### ISSUE TITLE
Add checks for pretraining networks that shouldn't be pretrainable

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1141]
Consider .pretrain(true) with a network that only contains dense layers and an output layer: network shouldn't be trainable using pretraining. Currently: no checks for this, and network training will proceed, not informing users that anything is wrong.

Example output with only Dense + OutputLayer:

o.d.n.m.MultiLayerNetwork - Training on layer 1 with 80 examples
o.d.n.m.MultiLayerNetwork - Training on layer 2 with 80 examples
o.d.n.m.MultiLayerNetwork - Training on layer 3 with 80 examples
o.d.n.m.MultiLayerNetwork - Finetune phase
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 41.438174438476565
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 41.30641479492188
o.d.n.m.MultiLayerNetwork - Training on layer 1 with 80 examples
o.d.n.m.MultiLayerNetwork - Training on layer 2 with 80 examples
o.d.n.m.MultiLayerNetwork - Training on layer 3 with 80 examples
o.d.n.m.MultiLayerNetwork - Finetune phase

**Comment by raver119** [comment]
@AlexDBlack                        I guess it's safe to close now, given recent API changes?

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
