### ISSUE TITLE
SequenceVectors label alternative

### ISSUE THREAD

**Issue by milanvdm** [eclipse/deeplearning4j#1180]
At the moment SequenceVectors is still depended on the getLabel() method. So basically you are reducing your SequenceElement to a word again. 

So in my opinion, there should be a more custom way on how to represent your SequenceElement. To make this work, I suppose the SequenceElement interface has to be extended with some methods:
- Generic return type for your getLabel()
- Compare method to compare your own implemented label to another label

Also the LookupTable has to be extended to handle those generic labels.

**Comment by raver119** [comment]
this is easy improvement, but label will be required for serialization to text via WordVectorSerializer

**Comment by Milanvdm** [comment]
Isn't it possible to have other Serializers? I'm thinking that maybe a label could return a Double, INDArray, ... I guess those objects can also be Serialized without being converted to text?

**Comment by raver119** [comment]
Yes thats sure possible, i'm speaking about exactly saving model to text file. Binary serialization is another thing :)

**Comment by Milanvdm** [comment]
Also when the SequenceVectors are plotted with TSNE, it would be great if the datapoints on the plot could have some other label based on the SequenceElement getTsneLabel() or something. Because SequenceVectors are hard to express and maybe a custom label for theTsne plot makes sense also.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
