### ISSUE TITLE
Documentation: add tasks-specific guides for common use cases

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1293]
The idea: add pages that guide users through the full pipeline for common tasks. This would be quite useful, especially for new users who want to build something on their own data.

Ideally we should have pages on the common use cases, such as:
- RNNs for natural language processing
- CNNs for image classification

These pages should provide details on (and code examples of) the full pipeline, in one place:
- What the options are for different input representations
- How to actually get data from the raw source to a representation suitable for learning (including, normalization etc)
- Basics on how to set up a suitable network architecture for different tasks (classification, regression, sequence classification, multi-task learning etc)
- How to evaluate the performance of your model (and potentially improve it)
- How to use the model at test time (inc. using same normalization methods, etc)

In the case of RNNs for NLP for example, it would be advantageous to clearly lay out the various options: word level one-hot, character level one-hot, using word2vec (or GloVe) vectors as input, using embedding layers in conjunction with RNN layers. Then talk about how to actually process raw data for each of these. And choices like bidirectional vs. standard LSTMs, when to use truncated BPTT vs. standard BPTT, etc.

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataVec & al. - improve open-source documentation related to workflow](https://trello.com/c/3u3jt2lF/5-datavec-al-improve-open-source-documentation-related-to-workflow)

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
