### ISSUE TITLE
Data structure for word vectors

### ISSUE THREAD

**Issue by montyhall** [eclipse/deeplearning4j#1310]
Request a feature where given:
1. LabelAwareListSentenceIterator 
2. tokenizer
3. wordvectors for unigrams and ngrams

creates a datastructure that contains, foreach unigram and ngrams
1. all vocab information
2. all labels
3. all vectors

thankyou  @raver119

**Comment by agibsonccc** [comment]
Won't this be handled by new nlp pipelines?

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
