### ISSUE TITLE
Generic Graphs for Deepwalk

### ISSUE THREAD

**Issue by milanvdm** [eclipse/deeplearning4j#1334]
The IGraph interface needs generic type from the objects in the Vertices/Edges. This implies that you can't make your own implementations for Vertex and Edge and use those for your own Graph class. 

I suggest making the generic types of IGraph as follows: `IGraph<V extends Vertex, E extends Edge>`

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
