### ISSUE TITLE
Word2Vec accept RDD[Seq[String]]

### ISSUE THREAD

**Issue by silentsnooc** [eclipse/deeplearning4j#1372]
It would be nice if `Word2Vec` could accept also `RDD[Seq[String]]`, a sequence of `String` where each element is a word in the corpus. That way I would not have to use TokenizerFactory and/or TokenPreprocessor but could just pass a sequence of words that I got from somewhere else to `Word2Vec`.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
