### ISSUE TITLE
Word2Vec set percentage for how much data to use in training

### ISSUE THREAD

**Issue by silentsnooc** [eclipse/deeplearning4j#1414]
Sometimes I want to test something very quick and/or check only if I broke my pipeline in any way. Afaik there is currently no way to tell `Word2Vec` to e.g. randomly skip some data.

It would be great to have something like

```
Word2Vec.Builder()
     .setTrainingDataPerentageToUse(0.05)
```

for reproducibility a second `seed` parameter might also be necessary.

I am not sure if that is a "_good_" solution but as for me I currently do it that way. I can even work on larger file on my local machine that way and I don't have subset files of that original file since that way it makes no difference.

PS: A different solution could also be to let e.g. the `LineIterator` internally decide if a line should be skipped but that could mean that there's just another method to implement which many people might not ever need.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
