### ISSUE TITLE
[Docs] Add minimal sbt file to quickstart guide

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1466]
Current quickstart guide has a minimal/example pom.xml file.
Adding a minimal sbt file for Scala users would also be helpful.

**Comment by crockpotveggies** [comment]
@tomthetrainer happy to help on this if you want to ping me on Gitter. it will be slightly tricky with classifiers

**Comment by saudet** [comment]
A good start could of what we have for nd4s: https://github.com/deeplearning4j/nd4s/blob/master/build.sbt

**Comment by huitseeker** [comment]
A good resource : 
https://github.com/wmeddie/dl4j-scalnet.g8
https://github.com/wmeddie/dl4j-scala.g8
https://github.com/wmeddie/dl4j-spark.g8

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataVec, workflow & al. - improve documentation](https://trello.com/c/3u3jt2lF/5-datavec-workflow-al-improve-documentation)

**Comment by huitseeker** [comment]
A good first step would be to integrate the giter8 profiles from @wmeddie  above, merge them into a dl4j repo, and document them in a page that would be the sbt + scala mirror of https://deeplearning4j.org/maven

**Comment by huitseeker** [comment]
Ideally this would integrate https://github.com/deeplearning4j/nd4j/issues/1850 as well

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
