### ISSUE TITLE
3D TSNE Visualisation

### ISSUE THREAD

**Issue by treo** [eclipse/deeplearning4j#1489]
Sometimes a 3D TSNE Visualization is more useful than a 2D one.
![3d-tsne](https://cloud.githubusercontent.com/assets/509379/14954429/aa154478-1072-11e6-9061-301b9c503009.gif)

And it looks nice :)

This example is created using the tourr R package.

**Comment by raver119** [comment]
Yes, we have discussed such feature earlier, and might add it later. Not a big deal - mostly just a question of D3 configuration.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
