### ISSUE TITLE
Consider and test alternative CNN mmul implementations

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1513]
Standard CNN implementations are based on im2col and mmul.
However, alternative implementations exist. For example, Nervana apparently uses an approach not based on im2col.
Benchmarks suggest the Nervana approach may be considerably faster: https://github.com/soumith/convnet-benchmarks
Some details and links to get started: see comment by Scott Gray here: https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/

I haven't looked into this in detail, but this is something we should look into more.

**Comment by AlexDBlack** [comment]
Convolution operations can also apparently be implemented using Toeplitz matrices:
https://en.wikipedia.org/wiki/Toeplitz_matrix#Discrete_convolution
https://github.com/torch/nn/blob/master/lib/THNN/generic/SpatialConvolutionMM.c

There are reports that this may provide superior performance.

**Comment by crockpotveggies** [comment]
As per Gitter conversation, Winograd is an alternative implementation for convolutional performance. We may want to implement that to keep up with standards on CPU performance.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
