### ISSUE TITLE
Avoid calculation of epsilons for first layer

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1529]
Currently, every layer calculates epsilonNext (i.e., errors to be passed to the layer below). However, in the case of the very first layer in the network (or, connected to the input in a CompGraph), this is unnecessary, as the array will not be used (no layers below the first one).
The only (rare) exception to this is when the MultiLayerNetwork is part of another MultiLayerNetwork or is part of a ComputationGraph, in which case there is (or, may be) another layer below the first layer in a MultiLayerNetwork.

**Comment by raver119** [comment]
I guess implemented long ago?

**Comment by AlexDBlack** [comment]
No, actually. Just hasn't been a high enough priority. Would require minor layer API changes too.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
