### ISSUE TITLE
Monitoring error in Word2vec trainings

### ISSUE THREAD

**Issue by cgravier** [eclipse/deeplearning4j#1627]
General NN models benefits from a monitoring tool ([see here](http://deeplearning4j.org/visualization))

On the contrary, this is not compatible with Word2Vec models.

A work around would be to able to log, at least, the error at each epoch.

The [latest commit in Word2Vec class](https://github.com/deeplearning4j/deeplearning4j/commit/5d5dfb6beeac6afaaf5b90d479bcad43b8e18c15) add a listener functionality (one can add a singleton of a SequenceVector instance) in order to hook a end-of-epoch listener.

In such case however, I don't see the functionality to fetch the current error from the Vord2Vec instance in order to log it in such a custom listener.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
