### ISSUE TITLE
GPUs load and multiple GPU on Word2Vec models

### ISSUE THREAD

**Issue by cgravier** [eclipse/deeplearning4j#1629]
It is possible to use cuda through openblas backend in order to train a Word2Vec model using a GPU.

However, regardless the batch size, the GPU overhead is not high (between 10 and 40%).
Moreover, on multiple GPUs settings, only 1 GPU is being used.

E.g. on a current model being trained : 

```
Wed Jun  1 18:26:11 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:01:00.0     Off |                  N/A |
| 26%   66C    P2    80W / 250W |    485MiB / 12287MiB |     31%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:02:00.0     Off |                  N/A |
| 22%   48C    P8    14W / 250W |    323MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```

Is there a way to increment the performance of the training phase ?

**Comment by raver119** [comment]
For now just don't use GPU for word2vec and its derivatives. 

Later we're going to introduce special gpu implementation for them, because x86 -> gpu transition for loads of axpy/dot calls isn't worth the hassle.

**Comment by raver119** [comment]
I mean - it's not impossible. It's just requires special approach, and we have that thing planned for implementation. But now we have more important improvements pending :)

**Comment by cgravier** [comment]
Sure, thanks for the info, I will go for the native backend.

I confess that I had some doubts about GPU backend for this task and I was looking for info after I posted this issue. I came across "Parallelizing Word2Vec in Shared and Distributed Memory" : https://arxiv.org/pdf/1604.04661.pdf from Ji et al. at Intel.

This could make you re-think... and anyway a nice reading, as most usually from this team.

**Comment by agibsonccc** [comment]
We have the new gpu backend out there now for word2vec.

**Comment by loretoparisi** [comment]
@raver119 which is the status of this i.e. Word2vec with GPU? @agibsonccc do you mean the hardware or a `dl4j` implementation of gpu (like Spark, etc.)?

**Comment by agibsonccc** [comment]
@loretoparisi  we intend on using a parameter server for that...the main problem we have is offsetting the effects of the large embeddings in memory.

**Comment by q463746583** [comment]
> @loretoparisi we intend on using a parameter server for that...the main problem we have is offsetting the effects of the large embeddings in memory.

So Do you multi-gpu version right now?

**Comment by raver119** [comment]
multi-gpu support will be available on next release i hope.

**Comment by loretoparisi** [comment]
@raver119 that's a great news!!!
