### ISSUE TITLE
Document similarity in ParagraphVectors is not intuitive

### ISSUE THREAD

**Issue by liugw198209** [eclipse/deeplearning4j#1643]
for example:
double sim = vec.similarity(doc1.getContent(), doc1.getLabel())
I try to get the similarity between the same document, but the above code will give me a very poor similarity (It is supposed to be 1).

The reason is:
the first vector (the first parameter) is the average vector of all words contained in doc1
the second vector (the second parameter) is the trained vector in paravector.

The simple geometric center of all words can't represent the document at all!

**Comment by tezer** [comment]
Any solution to this problem?

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
