### ISSUE TITLE
Review use of defaultConfiguration in MultiLayerNetwork and ComputationGraph

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1708]
Currently, MultiLayerNetwork and ComputationGraph instances have both a MultiLayerConfiguration/ComputationGraphConfiguration, _and_ a NeuralNetConfiguration ("defaultConfiguration" field), mainly so they can work with the optimizer/model. This design is a little ugly, and should be cleaned up so that we only have a single configuration object per neural network.

**Comment by raver119** [comment]
I guess it's safe to close now?

**Comment by AlexDBlack** [comment]
No, still relevant. Just hasn't been a high enough priority to fix.
