### ISSUE TITLE
Clean up network config JSON representation

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1715]
Consider the JSON representation a simple 2-layer network:
https://gist.github.com/AlexDBlack/6392cfe2047d622a23bd3957a545b4ca

Of note here are the entries that are not set, which are always included in the config regardless:
- Many null values
- Many NaN values
- Many empty arrays/objects: `{ }` or `[ ]`

I think it would be cleaner to do the following:
- Use Double instead of double for numerical values -> then use null instead of NaN for not set
- Set Jackson to not encode any null (not set) values
- Don't encode empty arrrays etc. in the JSON

**Comment by AlexDBlack** [comment]
Also: 'defaultConfiguration' and global/layerwise configuration duplication.

**Comment by raver119** [comment]
Is original issue still viable?

**Comment by AlexDBlack** [comment]
Yes

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
