### ISSUE TITLE
Spark: add averaging schedules for parameter averaging

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1722]
Add option to have averaging schedules. This will allow us to do a few iterations of 1-step synchronous averaging followed by every N steps. This may help convergence in some instances.

**Comment by agibsonccc** [comment]
Did we ever get around to this?

**Comment by raver119** [comment]
@AlexDBlack ping ^^^ :)

**Comment by AlexDBlack** [comment]
No, but it hasn't been a priority. More in the "nice to have" basket.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
