### ISSUE TITLE
Implement parameter sharing between layers

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1785]
Parameter sharing between layers is (essentially) not possible currently in ComputationGraph.

Initial though on how to implement this: we can just concatenate and de-concatenate activations in and out. So two layers with the same parameters would actually just be one Layer object, that gets twice as much input as normal layers.

**Comment by agibsonccc** [comment]
Closing in favor of: https://github.com/eclipse/deeplearning4j/issues/7408
