### ISSUE TITLE
Clarify Word2Vec graph plotting

### ISSUE THREAD

**Issue by ghost** [eclipse/deeplearning4j#1790]
method plotVocab() in http://deeplearning4j.org/word2vec#just in the model vizualisation paragraph with tsne, the method plotVocab() at line "vec.lookupTable().plotVocab(tsne);" is:
- not up to date, it should be replaced with the new method definition - perhaps with plotVocab(tnse, 20, server.getConnectionInfo()).
- Not clarified, users should be told to:
  1- Have an unused port (8080 used by default by UiServer)
  2- Head to localhost:8080 then to the TNSE section. (And since we get the response in the plotVocab method here https://github.com/deeplearning4j/deeplearning4j/blob/8f4f64571c45c7a2058c4c78038e796e9da7bc30/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/inmemory/InMemoryLookupTable.java#L207 why not retrieve the sid and open the tab directly?)
  Thx.

**Comment by agibsonccc** [comment]
Closing old issues.
