### ISSUE TITLE
Spark: Add evaluate methods for RDD<LabeledPoint>

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1811]
Spark distributed Evaluate methods are for RDD<DataSet> or JavaRDD<DataSet> only, currently.

https://github.com/deeplearning4j/deeplearning4j/blob/bed160b46d24ee4f1ea6331d372d49c75c831e58/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/multilayer/SparkDl4jMultiLayer.java#L390

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by agibsonccc** [comment]
Closing old issues.
