### ISSUE TITLE
Apache beam integration

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#1831]
Interest has been expressed in apache flink integration.

Instead what we may do is look at doing beam integration and swap out our spark integration.

Programming against dataflow allows us to have any backend we want and we can use 1 api for multiple streaming frameworks.

**Comment by arturroo** [comment]
Something is happening with this Apache Beam integration or is it dead?
It would be really nice to train Deeplearning4j models on SaaS like Google DataFlow in Scala and with data extracted from BigQuery with Spotify Scio.

**Comment by agibsonccc** [comment]
@arturroo just no time. (Sorry going through backlog now) At this point, we want to look more at inference, model import first over integration with the big data frameworks. We'll accept PRs though.
