### ISSUE TITLE
Rewrite LRN implementation

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1948]
https://github.com/deeplearning4j/deeplearning4j/blob/0dbd47dec3ba85476305d9e64267d90457d83850/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/normalization/LocalResponseNormalization.java#L108

Current implementation uses get/put in a for loop. This is slow and inefficient, and needs to be replaced - ideally with an efficient native implementation.

**Comment by raver119** [comment]
At this point we have LRN implementation as CustomOp, maybe we should just migrate it, once CUDA support is provided?

**Comment by AlexDBlack** [comment]
Yes, for sure 👍

**Comment by raver119** [comment]
LRN is available for CPU/CUDA + mkldnn. cuDNN will be added soon regardless of this issue.
