### ISSUE TITLE
ComputationGraph: Add check for layers that occur after OutputLayers

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#1961]
Output layers should be the final layer in a network; adding another layer (or, vertex) after an output layer isn't supported (and I don't think it should be). However, this isn't checked at present, at least in ComputationGraph (not sure about MultiLayerNetwork).

**Comment by raver119** [comment]
Was this implemented?

**Comment by AlexDBlack** [comment]
Not yet.

**Comment by agibsonccc** [comment]
Closing old issues.
