### ISSUE TITLE
VectorDot vertex in ComputationGraphConfiguration

### ISSUE THREAD

**Issue by AlexanderSerbul** [eclipse/deeplearning4j#2106]
Please add VectorDot operation Vertex to implement http://www.wildml.com/2016/07/deep-learning-for-chatbots-2-retrieval-based-model-tensorflow/ model. Thank you!

Aha! Link: https://skymindai.aha.io/features/DL4J-110

**Comment by raver119** [comment]
@AlexDBlack we have this implemented now i think?

**Comment by AlexDBlack** [comment]
Not yet. Shouldn't be hard to do.
