### ISSUE TITLE
Pass RNN hidden state to init other RNN from it

### ISSUE THREAD

**Issue by AlexanderSerbul** [eclipse/deeplearning4j#2107]
Please implement passing final hidden state of one RNN layer to initialize other RNN layer. it is needed to implement "Double encoded LSTM" model, described here: http://www.wildml.com/2016/07/deep-learning-for-chatbots-2-retrieval-based-model-tensorflow/

Thank you!

**Comment by agibsonccc** [comment]
This should possible with our samediff framework and TF import. Closing this.
