### ISSUE TITLE
Evaluation: add time series evaluation with metadata

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2142]
We have an "eval with metadata" method, but we don't currently have the equivalent for time series.
Made more complicated here by the fact that we have multiple predictions for multiple time steps...

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/eval/Evaluation.java#L203

**Comment by raver119** [comment]
Is this still viable issue?

**Comment by agibsonccc** [comment]
Closing old issues.
