### ISSUE TITLE
Feature Request: L2 pooling 

### ISSUE THREAD

**Issue by xae217** [eclipse/deeplearning4j#2150]
It would be nice to have an L2 norm pooling option available in SubsamplingLayer.PoolingType
Some advantages are described in this paper:
http://yann.lecun.com/exdb/publis/pdf/lecun-eccv-12.pdf

**Comment by raver119** [comment]
@AlexDBlack do we want this?

**Comment by AlexDBlack** [comment]
I haven't come across this much in the wild. So yes, but it's low priority.

**Comment by agibsonccc** [comment]
Closing old issues.
