### ISSUE TITLE
Website: add simple database of resources

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2157]
Proposal: add a simple searchable database of resources to the website.

Users would be able to search for resources by type (example, tutorial, blog post etc) and find relevant information more easily.
As we add more integrations, people are going to want specific information: i.e., how do I load data for Spark training, for storage library X? Or where are examples for Y?

For example, we'd have an entry (with tags and description) for each of:
- The current examples (individually)
- Third party examples
- Blog posts
- Minimal projects and/or starter POM files for different configurations: native, cuda, native + spark, CuDNN

Example, Lightbend's activator:
https://www.lightbend.com/activator/download
(download, extract, run "activator ui")
![image](https://cloud.githubusercontent.com/assets/2360237/19074875/1eb2fefc-8a8e-11e6-9151-529a23a51790.png)

**Comment by raver119** [comment]
I'd say: it would be cool to have similar thing like "activator ui", but obviously running on the web, without downloading anything.

**Comment by AlexDBlack** [comment]
Oh, and thing I forgot to mention: should make the actual content open source - i.e., people can add a file to a github repo (JSON format?), and have it automatically appear in UI.

**Comment by tomthetrainer** [comment]
This is a good idea, I was thinking of putting all the tutorials for example in a tutorial folder and build navigation panels and table of contents automatically from that. This is more than that, but same idea.

**Comment by agibsonccc** [comment]
Closing old issues.
