### ISSUE TITLE
Add profiler page (VisualVM/YourKit) to aid performance debugging

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2168]
Typical case: User comes to gitter. "X is slow!".
Typical response: (a) show me your configuration, and/or (b) show me visualvm/yourkit profiler.
Having instructions on how and why to do the latter would help at times.

(And add a gitter bot response for this)

**Comment by raver119** [comment]
Great idea :)

8 окт. 2016 г. 14:29 пользователь "Alex Black" <notifications@github.com>
написал:

**Comment by agibsonccc** [comment]
Closing old issues.
