### ISSUE TITLE
Encapsulate best practices for single desktop training

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#2192]
Right now users don't have a smooth segway in to creating and maintaining end to end training pipelines.

There are a few different concepts to consider:
Datavec for pre processing 
MInibatch serialization via BalanceMiniBatches and a datasetiterator
Efficient training and iteration over minbatches
The iterator itself: how to set it up with respect to the kind of data
they're dealing with.
Setting up an epoch: Users get confused with iterations (an update) vs epochs.

Solution: Encapsulate in some sort of a concrete pipeline object that knows hot to manage this flow for users.

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataVec & al. - improve open-source documentation related to workflow](https://trello.com/c/3u3jt2lF/5-datavec-al-improve-open-source-documentation-related-to-workflow)

**Comment by agibsonccc** [comment]
Closing old issues.
