### ISSUE TITLE
Apply preprocessor after last layer

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2218]
Idea: we can't currently apply an InputPreProcessor after the last layer, but we might need to. Not a high priority to fix, but this can come up in practice (for example, here: https://github.com/deeplearning4j/deeplearning4j/issues/2215).

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by agibsonccc** [comment]
Closing old issues.
