### ISSUE TITLE
Embedding layer parameter initialization: switch to f order

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2241]
Embedding layer extracts out rows.
Rows are contiguous in memory for C order, but strided access for F order.

DefaultParameterInitializer uses f order...
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/params/DefaultParamInitializer.java#L135

And embedding layer uses DefaultParamInitializer...
https://github.com/deeplearning4j/deeplearning4j/blob/11bd0f739f5cbbefc362c0aaf0bf7ef38b74ad05/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/EmbeddingLayer.java#L49

Only challenge here is to switch this without breaking serialized models...

**Comment by agibsonccc** [comment]
Maybe you could implement some kind of hooks for the serializer? eg: an adapter? Another thing we could do is add an ordering map for the parameters where the default is c ordering but could be f?

Make the ModelSerializer customizable to the outside world might be a bad idea but internal adapters might make sense here?
