### ISSUE TITLE
Modular GraphVertex allowing embedded ComputationGraph

### ISSUE THREAD

**Issue by crockpotveggies** [eclipse/deeplearning4j#2248]
As per discussion with @AlexDBlack there are some inherent issues with creating a `ModuleVertex` which allows for an embedded ComputationGraph. 1-output-array per vertex issue is a problem as well as avoiding duplicate configuration + parameter/gradient views.

Currently I've merged a modular Graph Builder in https://github.com/deeplearning4j/deeplearning4j/pull/2224 but as per @agibsonccc comments on https://github.com/deeplearning4j/deeplearning4j/pull/2202 a preferred approach would be a graph vertex.

Looks like this will take some work, so I'm opening this issue so it can be addressed.

**Comment by agibsonccc** [comment]
Closing old issues.
