### ISSUE TITLE
To add Android compatibility information for API calls

### ISSUE THREAD

**Issue by dharmeshrchauhan** [eclipse/deeplearning4j#2269]
It will be helpful if documentation of classes / api calls bears the information about whether it is supported in Android.

**Comment by dharmeshrchauhan** [comment]
Here is compatibility information which I found so far:

Class Name:  **DefaultTokenizerFactory**: 
https://deeplearning4j.org/doc/org/deeplearning4j/text/tokenization/tokenizerfactory/DefaultTokenizerFactory.html
Compatible with Android

Class Name:  **UimaTokenizerFactory**: 
https://deeplearning4j.org/org/deeplearning4j/text/tokenizerfactory/UimaTokenizerFactory.html
Not compatible with Android
Possible Reason: It depends upon parts of java beans library that are not supported in Android

Class Name: **PosUimaTokenizerFactory**: 
https://deeplearning4j.org/datavecdoc/org/datavec/nlp/tokenization/tokenizerfactory/PosUimaTokenizerFactory.html
Not compatible with Android
Possible Reason: It depends upon parts of java beans library that are not supported in Android

**Comment by agibsonccc** [comment]
Closing old issues.
