### ISSUE TITLE
Doc issue in RBM tutorial

### ISSUE THREAD

**Issue by BStudent** [eclipse/deeplearning4j#2324]
Re the intro to the doc for the RBM tutorial - which is excellent BTW - just wanted to offer this in the name of accuracy:
RBM was not invented by Geoff Hinton, that's a popular misconception.  It was invented by Smolensky and appeared in the famous 1986 PDP book as "Harmony Theory."  It was later popularized by Hinton.  P.S. I do not know them or any of their students, but I've been doing research on the history of NN.  Here is the citation to a free version of the Smolensky article:
Smolensky, Paul. “Information Processing in Dynamical Systems: Foundations of Harmony Theory.” DTIC Document, 1986. http://oai.dtic.mil/oai/oai?verb=getRecord&metadataPrefix=html&identifier=ADA620727.

_This is a preprint of Chapter 6 of D. E. Rumelhart, J. L. McClelland, and the PDP Research Group (in
press), Parallel Distributed Processing: Explorations in the Microstructure of Cognition. Volume [:
Foundations. Cambridge, rv1A: MIT Press/Bradford Books._

**Comment by agibsonccc** [comment]
Closing old issues.
