### ISSUE TITLE
"Pseudo" Online Training for DeepWalk

### ISSUE THREAD

**Issue by fgiasson** [eclipse/deeplearning4j#2367]
As discussed with @raver119 on Gitter, a good new feature for the next version of the DeepWalk implementation would be to enable "pseudo" online learning to its implementation.

The usecase that triggered this new feature is:

1. we have a static graph that initialized the DeepGraph instance and that got trained with it. Then
2. over time, we create new **leaf** vertices that only link to **existing** vertices in the graph
3. once a new node is added that way, a training pass would be performed on it

I named that feature "pseudo" only because if someone would use that new feature to do "full" online learning with the implementation, then if it would add new non-leaf vertices or if it would modify vertices within the graph, then innacuracies (errors) may crop in. However, it could still be used that way, but re-training of the whole graph would need to be performed if too many modifications have been performed on the graph.

**Comment by raver119** [comment]
Yep, so basically we're speaking about some kind of inference.

**Comment by agibsonccc** [comment]
Closing old issues.
