### ISSUE TITLE
Stats collection + Spark may use larger than expected memory

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2435]
Stats collection may use more memory than expected.

Best guess at this point: Agrona buffers aren't being garbage collected correctly? MapDB is running in the master (not the workers) and there's no other real differences between the stats and non-stats collection training configurations. In both cases, javacpp memory is being limited manually.

Though stats collection information shouldn't be taking up anywhere near this amount of memory, a few hundred MB max (though probably a lot less).

After many epochs on one training job, I'm seeing this:
```
16/12/05 03:20:41 WARN yarn.YarnAllocator: Container marked as failed: container_1447179492962_21174_02_000002 on host: [removed]. Exit status: 143. Diagnostics: Container [pid=20553,containerID=container_1447179492962_21174_02_000002] is running beyond physical memory limits. Current usage: 48.4 GB of 22 GB physical memory used; 115.0 GB of 46.2 GB virtual memory used. Killing container.
```

**Comment by saudet** [comment]
Does this happen only under Spark? Somewhat similar to #2401 perhaps?

**Comment by AlexDBlack** [comment]
So far I haven't seen any memory issues related to stats collection other than spark.

**Comment by huitseeker** [comment]
This should be helped by https://github.com/deeplearning4j/DataVec/pull/202 
What would be a good integration test for this issue, @AlexDBlack ?

**Comment by raver119** [comment]
@AlexDBlack                        Is this issue still viable?
