### ISSUE TITLE
Refactor Website Documentation

### ISSUE THREAD

**Issue by tomthetrainer** [eclipse/deeplearning4j#2451]
The Website Docs need Restructured into a coherent form. 

I propose the following: 

# DeepLearning4j Users Manual
### Preface and Legal Notices
It should have a license of some sort, Creative Commons perhaps, we will be accepting user content and writing stuff so some license, a permissive license but a license just the same. 
### Installing and Using DL4J
Overview of the pieces, DL4J, DataVec, ND4J, LibND4J

### Where to get help, and how to contribute

Put our quickstart in here, 
Other topics. 

* Creating a POM
* Updating
* Deploy

### Intro to Deep Learning
Give them the background, 
We have lots of docs that can be repurposed into this section

### Security

This is one of our advantages, we should promote it

### Some examples
Give them some text content to the examples

### Building a Neural Net
MultiLayerNetwork, MultiLayerConfig, MultiLayerBuilder

### Using DataVec
Core concept of what Datavec does. 

DataVec for CSV
DataVec for images
DataVec for Sequence data
DataVec Transform

### Distributed DL4J

Review our support, 
the challenge of backprop distributed explained. 
Parameter Server architecture

### ND4J
Creating arrays, 
modifying arrays
advanced concepts

### LibND4J

Switching to GPU's
how we are so fast. 
Internals, compiling,

**Comment by chrisvnicholson** [comment]
Re: the new Userguide directory proposal:

I don't understand the problem we're trying to fix with a new directory, I guess, because it feels like both relative and absolute links can break. 

Do you want to generate new content in the directory or move old content over there? If the latter, then my worry is we'll lose some of the SEO, or need to redirect a lot of pages.

**Comment by tomthetrainer** [comment]
Regarding Chris's concerns. 

The problem I would be trying to fix is to give it structure.
 
We have lots of good stuff, but just this week for example we both built a Keras Model Import page because we did not know what each other had done. 

A process of "update the table of contents" and add your content, would make things easier to manage. Or a directory of pages that an index/ Table of Contents is automatically built against would prevent that. 

So they could see a Table of Contents, search and find what they need. 

I hear you about redirects, so maybe new content would be the way to go. 

I am open to other suggestions, I just feel a refactor is a good path at this point.

**Comment by tomthetrainer** [comment]
My main point of this issue is this. We create a single document in response to an issue or a ticket and consider it solved.  Lacking structure however good content gets lost or is hard to find or efforts are duplicated.

I think I can work a middle ground, and that is to group tickets or issues and make more complete reference pages.

**Comment by agibsonccc** [comment]
Closing old issues.
