### ISSUE TITLE
Gpu verification instructions

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#2555]
Add GPu-Z on windows, nvidia-smi, and step by step instructions on how to verify the gpu is working with deeplearning4j.

**Comment by tomthetrainer** [comment]
Not sure I have an appropriate windows box to work on locally to verify.

**Comment by raver119** [comment]
I have windows box, and will be glad to help.

**Comment by agibsonccc** [comment]
Where are we on this?

**Comment by tomthetrainer** [comment]
I do not have the resources for this.

I was thinking of getting a GPU, but windows would not be my first choice,
if I get one, and if needed I suppose I could dual boot.

No progress...

**Comment by agibsonccc** [comment]
Closing old issues.
