### ISSUE TITLE
Spark: deletion of temporary files

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#2604]
Currently, users have to manually delete the temporary training files.
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/mlp/MnistMLPExample.java#L140

Downsides:
- Users may forget to do this
- The job may crash/fail before the manual execution
    - This is potentially solveable by intercepting any exceptions during training and performing a more graceful shutdown

Providing an option to delete *all* temp DL4J files would be possible, but would be very unsafe on a cluster (which may be running multiple training jobs in parallel)

**Comment by raver119** [comment]
Do you remember, if is this still relevant?
