### ISSUE TITLE
more "Document how to upload models for visualization. SUpport both dl4j and keras input"

### ISSUE THREAD

**Issue by bingyupiaoyao** [eclipse/deeplearning4j#2644]
we know in DL4J, we could use "UIServer" to visualize the model layer structure, but it only works when we 'fit' training data to the model, then we could see the model layer structure through the DL4J UI, is there any other way to visualize the model layer structure before we "fit" the data to the model? For example, if we import keras's model to DL4J, is there any better way to visualize the model layer quickly?

**Comment by tomthetrainer** [comment]
I am making this a feature request.
