### ISSUE TITLE
Add Gradient Check tutorial for custom models and loss functions

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#2647]
Usually when writing a custom layer or loss function you want to validate it "works' in some way. The way to do this is via gradient checks. 

1 common gotcha doing gradient checks is  setting the data type to double:
http://nd4j.org/userguide 

Examples of gradient checks are here:
https://github.com/deeplearning4j/deeplearning4j/tree/91a481ae8f5bcb4c9ff3463c1bba2df69d7325d2/deeplearning4j-core/src/test/java/org/deeplearning4j/gradientcheck

Custom loss functions and layers are here:
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/lossfunctions

https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers/CustomLayerExample.java#L125

The custom layer example has all of that information available - though perhaps it could appear on the website also.

**Comment by tomthetrainer** [comment]
Stub page exists, will complete this on this page..https://deeplearning4j.org/customizelossfunction

**Comment by agibsonccc** [comment]
Closing old issues.
