### ISSUE TITLE
Idea: create gists for exceptions automatically

### ISSUE THREAD

**Issue by raver119** [eclipse/deeplearning4j#2715]
Since we already have custom exceptions in most of places, we could avoid keep telling people "use gists!"

We could auto-post stack traces to REST-server, and provide shareable link for end-user, together with stack-trace. So, if user wants to deal with that himself - he has stack trace. If user wants some support - he can give us that link. That should also help with China.

What would you say guys? @agibsonccc @chrisvnicholson  @AlexDBlack @huitseeker @saudet @eraly

**Comment by AlexDBlack** [comment]
Auto post to REST server - that too could fail, adding complexity from the users perspective for debugging...

Alternatively: we could compress/hash the stack trace somehow? so you'd get an exception containing a base64 string (or similar), perhaps like "deeplearning4j.org/exceptions?zcgduoe873nzvouduo9h423thxuoep67" from which the original stack trace could be recovered (server side)

**Comment by raver119** [comment]
Mmm, that would be even better, if it won't be too huge.

**Comment by huitseeker** [comment]
Or we could use something like Sentry : https://sentry.io/welcome/
