### ISSUE TITLE
We should define what dl4j is "for" (People think we are closer to opencv)

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#2738]
There still seems to be a lot of confusion on what dl4j does. It would be good if we could try to explain
what you should expect to do with dl4j.

For example, we are lower level than stanford nlp or opencv with "canned" models.

However we are higher level than just a "math library".

**Comment by tomthetrainer** [comment]
Will probably add this to this page
https://deeplearning4j.org/overview

**Comment by agibsonccc** [comment]
Closing old issues.
