### ISSUE TITLE
Documentation for ParagraphVectors learning algorithms

### ISSUE THREAD

**Issue by oliverdain** [eclipse/deeplearning4j#2769]
I found it pretty confusing trying to figure out what the parameters `elementsLearningAlgorithm` and `sequenceLearningAlgorithm` mean for ParagraphVectors. First, the web page at https://deeplearning4j.org/word2vec says:

 > or using a word to predict a target context, which is called skip-gram. We use the latter method because it produces more accurate results on large datasets.

which lead me to believe that your implementation of ParagraphVectors was always DM. Was additionally confused because the JavaDoc contains those 2 parameters but I couldn't figure out what it would mean to set them both to different values.

Had a chat on gitter which cleared things up but Adam Gibson suggested I file a bug in addition so the docs will get updated.

**Comment by oliverdain** [comment]
You can find the conversation here: https://gitter.im/deeplearning4j/deeplearning4j?at=588d41941e4d4bd962a6a901

**Comment by tomthetrainer** [comment]
Thanks for the report

**Comment by oliverdain** [comment]
The logging is also confusing. I just trained a ParagraphVectors instance having set the SequenceLearningAlgorithm to DBOW. Here's the logs:

```
    15:17:14.021 [Test worker] INFO org.deeplearning4j.models.sequencevectors.SequenceVectors -           building SequenceLearningAlgorithm: [PV-DBOW]
    15:17:14.027 [Test worker] INFO org.deeplearning4j.models.sequencevectors.SequenceVectors -           building ElementsLearningAlgorithm: [SkipGram]
```

which seems to imply that skip-gram is still being used somehow.

**Comment by raver119** [comment]
DBOW is built on top of SkipGrame, and DM is built on drop of CBOW.

**Comment by agibsonccc** [comment]
Closing old issues.
