### ISSUE TITLE
Page on important Neural Networks

### ISSUE THREAD

**Issue by tomthetrainer** [eclipse/deeplearning4j#2774]
Not sure if we have this or not, if not we should build one, also wikipedia could use similar content

# Title Significant Neural Networks

## History and Background of the image prediction networks

ImageNet: 
Stanford University maintains and develops ImageNet. ImageNet is a labelled dataset of images. As of January 2017, ImageNet contained 14,197,122 images. 

ImageNet Challenge: Each year starting in 2010 research teams submit programs to the Imagenet Large Scale Visual Recognition Challenge (ILSVCR) . 

In recent years deep convolutional networks have taken the lead in accuracy at the challenge. 

Some Neural Networks have therefore become widely known and studied in the deeplearning community. If you are just getting started you should be aware of the following Neural networks. 

VGG16
VGG19
GoogleNet
Lenet
Inception

VGG Models. 

VGG models are developed by the University of Oxford's Visual Geometry Group. 
 http://www.robots.ox.ac.uk/~vgg/research/very_deep/

In ImageNet ILSVRC-2014 the VGG group had two Neural Networks that performed very well in the localization and classification challenge. The widely available configurations for the VGG models are VGG-16 and VGG-19, they are named for the number of Hidden Layers. 

The neural networks where tuned slightly afterwards and both the model configurations and the trained weights have been made available. 
https://gist.github.com/ksimonyan/211839e770f7b538e2d8#file-readme-md
https://gist.github.com/ksimonyan/3785162f95cd2d5fee77#file-readme-md

GoogleNet

Inception

**Comment by huitseeker** [comment]
Where would we put this ? Once we have a set format / emplacement for one of these descriptions, adding more becomes easy.

**Comment by agibsonccc** [comment]
Closing old issues.
