### ISSUE TITLE
RNN simple example and documentation improvement

### ISSUE THREAD

**Issue by svkap** [eclipse/deeplearning4j#2777]
Current RNN examples are too complex. It would be nice if you have a simple example using DataVec (I got the impression that for RNN it is required to construct INDArray manually). 

https://deeplearning4j.org/quickstart has a nice description on how to setup the dev env but it will be nice if you add links to basic getting started examples.

Section "DataSet, INDArray and Mini-Batches" in  https://deeplearning4j.org/core-concepts gives a good basic idea on the items but it makes the impression that DataSets and INDArrays should be used in order to work with dl4j. It would be nice if you add a warning that these are advanced and low level concepts and if you mention DataVec and give links to basic DataVec examples.

**Comment by agibsonccc** [comment]
Closing old issues.
