### ISSUE TITLE
ImagePipeline update docs

### ISSUE THREAD

**Issue by tomthetrainer** [eclipse/deeplearning4j#3124]
New ImagePipeline, clean up the docs to show use

**Comment by tomthetrainer** [comment]
Justin Long added this feature, it needs to be documented and examples need updated.

**Comment by tomthetrainer** [comment]
# Pipeline Image Transform

Pipeline Image Transform allows sequential or random collections of Image Transforms. 

## Contents

* <a href="#description">Description</a>
* <a href="#examples">Examples and Use Cases</a>
* <a href="#setup">Setup</a>
    * <a href="#prereqs">Prerequisites</a>
    * <a href="#step-by-step">Step-by-step</a>
      * <a href="#step-1">Step One</a>
      * <a href="#step-2">Step Two</a>
* <a href="#troubleshooting">Troubleshooting</a>
* <a href="#further-reading">Further reading</a>

## <a name="description">Description</a>

## <a name="examples">Examples and Use Cases</a>

## <a name="setup">Setup</a>

### <a name="prereqs">Prerequisites</a>

### <a name="step-by-step">Step By Step Instructions</a>

## <a name="troubleshooting">Troubleshooting</a>

## <a name="further-reading">Further Reading</a>

**Comment by crockpotveggies** [comment]
+1 for output

**Comment by tomthetrainer** [comment]
Completed page in local repo, will send to Mara for proofreading and merging

**Comment by tomthetrainer** [comment]
I am re-opening this, not sure it made it to public site

**Comment by tomthetrainer** [comment]
rewrite this page,simple-image-load-transform

Put into template, 
Check with @crockpotveggies to make sure I do not redo work he has already done.
