### ISSUE TITLE
Bug at UI

### ISSUE THREAD

**Issue by MikeF23** [eclipse/deeplearning4j#3126]
When I added UI, than I has exception: 
https://gist.github.com/MikeF23/17dad3a75a087d219db9e1e284d31d46

My source code:
https://gist.github.com/MikeF23/ebafc017c066c2238f6ecaf5bc815be7

**Comment by vlovsky** [comment]
Can you provide your data. I don't have anything in dl4j-examples/src/main/resources/tiny/
