### ISSUE TITLE
Spark training - planning and known issues

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#3157]
This issue is intended to be a summary of the various outstanding/known issues for our Spark implementation.

- Known issues
    - Export data has to be deleted manually (there is a convenience method); even with convenience method, data may not get deleted if crash occurs  https://github.com/deeplearning4j/deeplearning4j/issues/2604
    - Export data approach can fail for some systems https://github.com/deeplearning4j/deeplearning4j/issues/3134 https://github.com/deeplearning4j/deeplearning4j/issues/3133
    - Spark stats functionality: UI rendering doesn't scale well to long time periods (too much memory, large file size) https://github.com/deeplearning4j/deeplearning4j/issues/2663
    - Spark stats functionality: Relies on internet access for NTP server (built-in NTP functionality would be better)
(see also https://github.com/deeplearning4j/deeplearning4j/issues/2351)

- Additional functionality (some necessary, some 'nice to have')
    - Normalization: wrap existing normalizers for execution on Spark: https://github.com/deeplearning4j/deeplearning4j/issues/3119
    - DL4J UI: aggregate or average case (currently only stats for each worker separately)
    - Automatic detection of incorrect Spark version (trying to run DL4J spark 1 on spark 2, and vice-versa)
    - Real-time 'spark stats' functionality (i.e., for performance insights/debugging)
    - SparkDl4jMultiLayer and SparkComputationGraph - distribution evaluation convenience methods to match MultiLayerNetwork and ComputationGraph
( see also https://github.com/deeplearning4j/deeplearning4j/issues/1811 )
    - Convenience methods like 'feedForwardToLayer' etc
    - Sanity checks + warnings on memory management: detect likely misconfigured memory situations (like small/default off-heap and large heap memory) https://deeplearning4j.org/spark#memoryyarn

- Performance issues/notes
    - Integrate parameter server
    - Add async training methods
    - Networks are re-initialized each iteration; involves per-averaging overhead
    - Possibly not relevant given upcoming changes:
        - DataSet 'export with compression'
        - Parameter/gradient/updater state compression
    - Locality configuration: can we do something to avoid users having to set this manually? https://deeplearning4j.org/spark#locality

- Benchmarks
    - Benchmark repo: https://github.com/deeplearning4j/dl4j-benchmark/tree/master/dl4j-spark-benchmark
    - main conclusions from previous benchmarking work:
        - repartitioning is necessary (to get the correct number of examples/DataSet objects in each objects) but totally killed performance (synchorous and very slow)
        - Only approach (using built-in Spark functionality that I'm aware of) that had reasonable performance: export then pass around String paths (which are cheap to serialize/repartition)
        - Exporting then using PortableDataStreams: very bad performance
		
- Examples and docs
    - Need more examples
    - No documentation on spark data pipelines yet
    - Spark training data pipelines (images, video, etc) need to be easier to build/understand/modify

**Comment by raver119** [comment]
Is this issue still relevant?
