### ISSUE TITLE
Doesn't train elements vectors into ParagraphVectors.Builder

### ISSUE THREAD

**Issue by silvioOlivastri** [eclipse/deeplearning4j#3210]
Hi,

I have this code:

```java
      // ParagraphVectors training configuration
      VectorsConfiguration vectorsConfiguration = new VectorsConfiguration();
      vectorsConfiguration.setTrainElementsVectors(false);
      paragraphVectors = new ParagraphVectors.Builder(vectorsConfiguration)
              .learningRate(0.025)
              .minLearningRate(0.001)
              .batchSize(1000)
              .epochs(20)
              .iterate(iterator)
              .trainWordVectors(true)
              .tokenizerFactory(tokenizerFactory)
              .build();

      System.out.println("isTrainElementsVectors: "+paragraphVectors.getConfiguration().isTrainElementsVectors());
```

the output was: `isTrainElementsVectors: true`

So, I can't fit only labels.

My current solution is insert `trainElementsRepresentation(vectorsConfiguration.isTrainElementsVectors())` into Builder, but I think isn't good solution.

I propose this:

```java
        public Builder(@NonNull VectorsConfiguration configuration) {
            super(configuration);
            this.trainElementsVectors = configuration.isTrainElementsVectors();
        }
```

[here](https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/paragraphvectors/ParagraphVectors.java#L1010)

Ps: same thing for `this.preciseWeightInit` parameter.
Ps2: `<dl4j.version>0.8.0</dl4j.version>`

**Comment by raver119** [comment]
> .trainWordVectors(true)

You set it to true right in your builder.

**Comment by raver119** [comment]
I mean - paravec has 2 setters for this option. don't remember why though.

**Comment by silvioOlivastri** [comment]
Ok, thank you!

Why I can set all option trough `new ParagraphVectors.Builder(vectorsConfiguration) ...` except `preciseWeightInit` and `trainElementsVectors`?
