### ISSUE TITLE
ETL performance discussion thread

### ISSUE THREAD

**Issue by raver119** [eclipse/deeplearning4j#3292]
As we already know, single threaded ETL prevents proper scaling even for high-end systems, like DGX.

It happens due to the simple math behind data feeding logic: 
If single DataSet creation time takes X milliseconds, and neural network spends Y milliseconds training on it, optimal throughput will be achieved on Y/X parallel computing devices. If number of devices is more then Y/X - IO starvation will start, limiting overall system performance to performance level of Y/X devices.

General solution here is obvious too: make ETL parallel. 
Now we have parallel prototypes of **RecordReaderDataSetIterator** and **ExistingMiniBatchesDataSetIterator**, which are kinda able to confirm problem vision expressed above, and for pre-saved datasets parallel looks like like a solution. But not for DataVec-originated RecordReaderDataSetIterator. 

Problem there comes from fact: RecordReader instances by design return examples one by one, then each of those examples should be converted to DataSet, with subsequent merge call. And this call is definitely NOT free. So, when run in background, eventually merge call will take computation time, slowing down neural network training. It's just concat after all, so for dataset of 32 images, it'll be 32 tads of, say, 3x224x224. So, it'll eventually take some processing time, thus preventing training threads from getting full power.

So, original solution becomes less trivial here. As discussed with @AlexDBlack today, here are some options:
- some memcpy magic instead of concat during DataSet.merge()
- some putScalar() loops instead of concat during DataSet.merge()
- reconsider RecordReader api, to make it work on new level, say return BatchedWritables instead of individual examples, and process those at once.
- make special concat version, that'll be cpu-only even with CUDA backend

 There probably will be some more solutions, but general idea will be the same: ETL stuff should leave GPU, keeping it for training.

**Comment by raver119** [comment]
@AlexDBlack @agibsonccc @crockpotveggies thoughts guys?

**Comment by raver119** [comment]
P.s. i'm tending to prefer special cpu-only concat + BatchedWritables as additional option where applicable.

**Comment by crockpotveggies** [comment]
Is it possible to limit one of the operations above to CPU only to prevent GPU usage or is that what you mean by special concatenation?

**Comment by raver119** [comment]
Yes, that's it. DataSet merge is main time consumer, and essentially it's a concat, as explained above. So we don't really have to provide hybrid executioner right now, simple cpu-based concat impl in cuda codebase should do the trick.

**Comment by agibsonccc** [comment]
A batch per load being part of the api makes sense to me.We typically need to accommodate both even if we have to create batches by hand later (explicit batch creation is what the rest of the industry does anyways, we'd just make it easier)

**Comment by AlexDBlack** [comment]
- memcpy magic instead of concat:
    - Possible for CNN and MLP data only (and, then only in C order) - the examples are contiguous in the bufer
    - NOT possible for RNNs: we want to (essentially) concat(0) where the output is F order (necessary for RNNs). That, plus variable length, means we can't do memcpy here
    - Note that this memcpy magic is really just a special case for concat... we could implement it as such (i.e., as an optimization)
- "putScalar() loops" -> presumably, this means: fetch a batch (as INDArrays), then allocate a single ouput array (instead of one per example + merge)
    - Quick and easy (and, we should do it when we can), but if the bottleneck is higher up (i.e., in the record reader) then this won't be enough
- RecordReader -> BatchedWritable
    - It's a significant change, but I like it (or, I'd probably like the result :))
    - Makes sense to consider DataVec binarization at the same time. Consider CSVSequenceRecordReader: with 32 batch, 1000 sequence length, 128 vector size: that's 4,096,000 Writable objects per minibatch (we still have all the Strings too, but that's another issue)
    - Major downside I see: we end up needing parallelism within the RecordReaders themselves (could get a bit ugly with code duplication, complex for user extensibility etc?)
- CPU-only concat: If we can't avoid concat, then sure, why not. 

Another option:
- RecordReader -> Spliterator type design. i.e., split a single RecordReader into N independent (single threaded) record readers. For example, 4 ETL threads -> split RR into 4 RRs, each doing 1 out of every 4 examples (in sequence). Could have other split strategies too (4 threads -> fetch 4 contiguous batches, instead of interleaved + merge, at cost of greater memory)
    - Upside: keeps parallelism/threading out of the record readers - they are always single threaded. Only thing we need to add is splitting
    - Downside: we still need to merge at the DL4J level
    - For something like ImageRecordReader: it's actually pretty trivial to do the split. Less easy for CSV etc, but not impossible
    - Personally: I like this design

Another thought: RecordReaderDataSetIterator and RecordReaderMultiDataSetIterator - the former can be viewed as a special case of the latter. If we are making significant changes, it might be worthwhile combining the two at the time - i.e., have one single implementation to write and maintain?

**Comment by raver119** [comment]
Well, CPU-only concat is more like proof of bottleneck for parallel RRDSI. If we'll see perfromance improvement with CPU-only concat, then we'll be sure that moving ETL parallelism further away from GPU will help perf on high-end system.s

**Comment by saudet** [comment]
I also think we should keep RecordReader single-threaded. For CSV files, would it be possible to do something easy like Spark does with text files?

**Comment by wmeddie** [comment]
The SplitIterator type design that Alex mentioned is pretty much the way Spark/Hadoop InputFormats work.

It divides a file into N input splits, and each thread starts by finding the nearest boundary and starts processing from there until it reaches the last boundary inside it's assigned split.

**Comment by agibsonccc** [comment]
Could we do anything with InputSplits (already in datavec? :D) here?

**Comment by raver119** [comment]
> I also think we should keep RecordReader single-threaded. For CSV files, would it be possible to do something easy like Spark does with text files?

I believe all perf problems of CSV readers will be solved by batched output on it's own. CSV input is lighweight, so not a concern for us. Most of possible inputs are easy tbh, and only hard stuff, like huge timeseries, or images/audo require special treatment for us.

**Comment by raver119** [comment]
So, we've spent some time experimenting with different approaches of cpu-only merge.
TL/DR looks simple: it's efficient only with relatively small inputs.

For 72x3x96x96 it looks like this:
```
[DefaultTrainer thread 0] INFO org.deeplearning4j.optimize.listeners.PerformanceListener - Device: [1]; ETL: 0 ms; iteration 18; iteration time: 320 ms; samples/sec: 225.000; batches/sec: 3.125; score: 5.734360697675516;
[DefaultTrainer thread 1] INFO org.deeplearning4j.optimize.listeners.PerformanceListener - Device: [0]; ETL: 0 ms; iteration 18; iteration time: 314 ms; samples/sec: 229.299; batches/sec: 3.185; score: 5.933645557366625;
[RRDSI thread] INFO org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator - Compilation: 56 ms; Pull: 2 ms; Merge: 13 ms; Travel: 71 ms;
[RRDSI thread] INFO org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator - Compilation: 61 ms; Pull: 1 ms; Merge: 8 ms; Travel: 70 ms;
[DefaultTrainer thread 0] INFO org.deeplearning4j.optimize.listeners.PerformanceListener - Device: [1]; ETL: 0 ms; iteration 19; iteration time: 315 ms; samples/sec: 228.571; batches/sec: 3.175; score: 5.913925489758325;
[DefaultTrainer thread 1] INFO org.deeplearning4j.optimize.listeners.PerformanceListener - Device: [0]; ETL: 0 ms; iteration 19; iteration time: 316 ms; samples/sec: 227.848; batches/sec: 3.165; score: 5.868557665724082;
[RRDSI thread] INFO org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator - Compilation: 68 ms; Pull: 2 ms; Merge: 14 ms; Travel: 84 ms;
[RRDSI thread] INFO org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator - Compilation: 52 ms; Pull: 3 ms; Merge: 8 ms; Travel: 63 ms;
```

And for 128x3x224x224 it looks like this:
```
o.d.d.d.RecordReaderDataSetIterator - Compilation: 112 ms; Pull: 5 ms; Merge: 66 ms; Travel: 184 ms;
o.d.d.d.RecordReaderDataSetIterator - Compilation: 154 ms; Pull: 5 ms; Merge: 72 ms; Travel: 231 ms;
o.d.d.d.RecordReaderDataSetIterator - Compilation: 101 ms; Pull: 4 ms; Merge: 65 ms; Travel: 170 ms;
o.d.d.d.RecordReaderDataSetIterator - Compilation: 101 ms; Pull: 4 ms; Merge: 71 ms; Travel: 176 ms;
o.d.d.d.RecordReaderDataSetIterator - Compilation: 101 ms; Pull: 5 ms; Merge: 63 ms; Travel: 169 ms;
o.d.d.d.RecordReaderDataSetIterator - Compilation: 100 ms; Pull: 5 ms; Merge: 71 ms; Travel: 176 ms;
o.d.d.d.RecordReaderDataSetIterator - Compilation: 104 ms; Pull: 4 ms; Merge: 63 ms; Travel: 171 ms;
```

So, with input size growth DataSet.merge() starts taking more and more time. And time grows happens specifically within concat() method.

**Comment by saudet** [comment]
What is "Compilation" and "Travel"?

**Comment by raver119** [comment]
Compilation time: time spent building batch of List<Writable> in current design. So, for batch of 128 images - it's time for 128 calls for RecordReader.next()
Travel time: time from first RecordReader.next() call, to the end of DataSet.merge() call, it's the last call within ETL.

**Comment by saudet** [comment]
Ah, so loading images is slow, that's expected. :)

**Comment by raver119** [comment]
That's only the part of the problem. Right now the problem is that DataSet.merge() is takes time comparable (or bigger) to image loading. So i'm going to address this today, while keeping merge() mechanics for smaller inputs, like CSVRecordReader
