### ISSUE TITLE
Shutdown TokenizerThread properly

### ISSUE THREAD

**Issue by julianmaster** [eclipse/deeplearning4j#3359]
#### Issue Description

Running many time Word2Vec create many TokenizerThread but none of them was shutdown and live all the time of my working process. How I can clear and shutdown Word2Vec and his TokenizerThread ?

#### Version Information

* Deeplearning4j version 0.8.0 on Windows

#### Screenshot
![capture](https://cloud.githubusercontent.com/assets/1508942/25705015/12479854-30dc-11e7-9dc0-16f8ae3b09dc.PNG)

**Comment by raver119** [comment]
Right, according to according to your screenshot, they are doing nothing. But ExecutorService better be stopped.

Thanks for highlighting this issue.
