### ISSUE TITLE
Can not run CUDA example on Jetson TX1

### ISSUE THREAD

**Issue by gospodinbodurov** [eclipse/deeplearning4j#3458]
#### Issue Description

deeplearning4jtest-1.0/bin/deeplearning4jtest 10000 10
09:07:35.540 [main] INFO  deeplearning4jtest.CSVExample - Build model....
09:07:35.652 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:173)
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:36)
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:29)
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:19)
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:45)
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5753)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5694)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:184)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:677)
	at deeplearning4jtest.CSVExample.main(CSVExample.java:54)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:62)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:752)
	... 24 more

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.8.0
* platform information (OS, etc) - Ubuntu 16.04, arm64, Jetson TX1
* CUDA version, if used - 8.0
* NVIDIA driver version, if in use - 

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it! - I could help, if I can.

**Comment by agibsonccc** [comment]
Did you use nd4j-cuda-8.0-platform?

**Comment by gospodinbodurov** [comment]
Yes, I have it as dependency in my build.gradle file. I experimented with adding native and native-platform too, but with no success.

**Comment by saudet** [comment]
You'll need to build binaries for that. It should work pretty similar to linux-x86_64, but there is no instructions for that right now. If you could give it a try and report errors that you get here we could help you get this running though.

**Comment by gospodinbodurov** [comment]
Yep, I will give it a try. So, I have to build jnind4jcuda and nd4jcuda and add them to java lib path manually? Do you have some kind of instructions for doing this? Can you give me the repos you use?

**Comment by saudet** [comment]
Just build libnd4j and nd4j, in that order. Things will get packaged in JAR files afterwards, so there should be no need to do anything special once built.

**Comment by gospodinbodurov** [comment]
Thanks.

**Comment by gospodinbodurov** [comment]
./buildnativeoperations.sh
eval cmake
PACKAGING = none
BUILD = release
CHIP = cpu
ARCH = x86-64
CHIP_VERSION = 
GPU_COMPUTE_CAPABILITY = all
EXPERIMENTAL = no
LIBRARY TYPE = dynamic
/home/ubuntu/libnd4j/blasbuild/cpu
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
NOT CLION
CPU BLAS
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_CXX_FLAGS) 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BLAS
    COMPUTE
    DEV
    MKL_MULTI_THREADED
    PACKAGING


-- Build files have been written to: /home/ubuntu/libnd4j/blasbuild/cpu
/usr/bin/cmake -H/home/ubuntu/libnd4j -B/home/ubuntu/libnd4j/blasbuild/cpu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/ubuntu/libnd4j/blasbuild/cpu/CMakeFiles /home/ubuntu/libnd4j/blasbuild/cpu/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/ubuntu/libnd4j/blasbuild/cpu'
make -f blas/CMakeFiles/nd4jcpu.dir/build.make blas/CMakeFiles/nd4jcpu.dir/depend
make[2]: Entering directory '/home/ubuntu/libnd4j/blasbuild/cpu'
cd /home/ubuntu/libnd4j/blasbuild/cpu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/ubuntu/libnd4j /home/ubuntu/libnd4j/blas /home/ubuntu/libnd4j/blasbuild/cpu /home/ubuntu/libnd4j/blasbuild/cpu/blas /home/ubuntu/libnd4j/blasbuild/cpu/blas/CMakeFiles/nd4jcpu.dir/DependInfo.cmake --color=
Scanning dependencies of target nd4jcpu
make[2]: Leaving directory '/home/ubuntu/libnd4j/blasbuild/cpu'
make -f blas/CMakeFiles/nd4jcpu.dir/build.make blas/CMakeFiles/nd4jcpu.dir/build
make[2]: Entering directory '/home/ubuntu/libnd4j/blasbuild/cpu'
[ 33%] Building CXX object blas/CMakeFiles/nd4jcpu.dir/cpu/NativeOps.cpp.o
cd /home/ubuntu/libnd4j/blasbuild/cpu/blas && /usr/bin/c++   -D__CPUBLAS__=true -Dnd4jcpu_EXPORTS -I/home/ubuntu/libnd4j/include -I/home/ubuntu/libnd4j/include/helpers -I/home/ubuntu/libnd4j/include/loops -I/home/ubuntu/libnd4j/include/ops -I/home/ubuntu/libnd4j/include/types -I/home/ubuntu/libnd4j/include/cnpy -I/usr/local/include  -Wall -O3 -Wl,-rpath,RIGIN/ -march=x86-64 -mtune=x86-64 -Wall -O3 -std=c++11 -fassociative-math -funsafe-math-optimizations -fPIC   -o CMakeFiles/nd4jcpu.dir/cpu/NativeOps.cpp.o -c /home/ubuntu/libnd4j/blas/cpu/NativeOps.cpp
/home/ubuntu/libnd4j/blas/cpu/NativeOps.cpp:1:0: error: unknown value ‘x86-64’ for -march
 //
 ^
/home/ubuntu/libnd4j/blas/cpu/NativeOps.cpp:1:0: error: unknown value ‘x86-64’ for -mtune
blas/CMakeFiles/nd4jcpu.dir/build.make:65: recipe for target 'blas/CMakeFiles/nd4jcpu.dir/cpu/NativeOps.cpp.o' failed
make[2]: *** [blas/CMakeFiles/nd4jcpu.dir/cpu/NativeOps.cpp.o] Error 1
make[2]: Leaving directory '/home/ubuntu/libnd4j/blasbuild/cpu'
CMakeFiles/Makefile2:88: recipe for target 'blas/CMakeFiles/nd4jcpu.dir/all' failed
make[1]: *** [blas/CMakeFiles/nd4jcpu.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/libnd4j/blasbuild/cpu'
Makefile:152: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by raver119** [comment]
add `-a native` argument to build script.

**Comment by raver119** [comment]
`./buildnativeoperations.sh -a native && ./buildnativeoperations.sh -a native -c cuda -cc 53`

**Comment by gospodinbodurov** [comment]
Thank you, it is compiling. Will reach out when ready.

**Comment by raver119** [comment]
hm, why it picks arch as x86-64 for you at cmake? shouldn't that be arm?

**Comment by gospodinbodurov** [comment]
It compiled find after chaning -a to "native". Initially I didn't set -a parameter. Now I received the following result:









Killed
-- Removing /home/ubuntu/libnd4j/blasbuild/cuda/blas/CMakeFiles/nd4jcuda.dir/cuda/./nd4jcuda_generated_NativeOps.cu.o
/usr/bin/cmake -E remove /home/ubuntu/libnd4j/blasbuild/cuda/blas/CMakeFiles/nd4jcuda.dir/cuda/./nd4jcuda_generated_NativeOps.cu.o
CMake Error at nd4jcuda_generated_NativeOps.cu.o.cmake:257 (message):
  Error generating file
  /home/ubuntu/libnd4j/blasbuild/cuda/blas/CMakeFiles/nd4jcuda.dir/cuda/./nd4jcuda_generated_NativeOps.cu.o


blas/CMakeFiles/nd4jcuda.dir/build.make:66: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o' failed
make[2]: *** [blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o] Error 1
make[2]: Leaving directory '/home/ubuntu/libnd4j/blasbuild/cuda'
CMakeFiles/Makefile2:88: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/all' failed
make[1]: *** [blas/CMakeFiles/nd4jcuda.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/libnd4j/blasbuild/cuda'
Makefile:152: recipe for target 'all' failed
make: *** [all] Error 2

I suspect the process is killed because of out of memory. top command showed 2.6G taken for compilation.

**Comment by raver119** [comment]
Mmm, yes, it might take somewhere between 2.5 and 4gb for compilation.

How much ram do you have there? Also, can you please check dmesg, if that's oom-killer, it'll be mentinoned there then

**Comment by gospodinbodurov** [comment]
[111286.954683] Out of memory: Kill process 15555 (ptxas) score 817 or sacrifice child
[111286.962352] Killed process 15555 (ptxas) total-vm:3366164kB, anon-rss:3328404kB, file-rss:4kB

Jetson TX1 specs:
Memory: 4 GB 64 bit LPDDR4

**Comment by raver119** [comment]
what about swap? is it available there?

**Comment by gospodinbodurov** [comment]
Tc, no swap.

**Comment by raver119** [comment]
since that's regular linux on board, can you enable it, and give it couple of gigs?

**Comment by gospodinbodurov** [comment]
I will continue next week. Thank you for your help, will write soon.

**Comment by raver119** [comment]
Thanks, keep us informed please. I had no serious feedback from such devices before, so any information is more then welcome

**Comment by gospodinbodurov** [comment]
Hi again, I found 2 hours to play with the board. Could you find a better way to compile it, but not swap? It seems swap feature is not activated for TX1 kernel...... See this forum post for more information - https://devtalk.nvidia.com/default/topic/901380/tx1-swapon-failed-function-not-implemented/. NVidia devs promised to activate it, but with kernel 4.4.38-tegra, I am still receiving:
root@tegra-ubuntu:/home/ubuntu/swap# sudo swapon swapfile
swapon: swapfile: swapon failed: Function not implemented

And I will be really sad to recompile the whole kernel ;)

**Comment by raver119** [comment]
The only thing that comes to my mind, is truncated functionality. Remove some kernels when target cc is 53... i need to think about it, how to do that properly,

**Comment by gospodinbodurov** [comment]
Is it necessary to build these two libraries on TX1? I have some experience with C and C++ libraries for Android and I am pretty sure I could compile them for ARM on my host machine (x86-64) and just place them on the target one. I had to disable compiler asm optimization though. Do you think this trick is possible and whether will decrease the performance in our case? My intuition says it won't, because we are using heavily CUDA system, but not the ARM processor, but as I say it is just intuition.

**Comment by raver119** [comment]
CUDA doesn't allow cross-platform builds, that's their limitatio,not ours.

TX2 idea sounds good only if you know someone with TX2 :)

**Comment by agibsonccc** [comment]
https://devtalk.nvidia.com/default/topic/774092/jetson-tk1/cross-compiler-setup-for-jetson-tk1/

**Comment by raver119** [comment]
Hm, yea, looks like i'm wrong: https://devtalk.nvidia.com/default/topic/963488/switching-to-newer-toolkits-and-cross-compilation-support-/

**Comment by gospodinbodurov** [comment]
Great news!!!! If you want I can write a forum post on NVIDIA board asking for someone with TX2 to help us, and you can try this cross compiler stuff?

**Comment by agibsonccc** [comment]
Yeah we wouldn't mind trying to adapt this, if we can get this right we wouldn't mind adding this as a pre cooked binary. It's "just linux" anwyays.

**Comment by gospodinbodurov** [comment]
I agree with you. NVidia seems pretty serious with these boards and they will develop further their ecosystem. I would give a try with cross-compiling, but do not have CUDA video card, just couple of Intels ones. My own company business is more android and server side related. I want to make the shift to AI(we have strong algorithms background as competitive programmers), but will not happen fast...though we are working on couple university research projects related to robotics and these tx1 boards are grant. I am thinking of buying dedicated deeplearning dev box, but have no enough time for detailed hardware research. Can try to upgrade my current dev machine though. Unfortunately this wouldn't happen in next couple weeks.
So we have three options:
1) Memory optimize build
2) Cross compile build
3) Find someone with tx2
Currently I can help you only with option 3), because I don't have CUDA video card. For option 2) - I see you have build for android. Couldn't you use some similar techniques?

**Comment by agibsonccc** [comment]
Our android build involves similar cross compiling yes. I don't think we "need" a tx1 directly if you actually look at the links we've been posting. You likely just need to cross compile it. Of note here: You don't need a gpu to have "nvcc" which is all you need for the builds.

**Comment by gospodinbodurov** [comment]
Could you give me then some kind of tutorial for nvcc builds?

**Comment by agibsonccc** [comment]
Well - it would basically just be installing cuda with just the sdk without the driver You should be able to follow a normal cuda installation from the nvidia website and just use nvcc like that. Does that make sense?

**Comment by gospodinbodurov** [comment]
I think so. Thank you for your answer! Will give a try and answer back here.

**Comment by agibsonccc** [comment]
Sure of course - the only place the cuda installer *should* fail is when you go to try to install the driver only for it to find no gpu. nvcc doesn't "care"  which by proxy means the sdk.

**Comment by gospodinbodurov** [comment]
nvcc fatal   : Unsupported gpu architecture 'compute_53'
CMake Error at nd4jcuda_generated_NativeOps.cu.o.cmake:198 (message):
  Error generating
  /libnd4j/blasbuild/cuda/blas/CMakeFiles/nd4jcuda.dir/cuda/./nd4jcuda_generated_NativeOps.cu.o


blas/CMakeFiles/nd4jcuda.dir/build.make:58: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o' failed
make[2]: *** [blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o] Error 1
make[2]: Leaving directory '/libnd4j/blasbuild/cuda'
CMakeFiles/Makefile2:78: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/all' failed
make[1]: *** [blas/CMakeFiles/nd4jcuda.dir/all] Error 2
make[1]: Leaving directory '/libnd4j/blasbuild/cuda'
Makefile:139: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by raver119** [comment]
O_o

What CUDA toolkit version you're using there? Show what `nvcc --version` says

**Comment by gospodinbodurov** [comment]
It was 6.5...Ubuntu has legacy apt-get package nvidia-cuda-toolkit. Now it is 8.0.

**Comment by agibsonccc** [comment]
@gospodinbodurov Have you tried with 8.0?

**Comment by gospodinbodurov** [comment]
Mhm and I am receiving different error:

/libnd4j/include/fp16_conversion.hpp:6:23: fatal error: cuda_fp16.h: No such file or directory
 #include <cuda_fp16.h>
                       ^
compilation terminated.
CMake Error at nd4jcuda_generated_NativeOps.cu.o.cmake:198 (message):
  Error generating
  /libnd4j/blasbuild/cuda/blas/CMakeFiles/nd4jcuda.dir/cuda/./nd4jcuda_generated_NativeOps.cu.o


blas/CMakeFiles/nd4jcuda.dir/build.make:58: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o' failed
make[2]: *** [blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o] Error 1
make[2]: Leaving directory '/libnd4j/blasbuild/cuda'
CMakeFiles/Makefile2:78: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/all' failed
make[1]: *** [blas/CMakeFiles/nd4jcuda.dir/all] Error 2
make[1]: Leaving directory '/libnd4j/blasbuild/cuda'
Makefile:139: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by agibsonccc** [comment]
Something seems off here... Can you run:
ls /usr/local/cuda/include/ | grep cuda

Your cuda install might be in a different place though. Find your cuda install.

**Comment by gospodinbodurov** [comment]
cuda_device_runtime_api.h
cuda_fp16.h
cudaGL.h
cuda_gl_interop.h
cuda.h
cudalibxt.h
cuda_occupancy.h
cuda_profiler_api.h
cudaProfiler.h
cuda_runtime_api.h
cuda_runtime.h
cuda_surface_types.h
cuda_texture_types.h
cudaVDPAU.h
cuda_vdpau_interop.h


Looks fine. Maybe I am not setting some path variable correctly?

**Comment by agibsonccc** [comment]
I'm guessing your cuda install is screwed up some how. Did you set CUDA_HOME ? Did you remove the old cuda?

**Comment by gospodinbodurov** [comment]
It was CUDA_HOME not set properly. x86_64 build is fine now. I will experiment with linaro aarch64 compiler for cross compile.

**Comment by gospodinbodurov** [comment]
Cpu build is running fine, but with cuda I receive the following:

nvcc fatal   : Unknown option '-target-cpu-architecture'
CMake Error at nd4jcuda_generated_NativeOps.cu.o.cmake:198 (message):
  Error generating
  /libnd4j/blasbuild/cuda/blas/CMakeFiles/nd4jcuda.dir/cuda/./nd4jcuda_generated_NativeOps.cu.o


blas/CMakeFiles/nd4jcuda.dir/build.make:66: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o' failed
make[2]: *** [blas/CMakeFiles/nd4jcuda.dir/cuda/nd4jcuda_generated_NativeOps.cu.o] Error 1
make[2]: Leaving directory '/libnd4j/blasbuild/cuda'
CMakeFiles/Makefile2:88: recipe for target 'blas/CMakeFiles/nd4jcuda.dir/all' failed
make[1]: *** [blas/CMakeFiles/nd4jcuda.dir/all] Error 2
make[1]: Leaving directory '/libnd4j/blasbuild/cuda'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by raver119** [comment]
Show gist with full output log for CUDA build please

**Comment by raver119** [comment]
P.s. http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#cross-compilation

According to this doc, it just wants to see general compiler for target compilation...

**Comment by gospodinbodurov** [comment]
It looks like they deprecated this option (-target-cpu-architecture) in newest cuda toolkits. It is in 5.5 documentation, but not in 8.0. Do you still need the whole gist?

**Comment by saudet** [comment]
@gospodinbodurov You're getting that error on the host Ubuntu 14.04 machine with JetPack 3.0?

**Comment by gospodinbodurov** [comment]
I've just successfully build it. Do you want instructions or pull request? Btw how can I test the library on jetson? Do you have some kind of unit or integration tests?

**Comment by saudet** [comment]
Great! Please do send a pull request. There are unit tests for nd4j-cuda as part of nd4j, so just run those.

**Comment by gospodinbodurov** [comment]
However FindCUDA.cmake have to be changed. Finding static libraries is hardcoded. It is always searching for lib64 directory in /usr/local/cuda. I had to change the symlink to aarch64 target instead the original x86_64. I had to install Linaro aarch64-linux-gnu-gcc compiler and symlink it from /usr/bin. And I had to do apt-get install cuda-cross-aarch64, which install the aarch64 target for cuda.

**Comment by saudet** [comment]
Yes, sounds complicated, so please add those instructions in a new Markdown file in https://github.com/deeplearning4j/libnd4j, thanks!

**Comment by gospodinbodurov** [comment]
I want to run the tests first. Can you give me some kind of guide for doing it?

**Comment by raver119** [comment]
Most simple tests are something like executing simple examples. Like LeNetMnist probably.
If that works, and gives 0.97-0.98 - then you're ok.

**Comment by raver119** [comment]
Or, nd4j-tests, obviously. But i'd recommend LeNet :)

**Comment by gospodinbodurov** [comment]
You mean placing the libnd4j.so into Jetson TX1 lib64 directory and just start the deeplearning4j framework?

**Comment by raver119** [comment]
No, i mean building nd4j after you've finished libnd4j build, and put that jar into your .m2 folder in your jetson, then build your app there (unfortunately you'll have to do that, since your nd4j jar is special), and run mvn there

**Comment by raver119** [comment]
you you should copy your built libnd4j files to jetson, clone nd4j there, export LIBND4J_HOME var, and build your nd4j copy on your jetson box. Once nd4j build is finished - you can build anything with maven right there, and just run as any other jar

**Comment by gospodinbodurov** [comment]
Ok, thank you.

**Comment by iandow** [comment]
I'm interested in running deeplearning4j on the TX2. Can anyone help me out? 

I'm trying to prepare a deeplearning4j presentation for my local Java User Group this month, and if possible I'd like to show off the Nvidia Jetson TX2 in the process.

**Comment by agibsonccc** [comment]
@iandow all the help you should need is in the github issue. Follow the steps that @raver119 provided.

**Comment by iandow** [comment]
On a related note, nd4j build fails on the TX2.  Details at https://github.com/deeplearning4j/nd4j/issues/2180
