### ISSUE TITLE
UIServer activation graph not visible and model not shown correctly when setting pretrain true

### ISSUE THREAD

**Issue by tlaukkan** [eclipse/deeplearning4j#3573]
#### Issue Description

Root cause for this issue seems to be that the network data becomes corrupted due to underflows or overflows.

Please describe our issue, along with:
- Activation graph should be visible when setting pretrain true
- Model should show correctly when setting pretrain true. Currently shows only Input -> RBM (layer0)

#### Code

https://gist.github.com/tlaukkan/9b137f941cff2a4e879c95f9e1b512db

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 0.7.2, 0.8.0 (status of 0.8.1-SNAPSHOT is unknown)
* Windows 10
* CUDA 8.0

**Comment by agibsonccc** [comment]
Not relevant anymore
