### ISSUE TITLE
Android Documentation: minor fixes

### ISSUE THREAD

**Issue by ezorrio** [eclipse/deeplearning4j#3755]
Android Studio 3.0 introduced new Gradle, now annotationProcessors should be defined too
So add to gradle dependencies:
```groovy
annotationProcessor "org.projectlombok:lombok:1.16.16".
```
As there are some troubles with compilation, we also should exclude a few dependencies:
```groovy
configurations {
all.exclude module: 'jsr305'
all.exclude module: 'jcip-annotations'
}
```
If we are compiling snapshot versions, we should write dependencies like below as classifier doesn't work:
```groovy
compile group: 'org.nd4j', name: 'nd4j-native', version: '0.8.1-SNAPSHOT-android-arm'
```

**Comment by saudet** [comment]
Great! Please send a pull request for the https://deeplearning4j.org/android mentioning that.
