### ISSUE TITLE
Vulnerabilities found in dependency jars of dl4j

### ISSUE THREAD

**Issue by mdnoorit** [eclipse/deeplearning4j#3833]
Running dependency check over all the dependencies of dl4j jars throwing up following jars with vulnerabilities

 avro-mapred-1.7.7-hadoop2.jar
 commons-beanutils-1.7.0.jar
 commons-beanutils-core-1.8.0.jar
 commons-collections-3.2.1.jar
 commons-httpclient-3.1.jar
 curator-recipes-2.4.0.jar
 datavec-nd4j-common-0.8.0.jar
 ffmpeg-3.2.1-1.3.jar
hadoop-mapreduce-client-core-2.2.0.jar
hibernate-validator-5.0.3.Final.jar
httpclient-4.3.5.jar
jackson-0.8.0.jar
jackson-core-2.4.4.jar
jackson-core-asl-1.9.13.jar
jackson-jaxrs-base-2.5.1.jar
jetty-io-9.2.9.v20150224.jar
jetty-setuid-java-1.0.2.jar
jetty-util-6.1.26.jar
jetty-xml-9.2.9.v20150224.jar
logback-classic-1.1.2.jar
logback-core-1.1.3.jar
nd4j-api-0.8.0.jar
netty-3.8.0.Final.jar
parquet-hadoop-1.8.1.jar
py4j-0.10.4.jar
spark-core_2.11-2.1.0.jar
spring-core-4.1.6.RELEASE.jar
sqlite-jdbc-3.15.1.jar
tomcat-servlet-api-8.0.21.jar
unused-1.0.0.jar
xbean-asm5-shaded-4.4.jar
xz-1.5.jar
zookeeper-3.4.5.jar

**Comment by raver119** [comment]
Can you please provide link to vulnerability report?

**Comment by mdnoorit** [comment]
Please find the attached zipped html report
[report.zip](https://github.com/deeplearning4j/deeplearning4j/files/1214601/report.zip)

**Comment by raver119** [comment]
@agibsonccc @saudet @sshepel maybe we could use OWASP maven plugin here once we move to mono repo?


https://www.triology.de/en/blog-entries/automatic-checks-for-vulnerabilities-in-java-project-dependencies

**Comment by sshepel** [comment]
@raver119 sounds reasonable to me, will create an issue for this.
