### ISSUE TITLE
Documentation inaccuracy https://deeplearning4j.org/word2vec

### ISSUE THREAD

**Issue by johnhemming** [eclipse/deeplearning4j#3885]
#### Issue Description

On page:
https://deeplearning4j.org/word2vec

It states:
//Click:
    IntelliJ Preferences > Compiler > Command Line Options 
    //Then paste:
    -Xms1024m
    -Xmx10g
    -XX:MaxPermSize=2g

However, on the version of IntelliJ that I have just installed which is 2017.2.2 this causes an error as there is an option (I am running windows) Help > Custom VM Options - where the heap size should go.  Obviously this is not a problem for me, but might be a problem for someone else and it would perhaps be worth referring to Help > Custom VM Options in the documentation.

**Comment by nkwoh01** [comment]
@tomthetrainer @ShamsUlAzeem Can you address this discrepancy?
