### ISSUE TITLE
The library needs some detailed examples as well as documentation to explain the basics of theories 

### ISSUE THREAD

**Issue by ichenjia** [eclipse/deeplearning4j#3931]
#### Issue Description
Tensorflow documentation is great as it walks you step by step through some examples to explain the mechanics of the theories behind some of the algorithms. Most people have to rely on academic  papers to learn those things; unfortunately they are packed with formulas written full of Greek alphabets. It is very difficult to understand and solidify the knowledge. Without it, we cannot use the library effectively. 

A good example of documentation:
https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/16_Reinforcement_Learning.ipynb

**Comment by crockpotveggies** [comment]
Thank you very much for submitting this feedback. This will be very helpful for some of the docs overhaul that I'm working on currently.

**Comment by tomthetrainer** [comment]
@ichenjia Thanks for the feedback, 

If you have experience and time and would like to assist in our documentation effort let us know and we can help you get started. 

We do have some tutorials that have a similar goal as to what you describe in the tensorflow doc.

https://deeplearning4j.org/tutorials 

We can use more of course..
