### ISSUE TITLE
CPU twenty times faster than GPU on Tsne

### ISSUE THREAD

**Issue by deborahduong** [eclipse/deeplearning4j#3982]
raver119 told me this nd4j issue https://github.com/deeplearning4j/nd4j/issues/2079  should be deeplearning4j since the way the GPU is handled is standalone across models:

Issue Description

In the performance with the GPU vs. CPU on Tsne: the CPU is much much faster. On the GPU with the UI listener on, The GPU version does 35 or 40 seconds per handling 500 records, while the CPU version does 5 seconds per handling 500 records. The GPU version takes about an hour per iteration, while the CPU version takes 3 minutes per iteration. You can see my GPU and CPU training outputs, with times, at https://gist.github.com/anonymous/80230b3dcbd4a8409acd6238b7573f38. This should not be, because I am running on a HP Z440 /Intel Xeon E5 1620 v4 processor 3.5 GHz that has 77 GB/s memory bandwidth , with a Nvidia quadro p5000: fp 32 performance 8.9 tflpos, 2560 cores, that has a memory bandwidth 288 GB/s. So I am looking at software reasons. From looking at my output, do you have any suggestions? The GPU stack differs from the CPU stack (both below) in that it has more Garbage Collectors and different math.

Version Information

0.9.1 for all dl4j modules, cuda 8.0, java 1.8, windows 10

the nd4j issue has a picture of the stacks

**Comment by deborahduong** [comment]
I just tried my GPU out on the LSTM, and it was three times faster than the CPU - so this really is a TSNE coding performance issue.

**Comment by AlexDBlack** [comment]
TSNE has been completely overhauled since this issue was opened.
