### ISSUE TITLE
PW caused crash

### ISSUE THREAD

**Issue by firasdib** [eclipse/deeplearning4j#3995]
#### Issue Description
I tried using ParallelWrapper with the following configuration:
```
new ParallelWrapper.Builder<>(model)
                        .prefetchBuffer(0)
                        .trainingMode(ParallelWrapper.TrainingMode.SHARED_GRADIENTS)
                        .workspaceMode(WorkspaceMode.SINGLE)
                        .build();
```

And got the application crashed: https://gist.github.com/firasdib/42319a15fb7976f80990a488de112d0c

Tried with and without `ND4J_FALLBACK`.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.2
* platform information (OS, etc) Linux

**Comment by raver119** [comment]
First guess here: something wrong with zero-model weights.
