### ISSUE TITLE
Batch Balance Sanity Checker

### ISSUE THREAD

**Issue by treo** [eclipse/deeplearning4j#4185]
A problem that I've seen come up pretty often on gitter is that people run into the problem that their network learns to predict only one of two classes, and the other one is ignored.

One reason for that is that their batches may be unbalanced. It would be *nice to have* a Utility Method which calculates the distribution of labels across the batches in order to quickly diagnose that problem.

If no-one feels like picking that up, I'll probably just do it myself.

**Comment by AlexDBlack** [comment]
Hm, not a bad idea. Two thoughts
- For some use cases, this feels like it should be in datavec (AnalyzeSpark, for example)
- For everything else: maybe this could be implemented as a preprocessor? Only challenge there is when to stop collecting stats (i.e., do it for the first epoch only maybe - unless we decide to count the number of each label type that the network has seen, across *all* epochs instead?)

**Comment by treo** [comment]
I like the preprocessor idea. It would certainly simplify the conversation to just "Add BatchBalanceCheckPreprocessor to your DataSetIterator and take a look at what it outputs". 

When called it should then just log the distribution of labels. I wouldn't expect any further usage beyond that. It should be a diagnostic tool, not something that people leave on their iterator over multiple epochs.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Yeah. More of a nice to have feature, not a priority IMO
