### ISSUE TITLE
Building locally guide link to Intel MKL setup guide is out of date

### ISSUE THREAD

**Issue by slinlee** [eclipse/deeplearning4j#4316]
This link goes to a 404 now.

<img width="526" alt="image 2017-11-17 at 4 02 44 pm" src="https://user-images.githubusercontent.com/1197406/32974168-f2465a84-cbb0-11e7-8303-9e47001a3f9c.png">

**Comment by chrisvnicholson** [comment]
can add a link? i don't see mention of intel MKL on the quickstart page.

**Comment by slinlee** [comment]
Whoops, I meant the 'Building locally' page: https://deeplearning4j.org/buildinglocally#installing-prerequisite-architectures

The 'setup guide link'
