### ISSUE TITLE
Update japanese word2vec

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#4331]
#### Issue Description
https://deeplearning4j.org/ja/word2vec

Could we get this updated @saudet ?
Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
Updated how?
