### ISSUE TITLE
Common mistakes page

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#4382]
#### Issue Description
At some point we should write a common mistakes page.
At times we have people coming in to the gitter channel repeatedly asking the same questions.
It would help our support load if we had a page to point to instead.

A few common mistakes:
Grabbing random jars off of maven central(I am not sure why this happens)

Mixing and matching versions

Importing project in to intellij wrong

Not setting up an eclipse project right

Not checking the cuda versions

Over allocating memory in a variety of ways (allocating more memory than gpu, not understanding workload sizes)

Jumping right in to spark rather than  stepping back and understanding how single node works first

Running spark submit without trying to understand basic distributed systems knowledge like overhead of networking, file system access, worker and driver configurations, off heap memory configurations

Complaining about spark being "slow" without understanding how to run it, this often means they don't test or benchmark various batch sizes or setup their HDFS the wrong way

Forgetting to turn on workspaces for memory control

Configuring the UI the wrong way

Mixing scala versions

Mixing cpu and gpu without really trying to understand what an nd4j backend is

Mixing scala and play versions when building an uber jar leading to things like sbt-config mismatch when running spark or play.

Trying to run on 32 bit JVMs

Building from source when they don't need to.

**Comment by maxpumperla** [comment]
@agibsonccc maybe we should start a google sheet with this and every time a common request comes in in gitter, we add or increase a counter. My gut feeling says there's less common mistakes than we think.
