### ISSUE TITLE
Android deployment Website Section Typos

### ISSUE THREAD

**Issue by aldrin233** [eclipse/deeplearning4j#4400]
Code Sections have Html tags in https://deeplearning4j.org/android

namely, [This these two with the extra `<code>` Tags and below it an Extra `</span>` tag.](https://deeplearning4j.org/android#configuring-your-android-studio-project)

i'd like to add that even the class names are included which may bring confusion to newer users

additionally, maybe a tip for developers to use updated versions for imports. since 0.8.0 has some issues with current ones.

**Comment by aldrin233** [comment]
i'd like to add that even the class names are included which may bring confusion to newer users

**Comment by saudet** [comment]
Actually, @jrmerwin will working on updating this.

**Comment by jrmerwin** [comment]
@saudet The replacement document and new demo app are ready to go. I will swap them with the old one.

**Comment by saudet** [comment]
@jrmerwin Sounds good! Please note that the new repo for documents is at https://github.com/deeplearning4j/deeplearning4j-docs
