### ISSUE TITLE
[model-zoo] Add hints on model's memory requirement

### ISSUE THREAD

**Issue by fvaleri** [eclipse/deeplearning4j#4570]
#### Issue Description

I think that the `model-zoo` is really useful, but it isn't always clear what are the model's memory requirements. It depends on the particular use case, but I think that give some numbers on a real example could be helpful.

Something like this:

| Example | Model | Total Params | Batch Size | Train % | RAM (Mb*) | Disk Space (Mb) |      
|---------- |---------|---------------:|------------:|---------:|-------------:|------------------:|
| [Flower](dl4j-examples/dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/EditLastLayerOthersFrozen.java) | VGG-16 | 134281029 | 15 | 80 | 6765 | 929 |
| ....

(*) Estimated value with `model.getConfiguration().getMemoryReport(...)`.

#### Version Information

Deeplearning4j 0.9.0+

**Comment by ejunprung** [comment]
Hi @fvaleri. This is a good idea, but I think there are too many permutations for us to provide memory requirements for each case. On my system, I have 32GB of memory and 500 GB of space. I haven't had issues running models from the Model Zoo. 

Do you happen to have a hard limit on memory for reasons other than budget (i.e. buying more RAM, disk space)?

**Comment by fvaleri** [comment]
Hi @ejunprung , currently I'm using a weak system that I can't touch (core i5, 8 GB RAM, 250 GB disk).
I can afford a better system, but this is the standard configuration in my company and I'm just exploring dl4j by myself. Anyway, I managed to run "Flowers" example on this system using workspace modes.

I see that there are too many permutations, but maybe we can collect here only some well known use cases that, eventually, can be included in the doc just to give a better sense of what means to leverage a pre-trained model. We could also add the link to the model's dl4j-benchmark.

**Comment by ejunprung** [comment]
Hi @fvaleri, that sounds like a great idea. Let me loop in @nkwoh01 who would need to help facilitate that. 

More broadly, we should probably start with [minimum hardware requirements](https://docs.skymind.ai/docs/single-server-requirements). Perhaps you could run DL4J on your own personal computer for now. From there, we can probably note which models have high memory requirements to set expectations.

**Comment by fvaleri** [comment]
Yep, I'll post here my experiments results related to transfer learning.
My system configuration can be reported as minimum hardware requirements for VGG-16.

I think that 2-3 more examples with minimum/recommended requirements can be enough.
This could help to build interesting demo projects without big hardware/time investment.

**Comment by ejunprung** [comment]
@fvaleri Sounds great, thank you. I will add your results to the documentation. I will try to look into this myself as well once things free up a bit!
