### ISSUE TITLE
Connectionist Temporal Classification ?

### ISSUE THREAD

**Issue by doofin** [eclipse/deeplearning4j#4746]
#### Contributing

What's the approximate steps of implementing this? 

http://www.cs.toronto.edu/~graves/icml_2006.pdf

**Comment by doofin** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/2746

**Comment by saudet** [comment]
We basically need to implement a custom loss function: https://deeplearning4j.org/customizelossfunction

Here are some implementations we can refer to:
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/ac/ActorCriticLoss.java
https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/impl

**Comment by saudet** [comment]
Actually, we might need to implement a custom layer, which would look like this:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/objdetect/Yolo2OutputLayer.java
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/objdetect/Yolo2OutputLayer.java

Some documentation about that at https://deeplearning4j.org/devguide#adding-new-layers-to-dl4j
