### ISSUE TITLE
Suspected bug in Barnes-Hut-SNE implementation

### ISSUE THREAD

**Issue by melanietosik** [eclipse/deeplearning4j#4785]
I recently tried to visualize some _word2vec_ embeddings and got [pretty terrible results](https://i.imgur.com/IzuN6kc.png) using the default [_BarnesHutTsne_](https://deeplearning4j.org/doc/org/deeplearning4j/plot/BarnesHutTsne.html) implementation. Performance was poor across multiple different parameter settings, so optimization there didn't really help. I'm not 100% sure where the problem is or whether this generalizes to other types of data, but I just wanted to raise a flag.

Setting `theta=0.0` fixed this problem because apparently there is a special case implemented for this that results in just regular t-SNE (_decomposedTsne_) being used within _BarnesHutTsne_. This should be documented more explicitly. I also found that _decomposedTsne_ ran an order of magnitude faster than _BarnesHutTsne_, which is the opposite of how it should be. 

**Version info**

* Deeplearning4j version: `0.9.1`
* Platform information: macOS Sierra (10.12.6)
* Java version:

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by anomal** [comment]
I also got incorrect results using BarnesHutTsne with sample data from dl4j-examples/src/main/resources/raw_sentences.txt. The closest words to "day" are `[night, week, game, year, season, time, office, group, war, director]` according to Word2Vec's `wordsNearest`, but [BarnesHutTsne plots "day" and "week" far apart](https://imgur.com/a/gpLD5sy) on opposite quadrants. 

When I set theta=0.0, using the default TSNEStandardExample.java with only theta changed, I get the following exception:
```
Exception in thread "main" java.lang.IllegalStateException: Can't transpose array with rank < 2: array shape [140]
	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:304)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.transpose(BaseNDArray.java:4356)
	at org.deeplearning4j.plot.Tsne.x2p(Tsne.java:278)
	at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:120)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:515)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:754)
	at shortlister.wordvectorizer.TSNEStandardExample.main(TSNEStandardExample.java:76)
```
**Version info**

- Deeplearning4j version 1.0.0-beta4
- Platform information: Ubuntu 16.04
- Java version:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

**Comment by raver119** [comment]
Unfortunately, with theta = 0.0, there's old TSNE executed.

**Comment by raver119** [comment]
Also, BarnesHutTsne was overhauled recently to match reference implementation, however there was no release yet.

**Comment by raver119** [comment]
@anomal can you please file new issue about original (non-BarnesHutTsne) please?
