### ISSUE TITLE
wordsNearest returns different words after uptraining Word2Vec and doing buildVocab

### ISSUE THREAD

**Issue by ntaherkhani** [eclipse/deeplearning4j#4810]
#### Issue Description
I am trying to uptrain word2vec model that I restored from GoogleNews-vectors-negative300.bin.gz pretrained word2vec model, to add my new corpus words to the vocabs list of model.
the wordNearest results are totally different before and after buildVocab and fit. 
for example:
before uptraining: wordsNearest("day", 5) -> [week, days, morning, month, hours]
after uptraining :wordsNearest("day", 5) -> [Yamhill_County, shaking, Houghton_Kepier, cleric_Allama_Hassan, Emilie_Mondor]
Number of vocabularies increases after doing buildVocab and fit , but the nearest words change and they are not reasonable. 

* Deeplearning4j version : "0.9.1"
* Nd4j version : "0.9.1"
* platform information : Windows

**Comment by raver119** [comment]
Please show how you've set up uptraining. Your model's output looks corrupted so far.

**Comment by ntaherkhani** [comment]
Thanks for your response and sorry for answering late. 
I am codding through Scala. 

val iter: SentenceIterator = new BasicLineIterator(new File("Path of new corpus"))
var w2v = WordVectorSerializer.loadGoogleModel(new File("/GoogleNews-vectors-negative300.bin.gz"), true, false)

val dayNearestWords_beforeUpTrain= w2v.wordsNearest("day", 5) // @return  [week, days, morning, month, hours]

var t: TokenizerFactory = new DefaultTokenizerFactory();
t.setTokenPreProcessor(new CommonPreprocessor());

w2v.setTokenizerFactory(t)
w2v.setSentenceIterator(iter)
w2v.buildVocab()
w2v.fit()


val dayNearestWords_afterUpTrain= w2v.wordsNearest("day", 5) //@return [Yamhill_County, shaking, Houghton_Kepier, cleric_Allama_Hassan, Emilie_Mondor]



Thanks.

**Comment by raver119** [comment]
I see.

That's expected behavior. If you'll check wordsNearest() javadoc, you'll see warning about normalization being applied.

do NOT call wordsNearest before training.

**Comment by ntaherkhani** [comment]
I removed the wordsNearest before up-training , but I got inconsistent nearest words for "day".

[Heavenly_Ski, Sipera_UC_Sec_Sipera, EMEA_Structured_Finance, Ranero, Gen_Thein_Sein]

**Comment by raver119** [comment]
Show your _current_ source code please.

**Comment by ntaherkhani** [comment]
it is same as I sent in previous one. I just removed the wordsNearest before fit().


val iter: SentenceIterator = new BasicLineIterator(new File("Path of new corpus"))
var w2v = WordVectorSerializer.loadGoogleModel(new File("/GoogleNews-vectors-negative300.bin.gz"), true, false)

var t: TokenizerFactory = new DefaultTokenizerFactory();
t.setTokenPreProcessor(new CommonPreprocessor());

w2v.setTokenizerFactory(t)
w2v.setSentenceIterator(iter)
w2v.buildVocab()
w2v.fit()

val dayNearestWords_afterUpTrain= w2v.wordsNearest("day", 5)
