### ISSUE TITLE
KMeans implementation is slow

### ISSUE THREAD

**Issue by jentfoo** [eclipse/deeplearning4j#4882]
I opened an issue on javacpp when this was discovered ( https://github.com/bytedeco/javacpp/issues/231 ).  There are currently some changes in `master` that will improve this situation, but even with those changes there is SIGNIFICANT gains that can be done on the deeplearning4j side as well.

I personally see a few options with this:
* Change the API to allow a create / dispose lifecycle so that resources can be reused easier
* Perhaps some internal caching or other changes we can do to reduce native object churn
* Don't use javacpp for kmeans

I would like to hear your perspective on this, but I personally don't think kmeans is an algorithm that has a lot to gain from native offloading.  Maybe there is some cases where this is not the case, but in every example I have made, native seems to slow it down more than gain.  Cuda is even worse for me.  Instead rather just keeping things in heap has performed the best.

To give an idea of possible gains....Speed when running with master of javacpp (physicalByte check improvement included):
```
real	2m37.982s
user	9m5.801s
```

Same data running against an implementation I made that is entirely maintained within the heap:
```
real	0m6.407s
user	2m24.741s
```

Let me know your thoughts here.  Thanks!

**Comment by saudet** [comment]
If we can't use workspaces for the loop at
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nearestneighbors-parent/nearestneighbor-core/src/main/java/org/deeplearning4j/clustering/algorithm/BaseClusteringAlgorithm.java#L109
we would be able to use PointerScope instead: https://github.com/bytedeco/javacpp/commit/d98d323778c4b73865d19c7fc15c8380b130f5e0

**Comment by jentfoo** [comment]
I am not convinced that kmeans is an

**Comment by jentfoo** [comment]
I am not convinced that kmeans is an algorithm that makes sense with the native Pointers at all.  I think you would need to reduce how many times you need to go in and out of native space.

While I recognize my pure java implementation may not be right for all use cases, in my use case it seems pretty well suited.  I can't see how to make Pointer alone solve the problem.

Perhaps if the kmeans algorithm itself was implemented natively and you only need to jni into that operation would be as good as it gets.
