### ISSUE TITLE
deeplearning4j-scaleout-parallelwrapper has too many transitive dependencies

### ISSUE THREAD

**Issue by treo** [eclipse/deeplearning4j#4959]
In order to use ParallelInference the deeplearning4j-scaleout-parallelwrapper module is needed. It depends on deeplearning4j-core which in turn pulls in all of dl4j. 

I think that explicitly depending on just the dl4j modules that are really needed would be the better approach here.

**Comment by AlexDBlack** [comment]
deeplearning4j-play might also not be required? https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-scaleout-parallelwrapper/pom.xml#L77-L81

**Comment by agibsonccc** [comment]
The reason that thats' there: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-scaleout-parallelwrapper/src/main/java/org/deeplearning4j/parallelism/main/ParallelWrapperMain.java - we could consider splitting out inference in to a stand alone module?

**Comment by AlexDBlack** [comment]
Yeah, that would make sense.

**Comment by saudet** [comment]
One thing: Make sure to run your build with `mvn -Djavacpp.platform=<os>-<arch> ...`
