### ISSUE TITLE
Improve InputType and Time Distributed Functionality

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#4997]
Currently we have 3 input types:
- feedForward
- recurrent
- convolutional

And soon to have one more for conv3d

What I would like to add/change:
- A "time distributed" input type
- Add an input type specifically for embedding layers (integer index type)
- Rename "recurrent" -> "time series" or "sequence" (InputType.recurrent + conv1d is a bit confusing)
- Data formats (NCHW/NHWC, etc)
- Add InputType support for variable-length inputs (like: fully convolutional -> pooling -> dense)

I would also like to add a TimeDstirbuted layer - this might be clearer/cleaner than preprocessors in some cases?

Finally, some serious thinking/design work needs to be done for time distributed Convolutional, and even "sequences of sequences" stuff.
Mask arrays for all of  these needs to be considered also.

**Comment by maxpumperla** [comment]
@AlexDBlack the only worry I have w.r.t. introducing more granular types is that when adding a new input type to the existing N types, you need to create 2 * N preprocessors, but I guess we have to live with that.

+1 for TimeDistributed and data formats

**Comment by rnett** [comment]
From the glitter, what I currently have is two layers, Distribute and Collate.  Distribute takes a target dimension, and Collate takes the target dimension (same as Distribute's) and the size of the distributed layer (necessary to reconstruct).  Each layer uses a reshape operation and a permute operation.  This only works if the shape doesn't change majorly.

Implementing a wrapper is also doable, but this approach supports multiple time-distributed layers without having to reshape and permute each time.  That said, it doesn't have the same issues with changing shapes, and if you limit it to disturbing the first dimension, it only uses 2 reshapes.

Imo, I would implement both.

It would also be possible to implement them as processors, if that would be useful, but I haven't looked at it enough to tell.  The issue would be knowing what size to restore the distributed dimension too.


As far as the implementation goes, implementing it as a as a WrapperLayer is easy enough, the only part that might be tricky is the masking.

Unless I'm misunderstanding it, I would just need to reshape the mask array in the `feedForwardMaskArray` method, call the underlying method on it, and then un-reshape it?

**Comment by rnett** [comment]
For the mask, as far as I can tell:
 * 4d mask -> Conv2D ->reshape [minibatch*timeSeriesLength, 1, 1, 1] to [minibatch,timeSeriesLength]
 * 2d mask -> RNN/Conv1D -> reshape [minibatch,timeSeriesLength] to [minibatch * timeSeriesLength]

Since we are only ever losing one dimension, we only have to worry about Conv2D -> RNN and RNN -> FF.

Is this correct?  If it is, I can implement it.

**Comment by AlexDBlack** [comment]
Recently added - https://github.com/eclipse/deeplearning4j/blob/1930d9990810db6214829c716c2ae7eb7f59cd13/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/inputs/InputType.java#L198
