### ISSUE TITLE
Add ability to get libnd4j commit hash

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5053]
In ND4J we have version check functionality, which allows us to get the commit hash etc for most of our projects (nd4j, dl4j, datavec, arbiter, etc).
It would be nice if this could be extended to libnd4j somehow.

**Comment by saudet** [comment]
That can be added to the pom.xml file, but since the binaries get bundled with ND4J, it wouldn't be useful for that right now. Should we have standalone JAR files for libnd4j? We could strip out JavaCPP from ND4J and have all that in libnd4j..

**Comment by AlexDBlack** [comment]
Or, can we somehow inject the hash into the source (say, first step in the ```buildnativeoperations.sh``` script) which can then be called from Java?
We don't necessarily have to use the same maven/git properties-based version check functionality we use for our Java code.

**Comment by raver119** [comment]
That's trivial:
1) buildnativeops.sh modifies special file, i.e. version.h - it write 1 or few lines there, i.e. defining LIBND4J_COMMIT_HASH 
2) we add NativeOp method, which literally returns LIBND4J_COMMIT_HASH as `char *`
3) we invoke that method from Java.

**Comment by raver119** [comment]
@sshepel we already have it implemented, right?

**Comment by sshepel** [comment]
> @sshepel we already have it implemented, right?

I don't think so...
