### ISSUE TITLE
Fast tests pipeline

### ISSUE THREAD

**Issue by raver119** [eclipse/deeplearning4j#5085]
For pull requests we have (and must have) full-blown CI/CD pipeline. We test everything on all platforms etc.

But for engineers i think it would be awesome to have "fast pipeline", which will include only x86_64 Linux (since it fully supports parallel builds) and after we have CUDA support for new ops - Linux CUDA for 1 arch.

So idea is to use fast pipeline as Continuous Testing platform for working branches. So, during development engineers will be informed about upstream problems before PR created. I.e. if some libnd4J change breaks something at DataVec or DL4j. It would be better if engineers were notified sooner rather then later.

cc @sshepel @saudet

**Comment by raver119** [comment]
cc @agibsonccc @AlexDBlack

**Comment by AlexDBlack** [comment]
I like the idea, and something similar crossed my mind recently (after thinking about this: https://github.com/deeplearning4j/deeplearning4j/issues/5058)

What could this look like? For DL4J, perhaps this could be a set of simple integration tests.
Specifically, training a model (CNN, dense, LSTM, etc) for say 10 iterations (from real data - ImageRecordReader + RRDSI etc) and comparing the training curve (score vs. iter) and gradients at each step vs. a previous known-good run. A few of those sorts of tests are likely to catch a non-negligible fraction of breaking changes.

**Comment by raver119** [comment]
I'd say - we need the same tests we have right now, but:

1) Only on Linux, because it's faster.
2) Only on 1 arch, because we dont care about other archs.

If the box will be fast enough, tests will take:
- libnd4j:  2-4 minutes depending on real computation power. 
- nd4j: 3 minutes build time + 5-10 minutes tests time. 
- dl4j: longest set. see below.
- datavec: 5 minutes in total.

But there might be some improvements eventually. I.e. some long running tests might be excluded if there's specific env variable is set.

General idea is: notify engineer about upstream failures as soon as possible. So i doubt we should introduce "special" tests. We might just exclude some long running ones from fast pipeline.

**Comment by raver119** [comment]
p.s. and, obviously, engineer should be notified somehow, since that's background task. Gitter, slack, flock, basecamp, whatever  - just send pm to branch owner once check is finished.

**Comment by saudet** [comment]
As long as it's exposed via Maven profiles with the pom.xml files, it's something we can easily add to the pipeline of the monorepo.

**Comment by raver119** [comment]
Maven profiles are ok, but as for joint pipeline: the whole idea of fast pipeline is to be independent of heavy builds that take 4 hours. 10 minutes per run is the max what we should spend here...

**Comment by AlexDBlack** [comment]
FYI - updated test runtimes here: https://github.com/deeplearning4j/deeplearning4j/issues/5135
Seems like running via ```mvn clean test``` is a lot faster than via IntelliJ, especially for CUDA
