### ISSUE TITLE
ND4J tests + Intellij IDEA

### ISSUE THREAD

**Issue by raver119** [eclipse/deeplearning4j#5098]
Intellij IDEA 2018.x has issues with ND4J tests, and it looks like it's not a bug.

https://github.com/deeplearning4j/nd4j/blob/12d63943d76c5152192d979beed03e39d9b1ab82/nd4j-backends/nd4j-backend-impls/pom.xml#L45
https://github.com/deeplearning4j/nd4j/blob/34fec21757695246b8a18a32812054f95b290cb0/nd4j-backends/nd4j-backend-impls/nd4j-native/pom.xml#L114
https://github.com/deeplearning4j/nd4j/blob/2138328469fc07bad0d5eed95112d73d9c445b72/nd4j-backends/nd4j-backend-impls/nd4j-cuda/pom.xml#L23

These maven properties are parsed, and imported into Intellij IDEA modules properties, causing problems with IDE.

@saudet  Can we reconsider that somehow?

**Comment by saudet** [comment]
Which Maven properties?

**Comment by raver119** [comment]
click the links. they all point to the suspected property

**Comment by saudet** [comment]
testSourceDirectory? We can't do anything about that unless we don't share the tests..

**Comment by raver119** [comment]
Ok, we should start looking for another IDE then. Because in 2018.x after
any reimport you must manually fix Intellij project

**Comment by AlexDBlack** [comment]
@raver119 what does this look like for you when it fails?
It seems like I'm unable to run nd4j tests in intellij anymore, not sure if it's the same issue or not.
Previously we set "use classpath of module" to nd4j-native.
Now I do that and simply get ```Class not found: "org.nd4j.linalg.Nd4jTestsC"Empty test suite.```

**Comment by AlexDBlack** [comment]
OK, seems like this is still super-flaky... but I can now run tests with the following is a workaround:
(a) install Nd4J
(b) import nd4j-tests ONLY into intellij (separate project -> forces ND4J to use maven dependencies)
(c) Select and run clean/validate/compile under Maven Projects -> Lifecycle

Running them directly (i.e., opening more than 1 project) means I get errors related to ND4J initialization (missing native libraries).
Without the clean/validate/compile I get a ton of missing dependencies.

**Comment by raver119** [comment]
It's getting worse guys, now on top of original issue i can't use test resources in Intellij, if nd4j is open as separate project.

We need to get these issues fixed somehow, because it seriously slows down work flow.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/0e66ef031daf88ae6f671208b85b08b5562e4b9b/pom.xml#L538-L551

I think since this is declared in top-level pom.xml, Intellij just can't see it if you open nd4j as separate project.

**Comment by saudet** [comment]
@rajeev3983 That'd be a bug in IntelliJ, but we can do some copy/paste there, and if it works, we can leave it like that. It wouldn't hurt other tools.

**Comment by raver119** [comment]
Ye, there's definitely something goes on in Intellij, they do some refinements... But since we have no other viable IDEs - we should adopt somehow 😄

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/e97090b504acae2ad6d717d58ddce79af212ccab/nd4j/pom.xml#L403-L416

This copypasta seems to work fine, nd4j-tests work again in latest Intellij. Is it acceptable workaround for CI/CD compatibility? @saudet @sshepel

**Comment by raver119** [comment]
We've switched to profiles to address this issue.
