### ISSUE TITLE
NullPointerException when use AutoEncoder

### ISSUE THREAD

**Issue by w4ngzhen** [eclipse/deeplearning4j#5250]
#### Issue Description
- I found it throw a NullPointerExcetion when I create a  AutoEncoder (in org.deeplearning4j.nn.layers.feedforward.autoencoder not in org.deeplearning4j.nn.conf.layers) and use the Instance Methods like "encode" or "activate".  
```
    public static NeuralNetConfiguration autoEncoderConf
            = new NeuralNetConfiguration.Builder()
            .seed(123)
            .iterations(1)
            .weightInit(WeightInit.XAVIER)
            .updater(Updater.ADAGRAD)
            .activation(Activation.RELU)
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
            .learningRate(0.05)
            .regularization(true).l2(1e-4)
            .layer(new OutputLayer.Builder()
                    .lossFunction(LossFunctions.LossFunction.MSE)
                    .nIn(3).nOut(3)
                    .build())
            .build();
    public static void main(String[] args) {
        INDArray someData
        AutoEncoder autoEncoder = new AutoEncoder(autoEncoderConf);
        autoEncoder.init();
        autoEncoder.encode(someData, false); // NullPointerExcetion
        autoEncoder.activate(); // NullPointerException, too
    }
```
- I think it will return a right INDArray object. Do I use this class incorrectly? Can you provide a demo for the org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder? I just want to use it to encode or decoder some data.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j -nn  0.9.1 
* platform information (macOS)

**Comment by agibsonccc** [comment]
Please try the latest versions (1.0.0-alpha or beta) and try again.
