### ISSUE TITLE
ND4S: Instead of using custom -> for ranges, use ones that are already built into Scala

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5258]
_From @Mocuto on October 22, 2016 18:0_

As the title states, currently the documentation shows the following:
`arr(0 -> 3)` in ND4S is equivalent to `arr[0:3]` in Numpy+Python

However, Scala already has its own syntax that is equivalent to `arr[0:3]` in Python, which is `arr(x until y)`
In order to align more with Scala, ND4S should simply have
`arr(0 until 3)` as being equivalent to `arr[0:3]` in Python,

 and removing the `x->y` syntax entirely, as in Scala using the `until` keyword is more intuitive and using `->` is more associated with Maps/Tuples, which makes it confusing.

_Copied from original issue: deeplearning4j/nd4s#95_

**Comment by AlexDBlack** [comment]
_From @javadba on March 3, 2018 19:41_

No let's keep this: the enhanced similarity to numpy is appreciated. The scala syntax is clumsy.

**Comment by Mocuto** [comment]
The Scala syntax is clumsy to who exactly? It's ND4Scala not ND4(Scala Developers who wish Scala was Numpy).

**Comment by alexanderst** [comment]
I agree that binding -> operator to Scala ranges is really clumsy , not intuitive and not flexible (there's no option for either excluding or including upper bound). Not sure what was the reason, but 1 to 3, 1 until 3, etc. looks native for Scala developer.
