### ISSUE TITLE
ND4S: Publish 2.12 artifact to Maven Central

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5259]
_From @ctongfei on June 9, 2017 2:23_

Scala 2.12.2

_Copied from original issue: deeplearning4j/nd4s#108_

**Comment by AlexDBlack** [comment]
_From @saudet on June 9, 2017 3:9_

Actually duplicate of #96: Some dependencies are missing.

**Comment by AlexDBlack** [comment]
_From @letalvoj on November 13, 2017 16:17_

Well it seems that [scalaxy-loops](https://mvnrepository.com/artifact/com.nativelibs4java/scalaxy-loops) is the problem.

It does not seem that they are going to bump it up to 2.12 anytime soon. Has anyone actually measured the performance gain of this particular library? Is rewriting the for-loops such a big deal? Is it used often enough?

The optimization provided by the library is used only twice in the whole project...

**Comment by AlexDBlack** [comment]
_From @saudet on November 14, 2017 9:34_

If you can replace scalaxy-loops with something else, that'd be great. If performance doesn't drop too much, for loops are acceptable, sure.

**Comment by AlexDBlack** [comment]
_From @letalvoj on November 14, 2017 9:38_

I will surely not write a macro to rewrite `for`-loops to `while` yet we can rewrite those two particular loops manually. Would you agree?

**Comment by AlexDBlack** [comment]
_From @saudet on November 14, 2017 9:40_

Yes, that's fine, for loops, while loops, same difference, that's what I meant :)

**Comment by AlexDBlack** [comment]
_From @MartinSeeler on November 14, 2017 9:45_

[non/spire](https://github.com/non/spire) has a macro for loops as well. Not sure if this helps, but it's definitly available for 2.12. Excerpt from the README:

Spire also provides a loop macro called `cfor` whose syntax bears a slight
resemblance to a traditional for-loop from C or Java. This macro expands to a
tail-recursive function, which will inline literal function arguments.

The macro can be nested in itself and compares favorably with other looping
constructs in Scala such as `for` and `while`:

```scala
import spire.syntax.cfor._

// print numbers 1 through 10
cfor(0)(_ < 10, _ + 1) { i =>
  println(i)
}

// naive sorting algorithm
def selectionSort(ns: Array[Int]) {
  val limit = ns.length -1
  cfor(0)(_ < limit, _ + 1) { i =>
    var k = i
    val n = ns(i)
    cfor(i + 1)(_ <= limit, _ + 1) { j =>
      if (ns(j) < ns(k)) k = j
    }
    ns(i) = ns(k)
    ns(k) = n
  }
}
```

**Comment by AlexDBlack** [comment]
_From @letalvoj on November 14, 2017 10:21_

@saudet I'm having some issues with the codebase... I tried to compile it using `sbt compile` and nothing happens ... It says that everything is OK but the target folder does not contain any compiled classes 😦

Am I invoking a wrong task? It's wierd that I do not get any error whatsoever.

**EDIT** sorry, no idea what happened, but closing and reopening intelij / terminal solved the issue 🤦‍♂️

**Comment by AlexDBlack** [comment]
_From @winitzki on November 27, 2017 20:21_

Just a comment - some time ago I have compiled `scalaxy-streams 0.4-SNAPSHOT` with Scala 2.12 with either no or very few code changes necessary (not sure now). It seems to me that `scalaxy` is not supported or developed much any more, and that `scalaxy-streams` is a replacement of `scalaxy-loops`, although I may be mistaken here. Would it be possible to use `scalaxy-streams` instead of `scalaxy-loops`?

**Comment by AlexDBlack** [comment]
_From @saudet on February 28, 2018 7:17_

Please test the https://github.com/deeplearning4j/nd4s/tree/scala-2.12 branch! Thanks

**Comment by raver119** [comment]
Is this issue still relevant?

**Comment by benetis** [comment]
Is 2.12 support coming with 1.0?

**Comment by Joe29** [comment]
bump

**Comment by raver119** [comment]
cc @alexanderst @sshepel
