### ISSUE TITLE
ND4S: remove from the project all ComplexNDArray related stuff

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5261]
_From @cpuheater on September 29, 2017 10:47_

like this class https://github.com/deeplearning4j/nd4s/blob/master/src/test/scala/org/nd4s/ComplexNDArrayTest.scala

_Copied from original issue: deeplearning4j/nd4s#117_

**Comment by alexanderst** [comment]
@AlexDBlack There are no references to this class in current master.

**Comment by raver119** [comment]
That's probably outdated issue.
