### ISSUE TITLE
ND4S: There is a bug in `CollectionLikeNDArray.existsRC`

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5262]
_From @letalvoj on November 14, 2017 12:55_

Check out [CollectionLikeNDArray.scala#L77](https://github.com/deeplearning4j/nd4s/blob/bf2ea7d5f829f0d3a61c11a0d8ba11ccc6e220dd/src/main/scala/org/nd4s/CollectionLikeNDArray.scala#L77). The condition is negated 😉 . I am updating the code in [#108](https://github.com/deeplearning4j/nd4s/issues/108) anyway. Thus I'll write breaking tests and fix it there.

_Copied from original issue: deeplearning4j/nd4s#120_

**Comment by alexanderst** [comment]
@raver119 There's no such method anymore. Looks like can be closed.
