### ISSUE TITLE
Jumpy: Test suite integration for jumpy.

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5277]
_From @akshaysharma096 on April 23, 2018 1:31_

Currently, there is no test suite integration for the package, it will be good to have a structured test suite for running unit tests and code stability.

_Copied from original issue: deeplearning4j/jumpy#19_

**Comment by akshaysharma096** [comment]
@AlexDBlack duly noted I will add the test suite to the code base.

**Comment by akshaysharma096** [comment]
@AlexDBlack I see jumpy repo is now archived, where do I raise the PR for the issue now?

Thanks!

**Comment by akshaysharma096** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/5282

@AlexDBlack I have added basic test suite, but we need to port the existing code to that test suite, I will create a new issue for that and raise PR for the same.
