### ISSUE TITLE
ND4J: inconsistent create methods; can't create rank 1 array

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5360]
One allows rank 1 arrays, the other does not:
https://github.com/deeplearning4j/deeplearning4j/blob/83a8ea4eefbdde4ed5dd7af7f416b5ad44a4b704/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L5408-L5431

I think this should be as simple as removing the check, now that we support rank 1 arrays properly?
Though if not, the behaviour should be consistent.

Aha! Link: https://skymindai.aha.io/features/ND4J-173

**Comment by raver119** [comment]
That's not a bug. That's feature.

New methods do allow vector creation. Old methods - use legacy logic. 
However, if you're ok with breaking backward compatibility with dl4j code - that would be great.

**Comment by AlexDBlack** [comment]
Hm... going forward (long term) it would be better having them aligned. So as much as I hate breaking backward compatibility in general, I think I'd rather fix this sooner (i.e., before next release) rather than later.

That said, I don't recall anywhere in DL4J (well, layers/NNs etc) that rely on the old functionality.

**Comment by raver119** [comment]
Great. Utra-easy fix then.

**Comment by raver119** [comment]
Fixed long ago as i remember.
