### ISSUE TITLE
Word2vec with GloVe does not stop saving

### ISSUE THREAD

**Issue by foggyoon** [eclipse/deeplearning4j#5386]
I`m trying to save Word2vec savefile with GloVe.

JAVA is not terminated.

Here are my source code and logs.

First, Source Code 
[Source Code](https://gist.github.com/foggyoon/b416c5125e75c7ff73a482d363a8f49e)
Second, CPU version log
[CPU version log](https://gist.github.com/foggyoon/d664df02dc23e09260d7aaf5a5f55a23)

Third, GPU version log
[GPU version log](https://gist.github.com/foggyoon/16538c74972dd1c29b65ee3cc66f3c94)

**Comment by raver119** [comment]
Or not. Show threads dump please.

**Comment by foggyoon** [comment]
Threads dump gist!
[https://gist.github.com/foggyoon/36da9e37dcce4813c3bb143a44697cc4](Threads dump)

**Comment by raver119** [comment]
Fixed in my branch, will be merged later.

Thanks for highlighting this bug. One of threads wasn't set daemonic.
