### ISSUE TITLE
Weird JVM Crash on Linux (1.0.0-beta)

### ISSUE THREAD

**Issue by treo** [eclipse/deeplearning4j#5406]
While trying to figure out https://github.com/deeplearning4j/deeplearning4j/issues/5072 I've ran into a very weird JVM Crash on Linux.

In contrast to what I was seeing on Windows, the JVM is crashing here on a JIT Compilation event.

It happens both with OpenJDK 8 and Oracle JDK 8.

Those are the Oracle JDK Error log files:
[hs_err_pid3692.log](https://github.com/deeplearning4j/deeplearning4j/files/2057885/hs_err_pid3692.log)
[replay_pid3692.log](https://github.com/deeplearning4j/deeplearning4j/files/2057886/replay_pid3692.log)

And these are the Open JDK Error log files:
[hs_err_pid31260.log](https://github.com/deeplearning4j/deeplearning4j/files/2057889/hs_err_pid31260.log)
[replay_pid31260.log](https://github.com/deeplearning4j/deeplearning4j/files/2057890/replay_pid31260.log)

Those crashes don't happen every time. Once I had a crash without any error log at all, just the output on STDERR that said "Double free or corruption". 

Warning wild speculation ahead: Maybe it is still related to the original issue, and it just shows itself with a different kind of crash on Linux. Maybe it is something about the Chinese Characters (as the compilation event on which it fails is always for DefaultTokenizer.nextToken).

I've tried to reproduce the problem with ParagraphVectorsInferenceExample, and couldn't do it. So maybe it is related to the combination of PV-DM and CBOW, because the example uses PV-DBOW and SkipGram, while the model from the original issue uses PV-DM/CBOW.

**Comment by raver119** [comment]
Do you have actual code i could run to reproduce it?

**Comment by AlexDBlack** [comment]
Closing due to age of issue (probably obsolete)
