### ISSUE TITLE
BasicHyperparameterOptimization Example needs to be updated

### ISSUE THREAD

**Issue by rahul-raj** [eclipse/deeplearning4j#5446]
Few deprecated usages to be updated:
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/arbiter/BasicHyperparameterOptimizationExample.java

1) TestSetAccuracyScoreFunction -> EvaluationScoreFunction
2) MultipleEpochsIterator -> MultiLayerNetwork.fit() or EarlyStoppingConfiguration<MultiLayerNetwork>

**Comment by minutolc** [comment]
Hello ,

I want to implement the example of BasicHyperparameterOptimization but i have some trouble : 
                          When i use OptimizationConfiguration i have to put an scoreFunction and in the tutorial they create it with ScoreFunction scoreFunction = new EvaluationScoreFunction(Evaluation.Metric.ACCURACY);

The problem is that Evaluation.Metric is Deprecated so i have an error when i use it. They advise to use instead ND4J Evaluation class, which has the same interface but i can't find a way to get a scoreFunction with ND4J.

Can someome help me please ?

**Comment by yptheangel** [comment]
> Hello ,
> 
> I want to implement the example of BasicHyperparameterOptimization but i have some trouble :
> When i use OptimizationConfiguration i have to put an scoreFunction and in the tutorial they create it with ScoreFunction scoreFunction = new EvaluationScoreFunction(Evaluation.Metric.ACCURACY);
> 
> The problem is that Evaluation.Metric is Deprecated so i have an error when i use it. They advise to use instead ND4J Evaluation class, which has the same interface but i can't find a way to get a scoreFunction with ND4J.
> 
> Can someome help me please ?

Although it is deprecated but my arbiter code can still run and display the metrics(Accuracy or F1)

You can refer to this: https://gist.github.com/yptheangel/9baff7a2f74d8d6844e79b58d6cd4ca7
