### ISSUE TITLE
ND4J: maven enforcer needs to run before maven surefire

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5469]
Currently (single the merge of the parent pom cleanup PR): all tests run before the enforcer plugin runs... basically it's just an issue of the order in which they are defined (enforcer plugin needs to be before surefire)

**Comment by saudet** [comment]
@sshepel We'll need to introduce pluginManagement in the parent pom.xml.

**Comment by sshepel** [comment]
@saudet got it
