### ISSUE TITLE
Nd4j.diag() regression

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5482]
_From @emillynge on June 5, 2018 12:7_

#### Issue Description
the diag function was broken in commit that was part of #2641

Please describe your issue, along with:
- expected behavior
 When passing a matrix to diag, a vector is returned
- encountered behavior
 A HUGE matrix is returned

#### Version Information

Please indicate relevant versions, including, if relevant:

* Nd4j 1.0.0-beta

diag function no longer checks if input is a vector or a matrix. Native op is directly called and [n,m] matrices are treated as [nm] vector which produces a [nm, nm] matrix.

The error was introduced in https://github.com/deeplearning4j/nd4j/commit/206199b295c1adfbd72388abdd0405f6f7c9b5c8#diff-329bd29dd155454c7a45684179eacdffL2824

NB. the old implementation does not seem correct for matrices if `k != 0`

_Copied from original issue: deeplearning4j/nd4j#2919_

Aha! Link: https://skymindai.aha.io/features/ND4J-171

**Comment by raver119** [comment]
Diag works ok for all input ranks now.

**Comment by AlexDBlack** [comment]
Our Nd4j.diag method (claims to, and used to) do both: i.e., like diag_part for matrix, or like set_diag for vector input.
There's also an overload with k argiment which isn't used currently.
https://github.com/deeplearning4j/deeplearning4j/blob/c44ce4c209c1dc4c5ac263e7d967aad073b1ce19/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L2557-L2588

**Comment by shugeo** [comment]
Current implementation of diag op put matrix given as giagonal elements of result.
