### ISSUE TITLE
Libnd4j/DL4J: Need new dropout ops with backprop implementation

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5485]
(Inverted) dropout forward pass:
x = input
z = output
p = probability of retaining an activation

Forward pass:
```
z = 0 	with probability (1-p)
    x/p with probability p
```

Backprop:
```
dL/dx = dL/dz * dz/dx
      = dL/dx * (0 if dropped, or 1/p if retrained)
```

Now, to implement the backprop, we need to record the dropout mask from forward pass.
This shoud be a binary vector - single bit per input value (0 = dropped, 1 = retained). There's no need to record this as FP32 for example.

Forward op:
input: 1
tArgs: 1 (dropout retrain probability p)
outputs: 2, both required
    - output array: same shape as input
    - mask array: binary vector - same number of bits as input.length() (rounded up, obviously)

Backward op:
inputs: 2
    - Gradient array (dL/dOut)
    - mask array (binary vector)

Of course, this 'binary vector' complicates things a bit for the calculate output shapes API, and DynamicCustomOp API...

---
Alpha dropout:

```
z = a(xd + a'(1-d))+b)
```
where ```a```, ```a'``` and ```b``` are constants.
```d``` is dropout mask (0 or 1, with probability p)

Backprop:
```
dL/dx = dL/dz * dz/dx
          = dL/dz * (a if x is retained, 0 otherwise)
```

Forward and backward ops are essentially identical to standard (inverted) dropout op, but forward has extra tArgs (a, a', b)

---

Spatial dropout: this is just standard dropout op, but with broadcast dropout mask.
It could probably be implemented as a special case of the standard dropout op (i.e., if iArgs are specified, assume spatial dropout, or otherwise assume standard).
Spatial dropout mask is equal to ``prod_i(input.size(dim[i])```

---

There's not any performance benefit to implementing Gaussian dropout as a native op, so let's keep that as java only.
For gaussian noise, dL/dx = dL/dz, so no need for native op either.

Aha! Link: https://skymindai.aha.io/features/DL4J-96

**Comment by shugeo** [comment]
If you have a test case for it, please add here.

**Comment by AlexDBlack** [comment]
@shugeo Probably the more critical issue is this one: https://github.com/deeplearning4j/deeplearning4j/issues/5650

We've got a reasonable work-around for DL4J for now. But we can't implement dropout into samediff until that issue is resolved. The solution for that issue (I'm not sure exactly what we should do there yet) will very likely impact the design (and of course testing) of these ops (including backprop).

**Comment by shugeo** [comment]
Expected with PR 5857.

**Comment by raver119** [comment]
@AlexDBlack this issue should've been resolved long ago, can you please confirm/decline this?

**Comment by raver119** [comment]
Implemented quite a while ago.
