### ISSUE TITLE
Libnd4j: implement GRU backprop op

### ISSUE THREAD

**Issue by maxpumperla** [eclipse/deeplearning4j#5504]
We could just do that in DL4J, but I think going forward it's worthwhile to move all the heavy lifting a level down. Our LSTM implementation, for instance, is a little too cluttered for my taste. I'd rather not repeat this with GRU.

**Comment by maxpumperla** [comment]
yeah, I realise it's a lot to ask. I'll see if I can find a reference 👍

**Comment by raver119** [comment]
@shyrma can we close this issue now?

**Comment by raver119** [comment]
Implemented, will be merged later today.
