### ISSUE TITLE
Glove randomly produces NaN weights or nonsensical similarities

### ISSUE THREAD

**Issue by daanvdn** [eclipse/deeplearning4j#5696]
**Issue Description**

In version 1.0.0-beta, there is (still) a bug in `org.deeplearning4j.models.glove.Glove` that causes it to produce a `org.deeplearning4j.models.embeddings.WeightLookupTable` with **NaN** as weights. This can be observed when running `org.deeplearning4j.examples.nlp.glove.GloVeExample` or any other code that uses dl4j's Glove implementation. Here's some of the logging from the `GloVeExample` that demonstrates this behaviour:

```
09:44:12.864 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [47194] pairs, Error was [3.370708701478753E7]
09:44:14.409 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [94388] pairs, Error was [NaN]
09:44:16.074 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [141582] pairs, Error was[NaN]
09:44:17.680 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [188776] pairs, Error was[NaN]
09:44:19.287 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [235970] pairs, Error was[NaN]
09:44:21.388 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [283164] pairs, Error was[NaN]
09:44:22.996 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [330358] pairs, Error was[NaN]
09:44:24.757 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [377552] pairs, Error was[NaN]
09:44:26.548 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [424746] pairs, Error was[NaN]
09:44:28.314 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [471940] pairs, Error was[NaN]
09:44:30.073 [VectorCalculationsThread 3] INFO org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe - Processed [519134] pairs, Error was[NaN]
```

What is important is that NaN values are *not always* produced. Sometimes real numbers are produced, sometimes it's NaN. 

Another problem is that, even if real numbers are produced, the word similarities are off the mark. E.g.

`o.d.e.n.g.GloVeExample - Day/night similarity: 0.06969143450260162`
`o.d.e.n.g.GloVeExample - Nearest words to 'day': [next, yesterday, a, season, place, one, who, program, best, house]`

There are already several tickets relating to this issue, but they have either been closed or pertain to older versions of dl4j cf: https://github.com/deeplearning4j/deeplearning4j/issues/1622, https://github.com/deeplearning4j/deeplearning4j/issues/3462

Therefore as requested by @RobAltena I'm creating a new ticket. I've also created a mini-project with a unit-test that runs the `GloveExample` multiple times and fails if any of the weights are NaN. As can be seen, the test fails after a several iterations (or sometimes even the first). If the test doesn't fail upon the first time you run it, please run it several times over. Eventually it will fail.

Please note that changing the `org.nd4j.graph.DataType` does in no way remedy this problem.

The code can be found in these gists: [GloveRunner](https://gist.github.com/daanvdn/0300c551065fe3fb70b5a1b559069309), [GloveRunnerTest](https://gist.github.com/daanvdn/6da0db45bd00c5ebaaacd107d3c3ec5b), [pom.xml](https://gist.github.com/daanvdn/08a01e862c5a3678c0a3d90859184b59)
I've also added it as a github project here: https://github.com/daanvdn/glove-nan-bug

**Version Information**

deeplearning4j version 1.0.0-beta

**Comment by RobAltena** [comment]
Thank you! I have send you a PR https://github.com/daanvdn/glove-nan-bug/pull/1 to clean up the code a little. Should make it easier to move your junit test into deeplearning4j.

**Comment by daanvdn** [comment]
your're welcome @RobAltena. I just approved the PR and merged. Do you need any other input from me?

**Comment by RobAltena** [comment]
Lets wait from some hints/tips from the core devs.

**Comment by daanvdn** [comment]
hi @RobAltena is there any news about this issue? Is there any one I can reach out to?

**Comment by raver119** [comment]
It's enqueued, but it's considered low priority.

**Comment by treo** [comment]
Closing due to GloVe feature removal. See https://github.com/eclipse/deeplearning4j/issues/7855#issuecomment-624616313
