### ISSUE TITLE
Executing Op with operands of same data type should be possible regardless of global data type

### ISSUE THREAD

**Issue by emillynge** [eclipse/deeplearning4j#5726]
I tried to ask the following question on gitter with no reply:
> Can anyone tell me why we use a global Nd4j.dataType() for input validation when executing op, rather than just using the datatype of the first operand?
> Multiplying a double array with a float array should of course raise an exception. But I see no reason to prevent the user in multiplying 2 float arrays just because the default datatype is set to double

So I thought I might instead file an issue.

**Expected behavior:**

1. To ensure new arrays use float64, `Nd4j.dataType() == DataBuffer.DataType.DOUBLE`
2. Create 2 INDArrays (A, and B ) backed by FloatBuffers because I do not need a lot of precision.
3. `A.mmul(B)` can be called and returns another INDArray backed by a FloatBuffer

**Found behavior:**
3.  `A.mmul(B)` throws exception because `A.data().dataType() != Nd4j.dataType()`

I do not think the above is an unreasonable use case, and constant switching of the global DataType does not seem appealing. Now I know that Nd4j is not threadsafe, but it is especialy problematic if Nd4j is used in a multithreaded application.

Also, I fail to understand why it is necessary to enforce that all ops has to use the same datatype as the default/global. I can see the argument for simplicity/protecting users from themselves. But other libraries such as numpy has no problems letting the user work with different datatypes at the same time, as long as they are not mixed in any operations.

Can the maintainers enlighten me as to why this global default is enforced in this way, and whether there could exist some way of getting Nd4j to a point where it is not longer needed?

Aha! Link: https://skymindai.aha.io/features/ND4J-168

**Comment by raver119** [comment]
It depends on operation. This limitation is mostly due to extraArgs arguments which is used by big number of legacy operations.

**Comment by raver119** [comment]
And yes, it's planned to get rid of that thing. We're moving in that direction right now, we're going to allow cross-dtype ops using special extras field in shapeInfo

**Comment by emillynge** [comment]
Nice :smiley: 

So if this is a feature i **really** want, and have time to help implement. where could I start?

**Comment by raver119** [comment]
You'll start with changing signatures of everything in libnd4j: loops, ops, etc.
Then you'll add additional types to underlying math functions.
After that you'll ensure that on libnd4j and ND4j side you'll set proper extra bits for dtypes.
After that you get rid of templates for everything but math functions, probably.
After that you'll change legacy extraArgs to be current type.
After that you'll get rid of separate dtype-related execution methods in favor of vague type methods.

**Comment by raver119** [comment]
That's approximate plan for it ^^^

**Comment by emillynge** [comment]
I see.. that is a very comprehensive piece of work you laid out.

But would it not be possible to start out by changing:
```
# NativeOpExecutioner.java
    private void exec(TransformOp op) {
        long st = 0;

        validateDataType(Nd4j.dataType(), op);
.....
```

to 
```
# NativeOpExecutioner.java
    private void exec(TransformOp op) {
        long st = 0;

        validateDataType(op.x().data().dataType(), op);
```
?

I have difficulty seeing what problems this would cause.

**Comment by raver119** [comment]
Okay, imagine that happened. Let's observe what changed after that, i.e. by studying pairwise transform:
- still expects 3 operands to have same (!) type T
- still expects extraArgs buffer to have the same type T

So, if you'll change it in that particular place (execTransform) - that's fine. But it gives you nothing in the rest of code base.

**Comment by raver119** [comment]
P.s. and no, actual major dtype change won't be THAT hard. Just boring routine work. Hopefully we'll make it happen after this release.

**Comment by raver119** [comment]
p.s. i personally can't wait for IndexAccumulations returning longs instead of T

**Comment by raver119** [comment]
Implemented long ago.
