### ISSUE TITLE
ND4J/Libnd4j: Add random integer distribution

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5776]
I don't believe we have this already.
Not a high priority, but it would be good to be able to generate random integers in range of [0,X) - i.e., X not included.
Think the NDArray version of java's ```Random.nextInt(int bound)```.

In the mean time, we can approximate this with floor(uniformRandom * bound).

Aha! Link: https://skymindai.aha.io/features/ND4J-46

**Comment by shugeo** [comment]
there is rng.nextInt() routine.

**Comment by raver119** [comment]
Now random uniform op allows int output
