### ISSUE TITLE
Error Starting training

### ISSUE THREAD

**Issue by vicdaran** [eclipse/deeplearning4j#5881]
Hello,
I'm trying to run a workout but I get the following error.

java.lang.NoSuchMethodError: org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(Lorg/nd4j/linalg/dataset/api/iterator/DataSetIterator;IZ)V

He compiled the latest version with maven the project from git

Any ideas?

Thank you

**Comment by viktordart** [comment]
I downloaded the entire git project. Compile first in nd4j that there is in git and then deepleaning4j. Am I wrong in something? Should not I use the nd4j in the git of deepleaning4j?

Thank you

**Comment by AlexDBlack** [comment]
@viktordart Yes, you are doing something wrong: you shouldn't be compiling anything from source (other than your own project).
Use DL4J and ND4J as dependencies using a dependency manage like maven.
https://deeplearning4j.org/quickstart
