### ISSUE TITLE
Convolution1DLayer=>BatchNormalization=>GlobalPoolingLayer throws `UnsupportedOperationException: Global max pooling cannot be applied to feed-forward input type. Got input type = InputTypeFeedForward(128)`

### ISSUE THREAD

**Issue by reuschling** [eclipse/deeplearning4j#6093]
[#6033](https://github.com/deeplearning4j/deeplearning4j/pull/6033) enables to use Convolution1DLayer with BatchNormalization layers, thanks a lot!
I try to implement a 1D CNN classification for timeseries from this [paper](https://arxiv.org/pdf/1611.06455.pdf) (the FCN, here is the according dl4j code [Gist](https://gist.github.com/reuschling/ba771bb80b609b10cc3c328bdc489086)).
The layers are 3 times `CNN1D=>BatchNorm=>Activation` with a succeeding `GlobalPoolingLayer` (not sure the activation layers are needed, you've written this in [issue #4093](https://github.com/deeplearning4j/deeplearning4j/issues/4093).
The `BatchNormalization` gives no exception now, but the `GlobalPoolingLayer` says

`UnsupportedOperationException: Global max pooling cannot be applied to feed-forward input type. Got input type = InputTypeFeedForward(128)`
I commented this also at [issue #2418](https://github.com/deeplearning4j/deeplearning4j/issues/2418)), just for information.

Aha! Link: https://skymindai.aha.io/features/DL4J-79

**Comment by AlexDBlack** [comment]
Possible quick workaround: you may be able to simply add a FeedForwardToRnnPreProcessor before the global pooling layer.
Beyond that, I'll need to took at this in the debugger...

**Comment by reuschling** [comment]
The code is running without Exception with the PreProcessor :+1:
