### ISSUE TITLE
DL4J GPU Backend possible memory leak when doing multiple train on same application

### ISSUE THREAD

**Issue by scauglog** [eclipse/deeplearning4j#6100]
When you train multiple model during the same run of the application (when you do a grid search), the memory on GPU continually increase.
I made [an application to reproduce the problem](https://github.com/scauglog/dl4j_tuning.git). I train on AWS p2.8xlarge with manual installation of cuda.

**Comment by agibsonccc** [comment]
Could you tell us a bit more? It's kind of hard to just start running this without knowing where to start. How did you profile it? Was anything attempted as far as basic benchmarking is concerned?

**Comment by raver119** [comment]
In all but 1 cases i've heard of in years, it was just references kept somewhere by user. 
In 1 case there was memory fragmentation issue.

Can you please point me to actual code in your repository? The place where you create threads and where you query for results of your models.

**Comment by raver119** [comment]
What hsould i do to execute your app locally? Can you provide me with step-by-step instructions please?

**Comment by scauglog** [comment]
- You should have apache spark 2.2.1 and java 8 
- export JAVA_HOME  to java8 folder
- export SPARK_HOME to spark folder
- create a folder named data with subfolder train and test.
- copy data/data.csv in those two folder (train and test)
- compile `mvn clean package -Djavacpp.platform=linux-x86_64`
- launch:
```
SPARK_SUBMIT=$SPARK_HOME/bin/spark-submit
SPARK_OPTIONS="--master local --deploy-mode client --driver-memory 20G --num-executors 3 --executor-memory 10g --executor-cores 1"
$SPARK_SUBMIT $SPARK_OPTIONS --conf "spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=60G -Dorg.bytedeco.javacpp.maxphysicalbytes=60G -XX:+UseG1GC" --name "ClicksAndCostPredictions" \
   --class aperture.tuning.predictions.tuning.TuningMain \
   --conf "spark.sql.shuffle.partitions=24" \
   tuning-1.0.0-shaded.jar \
   --input-path data  \
   --output-dir-path tuning_result \
   --number-of-epochs 10 &> tuning.log &
```
if you don't have more than 50G of ram on you may want to reduce --driver-memory and --executor-memory

**Comment by raver119** [comment]
Is there any way to get rid of spark part? Debugging anything in Spark environment isn't trivial usually

**Comment by scauglog** [comment]
spark just read the CSV file so you can plug any csv reader. I will update the code

**Comment by raver119** [comment]
That would be awesome. Please drop me a line once it happened

**Comment by scauglog** [comment]
I removed all spark. I keep hadoop dependency for writing on filesystem but it shouldn't bother you
