### ISSUE TITLE
Lambda Layer..

### ISSUE THREAD

**Issue by james-jjj** [eclipse/deeplearning4j#6107]
Hi  @maxpumperla 

I see the this commit.

https://github.com/deeplearning4j/deeplearning4j/commit/c451be9c3b48cbc5c12269fb83657785fa06fd69#diff-5143a696160546bfa067b979fbde54ce

Can I use it?

Thanks.

**Comment by raver119** [comment]
Sorry, what exactly you're asking about?

You can use anything that's available in our repository. In case of new features - you'll probably be using snapshots, but still everything should be usable.

**Comment by james-jjj** [comment]
@raver119 @AlexDBlack 
Thanks a lot !
