### ISSUE TITLE
Maven: Not catching java 8+ code in java 7 module

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6143]
These imports are Java 8:
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/nd4j/nd4j-common/src/main/java/org/nd4j/tools/BTools.java#L21-L22

Yet the language level for the module is set to java 7:
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/nd4j/nd4j-common/pom.xml#L30-L31

Clearly, Maven (and, Intellij - separate issue) is not enforcing this. In general, we should ensure that if we declare a module as Java X our code (and dependencies) for that module are actually java x compatible.

**Comment by raver119** [comment]
Worth a note: this issue wasn't noticed before due to intellij weird behavior. Once we "fix" language level somewhere in project (first candidate is nd4j-tests) - level gets silently applied to the whole project. So this stuff became invisible for Intellij as well.

**Comment by saudet** [comment]
As I've mentioned in passing before (https://github.com/deeplearning4j/deeplearning4j/issues/5599#issuecomment-402373070) this is actually a DevOps issue. We need to build modules that are supposed to be Java SE 7 with JDK 7... Not sure that it's actually possible to build with JDK 7 and test with JDK 8, so we might need to "port" the tests to Java SE 7 as well before.

**Comment by AlexDBlack** [comment]
> We need to build modules that are supposed to be Java SE 7 with JDK 7

That would certainly guarantee that we don't have any java 8+ code slip in. :)
I'd be surprised if there wasn't some other solution though, this is a common issue with java development...

**Comment by saudet** [comment]
I'm not sure there would be a reason to have another solution. If you're not testing your code against JDK 7, how could you know that it actually works with JDK 7?

**Comment by raver119** [comment]
Hm, but our codebase is a mix of j7 and j8. Anything aeron-related is j8 :(
So, part of tests (for these modules) will require j8 as well

**Comment by saudet** [comment]
@raver119 Yeah, exactly, good luck @sshepel :)
