### ISSUE TITLE
SameDiff does't calculate shape

### ISSUE THREAD

**Issue by GlassyWing** [eclipse/deeplearning4j#6148]
like this,  the shape should be calculated in principle ，while that is null in fact.
```
int nLabel = 2;
SameDiff sd = SameDiff.create();

SDVariable a = sd.randomUniform(-1, 1, nLabel);
SDVariable b = sd.randomUniform(-1, 1, nLabel);

SDVariable x1 = sd.stack(0, b, a);

System.out.println(Arrays.toString(x1.getShape())); // null
```

Aha! Link: https://skymindai.aha.io/features/ND4J-162

**Comment by GlassyWing** [comment]
@raver119 so, i have to add "sd.exec()" to get the shape.
like this:
```
sd.exec();
long s_len = xs_i.getShape()[0];
```
But I don't know whether it is an effective way.

**Comment by agibsonccc** [comment]
@farizrahman4u if I remember you were working on this a bit?

**Comment by raver119** [comment]
@GlassyWing It's not effective, and we're going to provide proper support for this. But as temporary workaround - that works. Once you execute graph - everything gets resolved.
