### ISSUE TITLE
code=4(cudaErrorLaunchFailure) "result" on Windows Server 2016 / NVIDIA Titan V

### ISSUE THREAD

**Issue by mtothak** [eclipse/deeplearning4j#6219]
Hi!

I opened this issue as I still have have problems running on a cuda backend
(might be related to https://github.com/deeplearning4j/deeplearning4j/issues/5708) :

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

[INFO ] 2018-08-20 16:54:26.465 [main] Nd4jBackend - Loaded [JCublasBackend] backend
[INFO ] 2018-08-20 16:54:31.794 [main] NativeOpsHolder - Number of threads used for NativeOps: 32
[INFO ] 2018-08-20 16:54:32.606 [main] Nd4jBlas - Number of threads used for BLAS: 0
[INFO ] 2018-08-20 16:54:32.622 [main] DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows Server 2016]
[INFO ] 2018-08-20 16:54:32.622 [main] DefaultOpExecutioner - Cores: [12]; Memory: [21,3GB];
[INFO ] 2018-08-20 16:54:32.622 [main] DefaultOpExecutioner - Blas vendor: [CUBLAS]
[INFO ] 2018-08-20 16:54:32.622 [main] CudaExecutioner - Device Name: [TITAN V]; CC: [7.0]; Total/free memory: [12884901888]
[INFO ] 2018-08-20 16:54:32.872 [main] MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]

Error message:
https://gist.github.com/mtothak/ffdf2cf429cc9eef0e9a17a43213a0fb

Files:
pom.xml
https://gist.github.com/mtothak/7176e67a69e22f07aca3e8226770b3ea

Iterator
https://gist.github.com/mtothak/75998b02170f72e0f4a37c9dc6ccd35f

BILSTMClassifier
https://gist.github.com/mtothak/b0c1a77335c73f8e93a182763a20ea94

Runner
https://gist.github.com/mtothak/e953fb09b8c77ad11fd6c5a004d971e1

DummyData
https://gist.github.com/mtothak/e2739d537028e5cdfd52c8bb0637b33e

It runs ok with (1.0.0-SNAPSHOT or 1.0.0-beta2):
<nd4j.backend>nd4j-native-platform</nd4j.backend>

but with (1.0.0-SNAPSHOT or 1.0.0-beta2):
<nd4j.backend>nd4j-cuda-9.0-platform</nd4j.backend>

I get the error explained above...
Thank you for you help!

lg Markus

**Comment by mtothak** [comment]
Hi!

I investigated some network configurations and it seems that the hidden layer inputs and outputs have to be a multiple of 8. At least with such a configuration it worked in my case...

lg Markus

**Comment by raver119** [comment]
I'd propose to update to CUDA 9.2 in this case. That might be the issue.
