### ISSUE TITLE
Support to Scala 2.12

### ISSUE THREAD

**Issue by napgab** [eclipse/deeplearning4j#6269]
Would be great have a version of ScalNet already compiled for scala 2.12

**Comment by Charele** [comment]
I think it's not important,
the newest Spark only support Scala2.11, not 2.12 yet

**Comment by napgab** [comment]
You're right, but there is also who use DL4J with scala without spark, and i think that this project should be compatible with spark, but should not depends on it.

Scala 2.11 is not supported anymore, no more release are planned for 2.11.x.
Also Scala 2.12 is near the end of its roadmap, for this version are planned only eventually bug fixes.
https://github.com/scala/scala/milestones

It's time to upgrade! :)

**Comment by Charele** [comment]
Hi,I know ScalNet don't depends Spark.
I mean, the "most great Scala product" Spark is use Scala2.11,
So we can continue to use 2.11.
For example, Oracle release Jdk10 now, but most coder(program) use Jdk8,Jdk7...

**Comment by maxpumperla** [comment]
sure, I think we could add 2.12 to https://github.com/deeplearning4j/deeplearning4j/blob/master/change-scala-versions.sh and build scalnet for 2.12 as well here https://github.com/deeplearning4j/deeplearning4j/blob/master/scalnet/buildmultiplescalaversions.sh, but still leave 2.11 as default.

**Comment by kamilkloch** [comment]
Support for Scala 2.12 would be great news!

**Comment by kamilkloch** [comment]
Any chances for the 2.12 release? Spark now supports 2.12, meanwhile Scala 2.13 is around the corner...

**Comment by weihsiu** [comment]
please support scala 2.12/2.13.  this has been a blocker for my organization to adapt scalnet and i really want them to try this great library...

**Comment by AlexDBlack** [comment]
Looks like Spark how has Scala 2.12 support (as of 2.4.0) - so this may be worth revisiting.
https://search.maven.org/artifact/org.apache.spark/spark-core_2.12/2.4.0/jar

However, the UI is still a problem here for us - we'd need to upgrade Play (which means dropping Scala 2.10 support for the UI) or try to work around supporting multiple versions of Play (Play does have some API changes in future versions, so it's not as simple as just upgrading the Play version).

**Comment by saudet** [comment]
@chrisvnicholson should have some stats for that from Maven Central...

**Comment by AlexDBlack** [comment]
Usage stats aside, we'll likely continue to support Scala 2.10 as long as we have customers with Spark clusters running it. For us, Scala 2.10 isn't a major maintenance issue as we have very little in the way of Scala code (other than ND4S obviously) - it's just Scala dependencies like Spark and Play for us.

**Comment by napgab** [comment]
UI dependencies aside, i think that starting to provide a first release with support to scala 2.12 is a great first step.
