### ISSUE TITLE
ND4J: Switch fully to 0d/1d shape semantics

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6301]
There's a number of places where we still use the old "rank 2 minimum" semantics:
* Nd4j.create(int[]) and similar methods
* Nd4j.getRow(int) -> [1,X]

We should do a full pass on this, and switch all uses, all at once. Though there would be some switching cost for users, doing it all at once would be better than doing one piece at a time, or maintaining the current state of "some 2d, some 0d/1d" for different methods/ops.

**Comment by stolsvik** [comment]
(Random drive-by comment: You should also consider dropping the "I" on interfaces. This is Java - the interface is called Whatever, and the default impl is called WhateverImpl or DefaultWhatever or CudaWhatever or somesuch. (I understand that it would not be entirely correct to rename INDArray to Tensor, as a tensor has some concept of "transformational functionality" embedded in its concept? - but that would have been nice, though))

**Comment by AlexDBlack** [comment]
@stolsvik If we were designing things from scratch - INDArray would probably just be called NDArray.
Is it worth the effort to change that at this point? Probably not - though if we do change it, the sooner the better.

If we *were* to change it - we could do ```interface NDArray extends INDArray``` so that code like ```INDArray x = <method that now returns NDArray>``` still works. Then remove INDArray later.
