### ISSUE TITLE
ND4S - tuples mapping

### ISSUE THREAD

**Issue by zorba128** [eclipse/deeplearning4j#6317]
I was wondering why ND4S doesn't have mapping between org.nd4j.linalg.primitives.Pair and Triple and scala tuples. Something like
```
  implicit class PairOP[T, U](a: org.nd4j.linalg.primitives.Pair[T, U]) {
    def asScala: (T, U) = (a.getFirst, a.getSecond)
  }

  implicit class TripleOP[T, U, V](a: org.nd4j.linalg.primitives.Triple[T, U, V]) {
    def asScala: (T, U, V) = (a.getFirst, a.getSecond, a.getThird)
  }

  implicit class Tuple2OP[T, U](a: (T, U)) {
    def asND4J: org.nd4j.linalg.primitives.Pair[T, U] = new org.nd4j.linalg.primitives.Pair(a._1, a._2)
  }

  implicit class Tuple3OP[T, U, V](a: (T, U, V)) {
    def asND4J: org.nd4j.linalg.primitives.Triple[T, U, V] = new org.nd4j.linalg.primitives.Triple(a._1, a._2, a._3)
  }
```
Any reason for that? # #

**Comment by Charele** [comment]
good idea!

By the way, I wonder what's the usefulness of ND4S?
In fact, I can write/run my DL4J program by Scala, without ND4S, and without ScalNet.

  val features = Nd4j.valueArrayOf(Array(100, 3), 1.5)
  val labels = Nd4j.valueArrayOf(Array(10, 1), 10)
  
  val ds = new DataSet(features, labels)
 
  val conf = new NeuralNetConfiguration.Builder()
    .updater(new Sgd(0.5))
    .list()
    .layer(0, new DenseLayer.Builder()
      .nIn(inputOfLayer0)
      .nOut(inputOfLayer1)
      .activation(Activation.IDENTITY)
      .weightInit(WeightInit.IDENTITY)
      .hasBias(false)
      .build())

**Comment by saudet** [comment]
@zorba128 No reason, just waiting for contributions :)

@Charele They are there to provide more idiomatic Scala APIs, but they obviously need much work...

**Comment by zorba128** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6323

**Comment by raver119** [comment]
Implemented quite some time ago.
