### ISSUE TITLE
GraphServer + MKL-DNN

### ISSUE THREAD

**Issue by raver119** [eclipse/deeplearning4j#6337]
Since @saudet works on MKL-DNN libnd4j intergration, we should expose it to GraphServer as well. 

p.s. CPUID should be used to disable it on non-Intel CPUs i guess?

**Comment by saudet** [comment]
MKL-DNN is an open source C++ library, so it probably works fine on AMD CPUs as well, but we need a global setting somewhere to let users disable it of course.

**Comment by raver119** [comment]
Implemented and merged
