### ISSUE TITLE
PRELU OP: wrong shape of alpha array, expected is [1, 1, 198], but got [1, 1, 10] instead !

### ISSUE THREAD

**Issue by xiptos** [eclipse/deeplearning4j#6339]
Hi!
I'm getting the following exception when inputing dynamic shape images to a CNN with PReLU activation layer:
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 2
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1.8GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
[main] INFO org.deeplearning4j.nn.graph.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]

==========================================================================================================================================================================================================================================================
VertexName (VertexType)                 nIn,nOut  TotalParams ParamsShape                             Vertex Inputs                 
==========================================================================================================================================================================================================================================================
input_3 (InputVertex)                   -,-       -           -                                       -                             
conv1 (ConvolutionLayer)                3,10      280         W:{10,3,3,3}, b:{1,10}                  [input_3]                     
PReLU1 (PReLU)                          -,-       10          W:{1,1,10}                              [conv1]                       
max_pooling2d_6 (SubsamplingLayer)      -,-       0           -                                       [PReLU1]                      
conv2 (ConvolutionLayer)                10,16     1456        W:{16,10,3,3}, b:{1,16}                 [max_pooling2d_6]             
PReLU2 (PReLU)                          -,-       3           W:{1,1,3}                               [conv2]                       
conv3 (ConvolutionLayer)                16,32     4640        W:{32,16,3,3}, b:{1,32}                 [PReLU2]                      
PReLU3 (PReLU)                          -,-       1           W:{1,1,1}                               [conv3]                       
conv4-1 (ConvolutionLayer)              32,2      66          W:{2,32,1,1}, b:{1,2}                   [PReLU3]                      
conv4-2 (ConvolutionLayer)              32,4      132         W:{4,32,1,1}, b:{1,4}                   [PReLU3]                      
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            Total Parameters:  6588
        Trainable Parameters:  6588
           Frozen Parameters:  0
==========================================================================================================================================================================================================================================================

12x12: Rank: 4,Offset: 0
 Order: c Shape: [1,3,12,12],  stride: [432,144,12,1]
12x12: Rank: 4,Offset: 0
 Order: c Shape: [1,2,1,1],  stride: [1,1,1,1]
100x200: Rank: 4,Offset: 0
 Order: c Shape: [1,3,100,200],  stride: [60000,20000,200,1]
Error at [/Users/jenkins/jenkins/workspace/deeplearning4j-master-macosx-x86_64-cpu/libnd4j/include/ops/declarable/generic/activations/prelu.cpp:64:0]:
PRELU OP: wrong shape of alpha array, expected is [1, 1, 198], but got [1, 1, 10] instead !
Exception in thread "main" java.lang.RuntimeException: Op validation failed
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1714)
	at org.nd4j.linalg.activations.impl.ActivationPReLU.getActivation(ActivationPReLU.java:61)
	at org.deeplearning4j.nn.layers.feedforward.PReLU.activate(PReLU.java:75)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:110)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2307)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1718)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1677)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1607)
	at pt.ipb.face.BugReport.main(BugReport.java:25)

The source code is in attach, with the model used.
I'm using 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

on macOS 10.13.6

[BugReport.java.zip](https://github.com/deeplearning4j/deeplearning4j/files/2343228/BugReport.java.zip)
[12net.zip](https://github.com/deeplearning4j/deeplearning4j/files/2343229/12net.zip)

**Comment by maxpumperla** [comment]
@xiptos thanks for reporting, I'll take a look asap.

**Comment by agibsonccc** [comment]
Fixed.
