### ISSUE TITLE
Libnd4j/ND4J: Add native updater ops

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6394]
Basically: make native versions of these:
https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/learning

Essentially, we should be able to fuse a lot of these ops.
For example: AMSGrad has 12 separate element-wise ops... The performance limitation here is likely memory access: i.e., in most cases, each op execution won't get any sort of benefit from data still being in cache.

https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/learning/AMSGradUpdater.java#L79-L101

**Comment by raver119** [comment]
Implemented and merged
