### ISSUE TITLE
Small question of CudaZeroHandler

### ISSUE THREAD

**Issue by Charele** [eclipse/deeplearning4j#6417]
See the alloc() method of CudaZeroHandler(MemoryHandler implement when GPU):

if (zeroUseCounter.get() + reqMemory >= configuration.getMaximumZeroAllocation()) {
   if (reqMemory > configuration.getMaximumZeroAllocation()) {
      throw new IllegalStateException(
         "You can't allocate more memory, then allowed with configured value: ["
            + configuration.getMaximumZeroAllocation() + "]");
    }

   while (zeroUseCounter.get() + reqMemory >= configuration.getMaximumZeroAllocation()) {
      try {
         log.warn("No available [HOST] memory, sleeping for a while...");
         log.debug("Currently used: [" + zeroUseCounter.get() + "], allocated objects: ["
                                            + zeroAllocations.get(0) + "]");

          Nd4j.getMemoryManager().invokeGc();
          Thread.sleep(1000);
       } catch (Exception e) {
          throw new RuntimeException(e);
       }
   }
}

For desc simply, let's set
A: zeroUseCounter.get()
B: reqMemory
C: configuration.getMaximumZeroAllocation()
if the first "if" condition match, so go into.
In most case, if we request a big memory, B > C, the second "if" will match, we get a exception...

Almost we will not meet,
but let's assume a special case, the second "if" don't match, that "while" match,
we will go into the while loop, execute GC, and wait 1s.

My question is, the "while" condition result will never change,
I think part A is a counter, it only increase or keep,
part B,part C are both fixed here, so the while(...) always is true,
so we loop here forever???

Aha! Link: https://skymindai.aha.io/features/ND4J-159

**Comment by raver119** [comment]
Yes, in hope that GC will release something unused we'll be waiting until memory is available. That mostly targets concurrent environment, since host memory isn't usually a problem for systems with 1-4 GPUs.

Plus, keep in mind: workspaces model doesn't involve CudaZeroHandler at all.

**Comment by Charele** [comment]
@raver119 Okay, I understand.
MemoryWorkspace is our friend now:-)
Thank you!
