### ISSUE TITLE
Memory leak when a ComputationGraph goes out of scope?

### ISSUE THREAD

**Issue by DrChainsaw** [eclipse/deeplearning4j#6432]
I'm using the TransferLearning API to do weight pruning (by replacing a ComputationGraph with a smaller one and transferring the parameters). Problem is that despite each new graph being smaller than the previous, the memory consumption of the program keeps increasing every time I do this. Old graphs go out of scope so I would expect the memory to be freed at some point in time, but this does not seem to happen.

I'm using CUDA 9.2 on windows 10 and beta2. Card is a GTX 980 Ti.

Below is a kind of nonsense example in which I could somewhat reproduce the issue. If I run it while watching the memory usage in GPU-z I see that the program consumes more and more memory (although I couldn't get it to crash). Interesting thing is that if I replace the graph with a same sized one in each iteration the memory consumption does not increase.

```
public static void main(String[] args) {
        final String inputName = "input";
        final String outputName = "output";
        final String conv1Name = "conv1";
        final String conv2Name = "conv2";
        final int conv1Nout = 1000; // Just a stupid large value to make issue more pronounced
        ComputationGraph graph = getNewGraph(inputName, outputName, conv1Name, conv2Name, conv1Nout);

// With this config I could avoid memory increase if graph.fit is not called...
        final MemoryWorkspace workspace = Nd4j.getWorkspaceManager().createNewWorkspace(WorkspaceConfiguration.builder()
                        .policyAllocation(AllocationPolicy.STRICT)
                        .policyLearning(LearningPolicy.FIRST_LOOP)
                        .policyReset(ResetPolicy.ENDOFBUFFER_REACHED)
                        .policySpill(SpillPolicy.REALLOCATE)
                        .initialSize(0)
                        .build(),
                "testWorkspace");
        final DataSet dummySet;
        // Workspace or not does not matter
        try(MemoryWorkspace ws = workspace.notifyScopeEntered()) {
            dummySet = new DataSet(Nd4j.randn(new long[]{1, 3, 100, 100}), Nd4j.randn(new long[]{1, 10}));
        }
        int cnt = 0;
        while (true) {
            // Workspace or not does not matter
            try(MemoryWorkspace ws = workspace.notifyScopeEntered()) {
                // This is kind of what I want to do...
                graph = getTransferedGraph(conv1Name, conv1Nout - cnt, graph);

                // ... and this leaks just as much...
                //graph = getNewGraph(inputName, outputName, conv1Name, conv2Name, conv1Nout-cnt);

                // Comment out to stop memory leak (!?). Each new graph is identical in size compared to the previous
                cnt++;

                if(cnt % 10 == 0) {
                    // No change visible here...
                    Nd4j.getWorkspaceManager().printAllocationStatisticsForCurrentThread();
                }
                // Note: Each new model is smaller than previous
                System.out.println(cnt + " numParams " + graph.numParams());


                // Comment out to stop memory leak (as long as workspace is used)
                graph.fit(dummySet);

                // Does not help!
                Nd4j.getMemoryManager().invokeGc();
            }
            // Doesn't matter if graph.fit is called inside or outside ws
            // graph.fit(dummySet);
        }
    }

    static ComputationGraph getTransferedGraph(
            String conv1Name,
            int conv1Nout,
            ComputationGraph graph) {
        graph = new TransferLearning.GraphBuilder(graph).nOutReplace(conv1Name, conv1Nout, WeightInit.RELU).build();
        return graph;
    }

    @NotNull
    public static ComputationGraph getNewGraph(String inputName, String outputName, String conv1Name, String conv2Name, int conv1Nout) {
        ComputationGraph graph = new ComputationGraph(new NeuralNetConfiguration.Builder()
                .trainingWorkspaceMode(WorkspaceMode.ENABLED)
                .inferenceWorkspaceMode(WorkspaceMode.ENABLED)
                .graphBuilder()
                .addInputs(inputName)
                .setOutputs(outputName)
                .setInputTypes(InputType.convolutional(100, 100, 3))
                .addLayer(conv1Name, new Convolution2D.Builder(15, 15)
                        .nOut(conv1Nout)
                        .build(), inputName)
                .addLayer(conv2Name, new Convolution2D.Builder(1, 1)
                        .nOut(1)
                        .build(), conv1Name)
                .addLayer(outputName, new OutputLayer.Builder()
                        .nOut(10)
                        .build(), conv2Name)
                .build());
        graph.init();
        return graph;
    }
```

Aha! Link: https://skymindai.aha.io/features/DL4J-63

**Comment by saudet** [comment]
Does calling System.gc() a few times make any difference?

**Comment by AlexDBlack** [comment]
Yeah, try System.gc(). The memory definitely should be cleared.

If it's not - can you give us some dumps of memory info?
i.e., before/after transfer learning on each new model.

https://github.com/deeplearning4j/deeplearning4j/blob/c2c349197c2bff4a1f1e8b8d5db832750616cdbb/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/graph/ComputationGraph.java#L4294-L4308

**Comment by Charele** [comment]
Run a small program, the result is same with DrChainsaw's,

int cnt = 0;
	    while (true) {	
	    	MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()              
	                .list()
	                .layer(0, new DenseLayer.Builder()
	                        .nIn(2000)
	                        .nOut(2000 - cnt) 
	                        // .nOut(2000)
	                        .build())              
	                .build();	  		
	  		new MultiLayerNetwork(conf).init();	    	
	  		cnt++;	    	
	  		Nd4j.getMemoryManager().invokeGc();
	    }

You will see the GPU memory usage increase and increase(I observe by GPU Shark),
invokeGc() is unuseful here.

If you uncomment line, ".nOut(2000)", as DrChainsaw said,  the memory consumption does not increase.

The result of "new TransferLearning.GraphBuilder(graph).nOutReplace..." generate a new ComputationGraph object,
nobody will new ComputationGraph/MultiLayerNetwork repeatedly in his program.
 
The reason is complext, my temporary solution of this question is,
	    while (true) {	
   	                ... ...
	  		cnt++;	    	
	  		Nd4j.getMemoryManager().purgeCaches();
	    }

It will be okay:-)

**Comment by DrChainsaw** [comment]
Ah, pure poetry to my eyes!

I can confirm Nd4j.getMemoryManager().purgeCaches() keeps memory utilization stable.

I'll leave the issue open in case developers wants to device a less explicit solution. Otherwise just close it.

**Comment by saudet** [comment]
It does sound like a bug. I believe the caches should get purged along with the associated network, @AlexDBlack ?

**Comment by DrChainsaw** [comment]
Ok, I ctrl+clicked my way into Nd4j.getMemoryManager().purgeCaches() and it seems like ND4js CUDA backend is caching some shape info, probably for NDArrays and most likely for the benefit of the user. I guess this is quite consistent with memory util not increasing if no new array sizes are used in the loops. 

Furthremore, no matter how I tune versions of the programs above, I can not get them to OOM crash, memory consumption always seems to flatten at about 80%. I guess this indicates that the cache is working as intended.  

Purging global caches just because a model or something goes out of scope might not be beneficial, especially if the cache is behaving well and adjusting its size to the amount of avilable memory.

I opened this issue because I had another issue (cuda memcpy failed) which seemed to be related to my (real) program using more and more memory the longer it ran. This issue seems to persist even with purgeCaches and more or less flat memory utilization (possibly taking a little longer to trigger). 

I'll go back to the drawing board with that one for now and come back if I'm able to isolate something. Anyways, I'll leave this open for @raver119 to comment. Just wanted to say that I'm not certain this is an issue and whatever problems I have are probably caused by something else.

**Comment by AlexDBlack** [comment]
cc @raver119 can we close this? Or anything here we want to look into more?
