### ISSUE TITLE
ND4J: add CPU features info (AVX etc) - supported vs. used

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6433]
Tensorflow:
```
I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
```

It would be nice to add something where we can see (a) what features are supported, and (b) what features are actually being used in practice.
Perhaps we can even log this as part of nd4j (native) init.

Aha! Link: https://skymindai.aha.io/features/ND4J-158

**Comment by raver119** [comment]
Implemented and merged
