### ISSUE TITLE
Bug on CudaFullCachingProvider

### ISSUE THREAD

**Issue by Charele** [eclipse/deeplearning4j#6452]
public void free(AllocationPoint point) {
...
if (reqMemory > CudaEnvironment.getInstance().getConfiguration().getMaximumDeviceCacheableLength() || deviceCachedAmount.get(deviceId).get() >= CudaEnvironment.getInstance().getConfiguration().getMaximumHostCache()) {

Is it ".getMaximumHostCache()" correct?
I think it should be ".getMaximumDeviceCache()".

Also, this is the reason of the issue:-)

https://github.com/deeplearning4j/deeplearning4j/issues/6432

Aha! Link: https://skymindai.aha.io/features/ND4J-156

**Comment by raver119** [comment]
Fixed long ago
