### ISSUE TITLE
Allow implicit broadcast in element-wise merge

### ISSUE THREAD

**Issue by ilyaivensky** [eclipse/deeplearning4j#6488]
In dl4j-1.0.0-beta2:

> Dimensions mismatch on dimension 1: x shape [7, 64, 3], y shape [7, 1, 3]
java.lang.IllegalStateException: Dimensions mismatch on dimension 1: x shape [7, 64, 3], y shape [7, 1, 3]

I got this error while importing Keras model, layer `Multiply()([x, y])`

Aha! Link: https://skymindai.aha.io/features/ND4J-155

**Comment by raver119** [comment]
auto-broadcast support should be introduced in next release, together with cuda support for new ops.

**Comment by raver119** [comment]
in roadmap it's next after current major pr of mixed datatypes support

**Comment by ilyaivensky** [comment]
That is a critical issue since the workaround in Keras cannot be imported to DL4J. 

I got the following error in the import:
> Error deserializing JSON ComputationGraphConfiguration. Saved model JSON is not a valid ComputationGraphConfiguration
java.lang.RuntimeException: Error deserializing JSON ComputationGraphConfiguration. Saved model JSON is not a valid ComputationGraphConfiguration

when added this code in Keras:
```
    x = Permute((2, 1))(x)
    x = Flatten()(x)
    x = RepeatVector(64)(x)
    x = Permute((2, 1))(x)
``` 
That effectively blocks the import of Attention mechanism

**Comment by raver119** [comment]
cc @maxpumperla

**Comment by boluoyu** [comment]
in numpy:
  
    a1 = [[1, 1]]
    a2 = [[1, 1]]
    
    result = np.array(a1) + np.array(a2).transpose()

    print result
[[2 2]
 [2 2]]

it is ok 

but in nd4j :

`  

        float[][] a = {{1, 1}};
        float[][] b = {{1, 1}};
        INDArray array1 = Nd4j.create(a);
        INDArray array2 = Nd4j.create(b);
        INDArray result = array1.add(array2.transpose());
        System.out.println(result);

`
I got this error:
 java.lang.IllegalArgumentException: X and Z arrays must be equal shape. X shape: [1, 2], Z shape: [2, 2] 
why?

**Comment by AlexDBlack** [comment]
This should be supported now automatically for forward pass (now that ND4J supports broadcasting).

But backprop will need to be changed...
