### ISSUE TITLE
Multi-Task/Outputs Classification Evaluation of Computation Graph

### ISSUE THREAD

**Issue by ghost** [eclipse/deeplearning4j#6497]
I am using ComputationGraph to train a Multi-Task learning system (one input sequence + two output sequence). However, when I add evaluations, it does not work for the second output sequence. Here is the error: 
(run-main-0) java.lang.IllegalArgumentException: Unable to evaluate. Predictions and labels arrays are not same shape. Predictions shape: [2989, 23], Labels shape: [2989, 45]
[error] java.lang.IllegalArgumentException: Unable to evaluate. Predictions and labels arrays are not same shape. Predictions shape: [2989, 23], Labels shape: [2989, 45]
[error] 	at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:382)
[error] 	at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:351)
[error] 	at org.deeplearning4j.eval.BaseEvaluation.evalTimeSeries(BaseEvaluation.java:91)
[error] 	at org.deeplearning4j.eval.BaseEvaluation.eval(BaseEvaluation.java:111)
[error] 	at org.deeplearning4j.nn.graph.ComputationGraph.doEvaluationHelper(ComputationGraph.java:4021)
[error] 	at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:3960)
[error] 	at ai.minxiao.tutorial.dl4j.evaluation.Evaluator$.run(Evaluator.scala:55)
[error] 	at ai.minxiao.tutorial.dl4j.evaluation.Evaluator$.run(Evaluator.scala:72)
[error] 	at ai.minxiao.tutorial.dl4j.learning.Learner$$anonfun$runWithTestCGMDEval$1.apply$mcVI$sp(Learner.scala:313)
[error] 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[error] 	at ai.minxiao.tutorial.dl4j.learning.Learner$.runWithTestCGMDEval(Learner.scala:308)
[error] 	at ai.minxiao.tutorial.dl4j.example.cgnn.WSJMultiTaskExample$.main(WSJMultiTaskExample.scala:185)
[error] 	at ai.minxiao.tutorial.dl4j.example.cgnn.WSJMultiTaskExample.main(WSJMultiTaskExample.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)

The first OutputLayer has 45 classes and the second OutputLayer has 23 classes. 
My guess is that it still uses the first OutputLayer's label with the second OutputLayer's prediction for evolution. 
If I only evaluate on the first OutputLayer, it works properly.

For references: the NN architecture is like: 
Word ID Sequence --> EmbeddingLayer --> GLSTM --> GLSTM-A --> RnnOutputLayer-A 
                                                                                         --> GLSTM-B --> RnnOutputLayer-B 
The evaluation is like: 
cg.evaluate(MultiDatasetIterator, Map(0 -> Array(new Evaluation), 1 -> Array(new Evaluation)).

**Comment by mxiao08** [comment]
Always!
