### ISSUE TITLE
SameDiff; repeating same operation multiple times

### ISSUE THREAD

**Issue by nadheesh** [eclipse/deeplearning4j#6563]
```
SameDiff sd = SameDiff.create();

SDVariable var1 = sd.var(Nd4j.rand(3, 5));
SDVariable var2 = sd.randomNormal(0, 1, 5, 1); //random variable 

SDVariable mul = var1.mmul(var2); 

```

How can we repeat `mul` operation multiple times such that, the random variable `var2` produces different random samples? I want to create a SDVariable that compute the mean of multiple `mul` variables .

**Comment by nadheesh** [comment]
Thanks @AlexDBlack , but this is not what I'm looking for.

My goal is to perform probabilistic deep learning (similar to Edward or tensorflow-probability in python) based on Monte-Carlo integration. 

Anyway, I find that we can use` mergeAvg(..)` to take the average of several SDVariables. Can I duplicate the `mul` variable in such a way that each duplication uses different random sample from the randomNormal during the execution? Then, I can uses mergeAvg() to get the average of such several multiplications. I tried using SDVariable.dup(), but it uses the same random sample every time as it seems. (notice that I can't call `sd.exec()` multiple times since I want to compute the gradients of average operation).

**Comment by agibsonccc** [comment]
@nadheesh could you follow up? Was this enough for you?

**Comment by nadheesh** [comment]
I'm sorry that I could not do a follow up sooner.

I was able to implement what I needed as follows;

```
SDVariable[] mulArr = new SDVariable[numIter];
        for (int i = 0; i < numIter; i++) {
              SDVariable var1 = sd.var(Nd4j.rand(3, 5));
              SDVariable var2 = sd.randomNormal(0, 1, 5, 1); //random variable 

              SDVariable mul = var1.mmul(var2); 
              mulArr[i] = mul;
        }
SDVariable avgMul = sd.mergeAvg(mulArr);
```
The trick was to use mergeAvg, however, I'm not sure if there are more efficient ways of duplicating the `mul` variable without using an explicit for loop.

**Comment by AlexDBlack** [comment]
We have loops now for this.
