### ISSUE TITLE
Update dl4j zeppelin docker container

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#6568]
https://deeplearning4j.org/tutorials/setup - docker container is out of date. It's confusing when people try to run it.

**Comment by AlexDBlack** [comment]
Any progress here? Another user ran into this...
0.9.1 that is uses doesn't work properly any more due to the change in the location for a lot of the resources like MNIST.
At the very least we should have some sort of warning if we can't fix this soon.
