### ISSUE TITLE
SameDiff sdvariable.getShape() returns null

### ISSUE THREAD

**Issue by nadheesh** [eclipse/deeplearning4j#6585]
The SDVariable.getShape() returns null for some of the cases such as,

- if the shape is defined using int[] array or interger values, instead of long[] array when initializing the sdvariables

- after certain operations are performed on the sdvariables (such as SameDiff.reshape() etc).

Therefore, in such occasion there is no way of finding out the shape of SDVariables, until the network is evaluated/executed properly.

Aha! Link: https://skymindai.aha.io/features/ND4J-151

**Comment by AlexDBlack** [comment]
Can you provide some code to reproduce the integer array issue?
I've tried the following on both 1.0.0-beta2 and snapshots, and I'm getting the expected shapes.
```
        SameDiff sd = SameDiff.create();
        SDVariable v1 = sd.var("v1", new int[]{1,2,3});
        System.out.println(Arrays.toString(v1.getShape()));

        SDVariable v2 = sd.one("v2", new int[]{1,2,3});
        System.out.println(Arrays.toString(v2.getShape()));

        SDVariable v3 = sd.zero("v3", new int[]{1,2,3});
        System.out.println(Arrays.toString(v3.getShape()));
```

As for the second one: v4 shape here is fine, v5 is null. If you are referring to v5, then this is a known issue - basically we need to implement offline shape inference: https://github.com/deeplearning4j/deeplearning4j/issues/6148
```
        SDVariable v4 = sd.var("v4", new long[]{1,2,3});
        SDVariable v5 = sd.reshape(v4, 6);
        System.out.println(Arrays.toString(v4.getShape()));
        System.out.println(Arrays.toString(v5.getShape()));
```

**Comment by AlexDBlack** [comment]
No longer relevant given API changes for this method
