### ISSUE TITLE
Upgrade Shaded Jackson version

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6655]
The version of Jackson we use (2.5.1 shaded) is now getting old... 2015 release. We should upgrade this for bug and security fixes.

Note that this is the same version of Jackson that Spark 1 uses... Spark 2 is 2.6.5 (2016). Not that we need to sync with these for the shaded version.

I have looked at this briefly in the past, and a new version is not a simple "drop in replacement" for us due to API and functionality changes.

Aha! Link: https://skymindai.aha.io/features/ND4J-150

**Comment by ejschoen** [comment]
For what it's worth, this is a major problem for us.  The critical security vulnerabilities in the older Jackson libs show up in security scans, and large customers with mature IT security processes see these vulnerabilities and require us to remove or mitigate them.  Is it possible to attest that as long as any JSON being read is valid and comes from trusted sources, the vulnerabilities are mitigated?

**Comment by AlexDBlack** [comment]
@ejschoen This is something we've been meaning to get to for a while.
Thanks for flagging it again, we'll talk internally and post here once we have something more to share.

Now, I can't see how our use of Jackson (which is basically limited to deserializing neural network configurations, NDArrays and schemas/transforms in DataVec) could lead to vulnerabilities if used in a standard way, if (a) you know and trust the source of the model/JSON, and/or (b) you control the classpath.

That said, I'm not able to make any claims that any particular CVE is/isn't impossible given our current use of Jackson, without looking at the specifics. And I'd rather spend that time upgrading the library version instead (in the case of the shaded Jackson dependency, it's a matter of when, not if).

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/eclipse/deeplearning4j/pull/8098
Will be merged soon.
