### ISSUE TITLE
ND4J Version Check: Add way to detect mixed Spark versions on cluster

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6676]
ND4J's version check warns about mixed versions on the classpath:
* Mismatched DL4J/ND4J dependencies
* Mismatched Scala 2.10/2.11 dependencies

However, it has no way currently to  detect running Spark 1 code on a Spark 2 cluster (or vice versa) - the Spark dependencies are added by Spark submit at runtime (i.e., Spark adds stuff to the job classpath), not by the user when building their jar.

Errors like this can lead to obscure errors like:
> java.lang.AbstractMethodError: org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMap.call(Ljava/lang/Object;)Ljava/util/Iterator;

For users that have not come across this sort of error before, it is likely not apparent that they are using conflicting Spark versions.

Aha! Link: https://skymindai.aha.io/features/ND4J-148

**Comment by raver119** [comment]
Spark 1 support was removed, so issue isn't relevant anymore.
