### ISSUE TITLE
Small floating point numbers evaluate to zero after loading libnd4jcpu.dll

### ISSUE THREAD

**Issue by migwellian** [eclipse/deeplearning4j#6690]
ND4J 1.0.0-beta2 or beta3
Apache commons-math3 3.6.1
Only affects Windows

We've been sporadically encountering exceptions in the Apache math libraries (specifically the [BrentOptimizer](org.apache.commons.math3.optim.univariate.BrentOptimizer)) when using ND4J. We've narrowed it down to `libnd4jcpu.dll` and we suspect it is because it's [setting the DAZ flag](https://software.intel.com/en-us/node/523328).

Here is a minimal repro case using version 1.0.0-beta2:

```
public class ND4JMemoryCorruption {
    public static void main(String[] args) {
        String filename = "nd4j-native-1.0.0-beta2-windows-x86_64.jar\\org\\nd4j\\nativeblas\\windows-x86_64\\libnd4jcpu.dll";
        System.load(filename);
        double smallValue = 1e-312;
        if (smallValue == 0) {
            throw new RuntimeException("Small numbers evaluate to zero!");
        }
    }
}
```

**Comment by raver119** [comment]
Thanks for highlighting this problem 

With best regards,
Vyacheslav K.

**Comment by raver119** [comment]
Should be fixed now.
