### ISSUE TITLE
ND4S: Missing beta release JAR in Maven

### ISSUE THREAD

**Issue by xhoong** [eclipse/deeplearning4j#6722]
Hi, when I try to grab Nd4s on 1.0.0-beta2 from Maven, it complains that the resources is not found, and apparently from https://mvnrepository.com/artifact/org.nd4j/nd4s only alpha release for 1.0.0 is published. Can the beta (beta2 and beta3) binaries be published as well? Thanks.

Aha! Link: https://skymindai.aha.io/features/ND4J-91

**Comment by saudet** [comment]
We'll need to remove methods that refer to `IComplexNumber` before we can release it...

**Comment by sshepel** [comment]
@xhoong just want to let you know that nd4s, artifacts are present on oss nexus already.

**Comment by saudet** [comment]
@sshepel Awesome, can we close this issue?

**Comment by sshepel** [comment]
@saudet how about to wait till next release, to not forget to check if nd4s artifact is in place :)

**Comment by AlexDBlack** [comment]
Solved with 1.0.0-beta5 release of ND4S
