### ISSUE TITLE
Support dpotrs, dgetrs, dormqr, dtrtrs, and eigen decomposition for asymmetric matrix

### ISSUE THREAD

**Issue by haifengl** [eclipse/deeplearning4j#6764]
They are needed to solve least square problems with the QR decomposition. ND4J supports QR decomposition already. Thanks.

Aha! Link: https://skymindai.aha.io/features/ND4J-145

**Comment by saudet** [comment]
Let's merge issues #6762, #6763, and #6765 here too if it's alright @haifengl?

**Comment by haifengl** [comment]
Yes, it is okay to merge them. Thanks.

**Comment by haifengl** [comment]
The current support of SVD can be improved too. Typically, we use the input matrix to hold the U after the decomposition. But Nd4j's gesvd() method requires U be a m x m matrix, where m is the number of rows. In most case, m be very large (thousand to millions). We cannot hold such big matrix in memory and it is also meaningless to compute m left singular vectors.

**Comment by haifengl** [comment]
Looking into the nd4j implementations, I would suggest the following improvements:

- In geqrf (for QR), the input R is required be a matrix of size n x n. In fact, it could be just a vector of size n. Let's call it tau, which just holds the diagonal of R. The R itself is stored in A.

- In general, we need call a function to determine the workspace size before the real decomposition (e.g. QR, SVD, eigen). It is not clear to me how do you decide the workspace size.

**Comment by saudet** [comment]
@haifengl Sounds good! If you have some time to implement this, feel free to send a pull request. This is not a priority for us, so unless @rcorbish has some time to work on this, we are not likely to spend time on this anytime soon, but feel free to ask questions if you need guidance.
