### ISSUE TITLE
Libnd4j: enforce GCC version in build

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6787]
After running into an odd JVM crash while testing datatypes branch changes, @raver119 and I tracked this back to a compiler issue. I was running an old gcc version - (6.x I think? not sure) and after upgrading, the JVM crash issue isn't present anymore.

To reduce the probability of running into issues like this in the future, we should consider enforcing a recent GCC version during the libnd4j build.

**Comment by saudet** [comment]
GCC 6.x is pretty recent, and pretty much the version we need to use to support CentOS 6, so if we have an issue with that we should find a workaround in libnd4j.

**Comment by saudet** [comment]
That's not exactly trivial, but we can put those in blocks such as:
```
#if __GNUC__ > 6
#pragma omp simd
#endif
```
We already need to do that for Clang anyway.

**Comment by raver119** [comment]
no guys, problem in that code block wasn't in pragma itself.

pragma caused troubles only in specific _sequence_ of operations, and highly likely on specific hardware.
in operation executed standalone - there were no troubles.

**Comment by AlexDBlack** [comment]
@raver119 so, back to the original issue - should we be doing anything (like enforcing gcc versions) to avoid running into this in the future? It's at least a few hours work to track down issues like this...

**Comment by raver119** [comment]
It's N+1 issue, and nobody is guaranteed from that happening, even with latest compilers. Like we had issues after Meltdown/Spectre fixes. So i believe best thing we can do here is tests that are executed in the same build mode that will be used for release. And, using latest compilers, where it's possible.

Luckily, such issues aren't happening THAT often.

**Comment by raver119** [comment]
P.s. if we need GCC 6 to be used for some specific reason - we should enforce its use in test & dev environment as well. If we can go with 7 or 8 - that would be better though.

**Comment by AlexDBlack** [comment]
> P.s. if we need GCC 6 to be used for some specific reason - we should enforce its use in test & dev environment as well. If we can go with 7 or 8 - that would be better though.

Hm, I like this idea, we'd be more likely to catch stuff during normal dev, instead of in final pre-release testing (or not at all). Definitely worth considering IMO (though let's make it overrideable with build flag)

**Comment by raver119** [comment]
@sshepel Can you post a list of compilers/versions used on all platforms we ship to?

**Comment by raver119** [comment]
macosx-x86_64 vs macosx-x86_64-cpu-avx2

Why different versions used there?

**Comment by sshepel** [comment]
@raver119 good question, looks like one of the build agents has been updated by someone...
Which version do we need? I can fix that...

**Comment by raver119** [comment]
use 7.3 there then, as used on macosx-x86_64

**Comment by sshepel** [comment]
> use 7.3 there then, as used on macosx-x86_64

ok, will try to fix that asap...

**Comment by sshepel** [comment]
@raver119 all `macosx-x86_64` build agents now have `7.3` compiler version installed.

**Comment by raver119** [comment]
This issue is fairly outdated now.
