### ISSUE TITLE
jumpy.array leaks memory

### ISSUE THREAD

**Issue by janotav** [eclipse/deeplearning4j#6794]
Hi guys,

Once jumpy is used python process doesn't seem to be able to GC properly. After running following sequence:

```
import gc
import numpy as np
import jumpy as jp
x = np.random.rand(3000000, 21).astype('f')
y = jp.array(x)
del y
del x
gc.collect()
```

My python process ends up with ~440MB of memory. The same sequence with jp.array creation removed leaves the process with memory footprint of ~200MB. The latter number seems to correspond to consumption just before x is generated.

Is this expected? Is it a bug?

**Comment by saudet** [comment]
You'll need to make sure Java's garbage collector too also frees everything
on its side...

**Comment by janotav** [comment]
Ok, but how do I do that? Calling java GC before python GC like this:

```
jp.autoclass("java.lang.System").gc()
gc.collect()
```

seems to make no difference.

**Comment by farizrahman4u** [comment]
@janotav jumpy keeps a reference to all arrays in `jumpy.ndarray._refs`. Calling `.clear()`  on this list should cause the arrays to get garbage collected. Will be adding a proper API for this soon.
