### ISSUE TITLE
ND4J/libnd4j custom ops: Output shape calculation with multiple valid datatypes?

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6872]
Many ops support a variety of input types and output types.
For example:
https://github.com/deeplearning4j/deeplearning4j/blob/af7155d61dc810d3e7139f15f98810e0255b2e17/libnd4j/include/ops/declarable/generic/parity_ops/onehot.cpp#L134-L138

Now, when we do CustomOp.calculateOutputShape() we get shape information back - including a datatype.
The problem: with multiple possible output datatypes, it's not currently possible uniquely determine an output data type from the current inputs - i.e., it's a "free parameter" with multiple valid values.

For the onehot example above - any floating point or integer datatype could be returned, but it seems like float is always returned.

The solution here: I think we need to do something like the following:
1. For ops with multiple valid output datatypes, enforce setting an output datatype at java level
2. Add some way of doing 'output type hints' for custom ops

Related issue: https://github.com/deeplearning4j/deeplearning4j/issues/6854

If we have user-defined output datatypes, then there's 2 ways we can use this:
Option 1 (bad IMO): Just ignore the calculateOutputShapes() datatype in Java, and use specified datatype (seems like a recipe for hard to detect dtype bugs...)
Option 2 (better): set the output type as an optional arg on custom op? For "multiple valid output dtype" ops, use dtype arg if present, or some default type if not.

Aha! Link: https://skymindai.aha.io/features/ND4J-141

**Comment by shugeo** [comment]
operation has a datatype of output.
