### ISSUE TITLE
Documentation copy/paste problem

### ISSUE THREAD

**Issue by mattbushell** [eclipse/deeplearning4j#6934]
https://deeplearning4j.org/tutorials/04-feed-forward

The last code example has the Layers as 3 OutputLayer instead of DenseLayer.

**Comment by saudet** [comment]
Please send a pull request if you can! Thanks

**Comment by cpoerschke** [comment]
question/observation: is https://github.com/deeplearning4j/dl4j-examples/tree/master/tutorials rather than `deeplearning4j/deeplearning4j` (here) is the repo for the pull request in this case? thanks!

**Comment by saudet** [comment]
@cpoerschke Indeed, it seems to be defined there. @crockpotveggies ?

**Comment by crockpotveggies** [comment]
Confirmed, tutorials are generated by notebooks in the `dl4j-examples` repository. Please submit PRs to that specific file tree you have linked above! Thank you.
