### ISSUE TITLE
ND4J/DL4J: Improve DataSetIteratorSplitter (add configurable train/test/validation sets etc)

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6993]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-data/deeplearning4j-utility-iterators/src/main/java/org/deeplearning4j/datasets/iterator/DataSetIteratorSplitter.java

A simple improvement here is to allow more than 2 subsets/splits.

Aha! Link: https://skymindai.aha.io/features/ND4J-135

**Comment by raver119** [comment]
Implemented in beta5
