### ISSUE TITLE
SameDiff: retire Op method resolvePropertiesFromSameDiffBeforeExecution()

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7004]
This method has been a useful hack for handling a few TF import edge cases, but it's not something we want long-term: it's not a robust solution given that we also need the op to be executable at the libnd4j level post flatbuffers export.

Here's an example of where it is used:
https://github.com/deeplearning4j/deeplearning4j/blob/a2176bed41440203ce7f660d84759064cd59b931/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/random/impl/Linspace.java#L123-L146

Aha! Link: https://skymindai.aha.io/features/ND4J-133

**Comment by rnett** [comment]
So Linspace's got removed at some point.

`Repeat` adds output arguments if there's less than the descriptor's numOutputs.  What exactly is going on there?

`HistogramFixedWidth`, `Pad`, and `UnsortedSegment*` all add an array argument as an IArg (or TArg for `Pad`), I'll make a separate issue for adding array arg support to c++.
