### ISSUE TITLE
ND4J: regression in safety from 0.8.1 to 1.0.0-beta3 in NDArray.shape()

### ISSUE THREAD

**Issue by mbkennel** [eclipse/deeplearning4j#7091]
#### Issue Description

I encountered a vexatious problem upgrading a project to use 1.0.0-beta3 from 0.8.1.  I was seeing inexplicable and nonsensical exceptions in basic matrix operations that worked OK before.

The problem appears to be a change in the semantics of the .shape() method on NDArrays. I don't know the internals but am looking at externally visible behavior.  Previously it was returning a safe value copy of int[].  I was modifying one element of that return value and then creating a new NDArray from it.

In 1.0.0-beta3, it returns long[] (no problem), but additionally it appears to be returning an internal reference that is *NOT* safe to modify, and this lack of safety is surprising, and not obviously documented, and results in difficult to find errors, as the internal operations crash on later operations that use the original NDArray.

Please describe our issue, along with:
- expected behavior
 ```
long[] the_shape[] = array1.shape();
the_shape[0] *= 2; // double its # of rows.  OK, because it's a value copy
INDArray array2 = Nd4j.create(the_shape);
// populate array2 here
```
- encountered behavior
With above code which was safe with 0.8.1, but not in 1.0.0-beta3, later uses of array1 can crash inside ND4J.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version:  1.0.0-version 3
* platform information (OS, etc): Ubuntu 18.4 LTS
* CUDA version, if used: not used
* NVIDIA driver version, if in use: not used

Aha! Link: https://skymindai.aha.io/features/ND4J-131

**Comment by raver119** [comment]
It's easy fix, but it'll automatically create lots of useless long[] in dl4j/nd4j code... Not sure how good is it. cc @AlexDBlack

**Comment by mbkennel** [comment]
Well one way is to refactor current shape() into shapeRef() for high performance read-only uses and a new one named shape() for a value copy.   Or something else, but at least in tutorials warn against consequences of modifying the result, as it's an easy beginner mistake with bizarre errors.
