### ISSUE TITLE
ND4J/SameDiff/libnd4j: add support for arrays with 0s in shape

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7112]
Example: rank 2, shape [0,2]
This is considered a valid array in tensorflow for some operations.

Now, we already have empty arrays, which works fine for the majority of ops. But these don't have shape/rank information available (empty arrays in our current implementation don't have either rank or shape).

However, one place where our "shape-less and rank-less" empty arrays doesn't work for TF import: rank and shapeof ops. I'm seeing this in practice in SSD model import: it has ```empty -> shape -> strided slice```, as a sequence of ops in the graph.
There's simply no way to get the correct result from this sequence of operations without allowing 0s in shapes for NDArrays.

Test case to reproduce:
https://gist.github.com/AlexDBlack/0bb57a8f4fe910e95fef669236459fc3

Some considerations here:
1. Public API: do we allow users to make these arrays via normal constructors? IMO no - only way to create these should be as the output of an op, or via an ```Nd4j.empty(DataType, long... shape)``` op.
2. Lots of ops are going to need minor changes (mostly libnd4j, some java)
3. We'll need a ton of new tests to verify correctness for this edge case vs. TF

PR with TF import test cases: https://github.com/deeplearning4j/dl4j-test-resources/pull/183

Aha! Link: https://skymindai.aha.io/features/ND4J-128

**Comment by AlexDBlack** [comment]
Here's another example:
```
tf.reset_default_graph()
input = tf.constant([12], dtype=tf.int32)
begin = tf.constant([0], dtype=tf.int32)
size = tf.constant([0], dtype=tf.int32)
slice = tf.slice(input, begin=begin, size=size)
sess = tf.Session()
out = sess.run([slice])
print("Shape: ", out[0].shape)
print("Rank: ", out[0].ndim)
print("Values: ", out[0])
```
Output:
```
Shape:  (0,)
Rank:  1
Values:  []
```

For the same inputs, ND4J (slice op) returns a rank 0 non-empty array, then fails on the exec:
```
    @Test
    public void test(){

        INDArray in = Nd4j.createFromArray(12);
        INDArray begin = Nd4j.createFromArray(0);
        INDArray size = Nd4j.createFromArray(0);

        DynamicCustomOp op = DynamicCustomOp.builder("slice")
                .addInputs(in, begin, size)
                .addOutputs(Nd4j.scalar(0))
                .build();

        List<LongShapeDescriptor> l = op.calculateOutputShape();
        System.out.println("Shape: " + Arrays.toString(l.get(0).getShape()));
        System.out.println("EMPTY: " + l.get(0).isEmpty());

        Nd4j.exec(op);
    }
```

```
Shape: []
EMPTY: false

Error at [C:/DL4J/Git/deeplearning4j/libnd4j/include/ops/declarable/generic/parity_ops/slice.cpp:65:0]:
Slice: interval for dimension 0 is less then 1
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op slice. Attempted to execute with 3 inputs, 1 outputs, 0 targs,0 bargs and 0 iargs. Inputs: [(INT,[1],c), (INT,[1],c), (INT,[1],c)]. Outputs: [(INT,[],c)]. tArgs: -. iArgs: -. bArgs: -. Op own name: "6ec4932b-6fe1-4e59-b636-a4a0b027f908" - Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: Op [slice] execution failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1645)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:7291)
```

**Comment by raver119** [comment]
I suppose we're done here now?

**Comment by AlexDBlack** [comment]
Yep, done. Forgot to close this earlier.
