### ISSUE TITLE
macOS failed build for CUDA backend

### ISSUE THREAD

**Issue by sshepel** [eclipse/deeplearning4j#7186]
#### Issue Description

libnd4j builds for any CUDA backend on macOS platform are failing with following error:

```
6 warnings generated.
[ 99%] Building CXX object blas/CMakeFiles/nd4jcuda.dir/__/include/ops/impl/specials_sparse.cpp.o
clang: warning: argument unused during compilation: '-fmax-errors=2' [-Wunused-command-line-argument]
[100%] Linking CXX shared library libnd4jcuda.dylib
clang: warning: argument unused during compilation: '-fmax-errors=2' [-Wunused-command-line-argument]
ld: in section __TEXT,__text reloc 138: length != 2 and X86_64_RELOC_GOT not supported file 'CMakeFiles/nd4jcuda.dir/__/include/ops/declarable/helpers/cpu/adjust_hue.cpp.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [blas/libnd4jcuda.dylib] Error 1
make[1]: *** [blas/CMakeFiles/nd4jcuda.dir/all] Error 2
make: *** [all] Error 2
```

Full build log can be found [here](https://gist.github.com/sshepel/daf4fd5c8c96d0dd08ee9d8bd0c4ecff)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): macOS 10.12, 10.14
* CUDA version: 9.0, 9.2, 10.0
* NVIDIA driver version: latest

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

Aha! Link: https://skymindai.aha.io/features/DL4J-12

**Comment by saudet** [comment]
This is way too obscure. Let's report this bug to NVIDIA:
https://developer.nvidia.com/cuda-faq#Programming
And until this is fixed, let's just drop support for CUDA on Mac. Sounds good?

**Comment by sshepel** [comment]
> And until this is fixed, let's just drop support for CUDA on Mac. Sounds good?

worth a try, I think...
