### ISSUE TITLE
ND4J/Libnd4j: CUDA - optimize scatter ops for 1D case

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7256]
Recent benchmarking has identified that this 1d edge case (1d input array, 1d indices - each update is 1 scalar only) is slower on CUDA than CPU.  A 1D-specific kernel could accelerate this significantly.
However, this is not a high priority use case (2+D is more common).

Libnd4j benchmark: https://gist.github.com/AlexDBlack/e03b089e6151034b3e54dfdda10f0d83

Aha! Link: https://skymindai.aha.io/features/ND4J-56

**Comment by raver119** [comment]
Implemented and merged
