### ISSUE TITLE
DL4J/Libnd4j: Add MKL-DNN LSTM support

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7282]
As per title.
We may be able to add this to lstmBlock op - but I'm not sure if that matches the MKL-DNN API. If not, we might need to add another LSTM op.

Aha! Link: https://skymindai.aha.io/features/ND4J-97

**Comment by raver119** [comment]
Implemented quite some time ago. LSTM bp is WIP.
