### ISSUE TITLE
deeplearning4j-nlp tests failures

### ISSUE THREAD

**Issue by alexanderst** [eclipse/deeplearning4j#7358]
<strike>Tests in deeplearning4j-nlp-parent fail when full test set is started. Tests are passed successfully when distinct test classes are started. Reproduced on Linux and Windows, CPU backend.</strike>

**Fixed.**

**Comment by alexanderst** [comment]
Failures (may be different on different systems):

org.deeplearning4j.TsneTest.testSimple(TsneTest.java:90)
java.lang.OutOfMemoryError: GC overhead limit exceeded

org.deeplearning4j.bagofwords.vectorizer.BagOfWordsVectorizerTest.testBagOfWordsVectorizer(BagOfWordsVectorizerTest.java:75)
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds

org.deeplearning4j.bagofwords.vectorizer.TfidfVectorizerTest.testParallelFlag2(TfidfVectorizerTest.java:159)
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds

org.deeplearning4j.bagofwords.vectorizer.TfidfVectorizerTest.testTfIdfVectorizer(TfidfVectorizerTest.java:75)
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds

org.deeplearning4j.iterator.TestCnnSentenceDataSetIterator
Assertions failed

org.deeplearning4j.models.glove.count.BinaryCoOccurrenceReaderTest.testHasMoreObjects1(BinaryCoOccurrenceReaderTest.java:82)
java.lang.OutOfMemoryError: Java heap space

org.deeplearning4j.models.paragraphvectors.ParagraphVectorsTest.testDirectInference(ParagraphVectorsTest.java:1011)
at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.configure(SkipGram.java:125)
    at org.deeplearning4j.models.sequencevectors.SequenceVectors.initLearners(SequenceVectors.java:197)
    at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:326)
java.lang.NoClassDefFoundError: org/nd4j/linalg/util/DeviceLocalNDArray


org.deeplearning4j.models.paragraphvectors.ParagraphVectorsTest.testJSONSerialization(ParagraphVectorsTest.java:1126)
java.lang.NoClassDefFoundError: org/nd4j/shade/jackson/core/JsonFactory

    at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.mapper(ParagraphVectors.java:719)
    at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.toJson(ParagraphVectors.java:735)
    at org.deeplearning4j.models.paragraphvectors.ParagraphVectorsTest.testJSONSerialization(ParagraphVectorsTest.java:1126)





org.deeplearning4j.models.word2vec.Word2VecTestsSmall.testUnkSerialization_1

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException

    at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeWord2VecModel(WordVectorSerializer.java:433)
    at org.deeplearning4j.models.word2vec.Word2VecTestsSmall.testUnkSerialization_1(Word2VecTestsSmall.java:117)

org.deeplearning4j.text.documentiterator.FilenamesLabelAwareIteratorTest.testNextDocument(
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertFalse(Assert.java:64)
    at org.junit.Assert.assertFalse(Assert.java:74)
    at org.deeplearning4j.text.documentiterator.FilenamesLabelAwareIteratorTest.testNextDocument(FilenamesLabelAwareIteratorTest.java:68)

TestCnnSentenceDataSetIterator
Assertions failed

**Comment by raver119** [comment]
👍  Memory errors are probably related to that LongBuffer issue...

**Comment by alexanderst** [comment]
Failures in nd4j-native
tests:
  TFGraphTestAllLibnd4j.test:170 output: 1 values exceed maxRelError=0.001 with minAbsError=1.0E-5; largest observed relError=0.0023089356254786253 expected:<0> but was:<1>
  TFGraphTestAllLibnd4j.test:170 Predictions do not match on nth_element/rank2_n3_reverse, node NthElement
  TFGraphTestAllLibnd4j.test:170 Predictions do not match on nth_element/rank2_n4, node NthElement
  TFGraphTestAllLibnd4j.test:170 Predictions do not match on nth_element/rank3_n2, node NthElement
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on cond/cond_true, node cond/Merge
  TFGraphTestAllSameDiff.testOutputOnly:178 output: 1 values exceed maxRelError=0.001 with minAbsError=1.0E-5; largest observed relError=0.0023089356254786253 expected:<0> but was:<1>
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on nth_element/rank2_n3_reverse, node NthElement
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on nth_element/rank2_n4, node NthElement
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on nth_element/rank3_n2, node NthElement
  OpExecutionerTests.testSum6d2:643 expected:<1160.0> but was:<392.0>

Tests run: 4066, Failures: 10, Errors: 0, Skipped: 326Failed

**Comment by alexanderst** [comment]
dl4j-core
org.deeplearning4j.nn.mkldnn.ValidateMKLDNN.validateBatchNorm
o.d.LayerHelperValidationUtil - Forward pass, max relative error: layer_-1 - input - 0.0
o.d.LayerHelperValidationUtil - Forward pass, max relative error: layer_0 - ConvolutionLayer - 0.0
Different values at index 227: -0.3762032985687256, 0.3200366199016571 - RE = 1.0

org.deeplearning4j.LayerHelperValidationUtil.validateMLN(LayerHelperValidationUtil.java:130)
    at org.deeplearning4j.nn.mkldnn.ValidateMKLDNN.validateBatchNorm(ValidateMKLDNN.java:173)
org.deeplearning4j.nn.layers.convolution.Upsampling1DTest.testUpsampling1DBackprop

java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.repeat(I[I)Lorg/nd4j/linalg/api/ndarray/INDArray;

    at org.deeplearning4j.nn.layers.convolution.upsampling.Upsampling1D.backpropGradient(Upsampling1D.java:65)
    at org.deeplearning4j.nn.layers.convolution.Upsampling1DTest.testUpsampling1DBackprop(Upsampling1DTest.java:88)
org.deeplearning4j.gradientcheck.BNGradientCheckTest.testGradientBNWithCNNandSubsamplingcCnfigurableProfile
Should be removed

**Comment by alexanderst** [comment]
dl4j-modelimport
org.deeplearning4j.nn.modelimport.keras.configurations.Keras2ModelConfigurationTest.runModelConfigTest(Keras2ModelConfigurationTest.java:271) 
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]
  org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
    at org.deeplearning4j.nn.modelimport.keras.configurations.Keras2ModelConfigurationTest.runModelConfigTest(Keras2ModelConfigurationTest.java:271) 

org.deeplearning4j.nn.modelimport.keras.configurations.Keras2ModelConfigurationTest.dgaClassifierTfConfigTest(Keras2ModelConfigurationTest.java:88)

java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

org.deeplearning4j.nn.modelimport.keras.configurations.Keras2ModelConfigurationTest.embeddingConv1DTfTest(Keras2ModelConfigurationTest.java:195)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

org.deeplearning4j.nn.modelimport.keras.configurations.Keras2ModelConfigurationTest.convPooling1dTfConfigTest(Keras2ModelConfigurationTest.java:93)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

org.deeplearning4j.nn.modelimport.keras.configurations.Keras2ModelConfigurationTest.flattenConv1DTfTest(Keras2ModelConfigurationTest.java:200)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.importDgaClassifier(KerasModelEndToEndTest.java:356)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.testMaskingZeroValue, testMaskingTwoValue, testMaskingLayer
java.lang.StackOverflowError
    at org.deeplearning4j.nn.conf.layers.util.MaskZeroLayer$Builder.setMaskValue(MaskZeroLayer.java:118)

org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.importCnn1d(KerasModelEndToEndTest.java:348)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

org.deeplearning4j.nn.modelimport.keras.layers.convolution.KerasAtrousConvolution1DTest.testAtrousConvolution1DLayer(KerasAtrousConvolution1DTest.java:66)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [2, 2]

org.deeplearning4j.nn.modelimport.keras.layers.convolution.KerasConvolution1DTest.testConvolution1DLayer(KerasConvolution1DTest.java:67)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [2, 2]

org.deeplearning4j.nn.modelimport.keras.weights.KerasWeightSettingTests.testSimpleLayersWithWeights(KerasWeightSettingTests.java:71)
java.lang.IllegalArgumentException: Need 1 dilation value, got 2 values: [1, 1]

**Comment by alexanderst** [comment]
nearest-neighbors-parent/nearest-neighbor-core
org.deeplearning4j.clustering.lsh.RandomProjectionLSHTest.testANNSearchReflexive(RandomProjectionLSHTest.java:195)
java.lang.ArrayIndexOutOfBoundsException: 1

org.deeplearning4j.clustering.lsh.RandomProjectionLSHTest.testEntropyDims
java.lang.ArrayIndexOutOfBoundsException: 1

    at org.deeplearning4j.clustering.lsh.RandomProjectionLSH.entropy(RandomProjectionLSH.java:129)
    at org.deeplearning4j.clustering.lsh.RandomProjectionLSHTest.testEntropyDims(RandomProjectionLSHTest.java:56)
 
org.deeplearning4j.clustering.lsh.RandomProjectionLSHTest.testBucketReflexive(RandomProjectionLSHTest.java:111)
java.lang.ArrayIndexOutOfBoundsException: 1

org.deeplearning4j.clustering.lsh.RandomProjectionLSHTest.testGetRawBucketOfDims(RandomProjectionLSHTest.java:89)
java.lang.AssertionError: array lengths differed, expected.length=2 actual.length=1

org.deeplearning4j.clustering.lsh.RandomProjectionLSHTest.testBucketDataReflexive(RandomProjectionLSHTest.java:131)
java.lang.ArrayIndexOutOfBoundsException: 1

    at org.deeplearning4j.clustering.lsh.RandomProjectionLSH.entropy(RandomProjectionLSH.java:129)

…

org.deeplearning4j.clustering.randomprojection.RPUtilsTest.testDistanceComputeBatch(RPUtilsTest.java:32)
org.nd4j.linalg.exception.ND4JIllegalStateException: Shape of target array for reduction [[4]] doesn't match expected [1]

**Comment by alexanderst** [comment]
deeplearning4j-zoo
org.deeplearning4j.zoo.TestInstantiation.testMultipleCnnTraining(TestInstantiation.java:85)
java.lang.OutOfMemoryError: Cannot allocate new LongPointer(12): totalBytes = 472M, physicalBytes = 14766M

**Comment by alexanderst** [comment]
**Assert failed:**
org.deeplearning4j.earlystopping.TestEarlyStoppingCompGraph.testTimeTermination()

	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.deeplearning4j.earlystopping.TestEarlyStoppingCompGraph.testTimeTermination(TestEarlyStoppingCompGraph.java:183)

**Comment by AlexDBlack** [comment]
> org.deeplearning4j.earlystopping.TestEarlyStoppingCompGraph.testTimeTermination()

Already fixed on my branch, should be merged today.
