### ISSUE TITLE
Libnd4j: Add broadcastable elementwise power derivative

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7461]
I don't believe we have a derivative for this op: https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/broadcastable/pow.cpp
(we only have derivative for scalar power, not broadcast/pairwise power).

If y=a^b, then:
```
dL/da = b*a^(b-1) * dL/dy
dL/db = a^b * log(a) * dL/dy
```

**Comment by raver119** [comment]
Implemented. 

cc @AlexDBlack
