### ISSUE TITLE
Python execution is hard to debug

### ISSUE THREAD

**Issue by agibsonccc** [eclipse/deeplearning4j#7544]
Simple example:
I just run:
    String filePath = "/home/agibsonccc/code/keras-nlp/simple_import.py";
        PythonExecutioner.exec(FileUtils.readFile(filePath));

which contains:
```python
import sys
paths = '/home/agibsonccc/anaconda3/lib/python36.zip', '/home/agibsonccc/anaconda3/lib/python3.6', '/home/agibsonccc/anaconda3/lib/python3.6/lib-dynload', '/home/agibsonccc/anaconda3/lib/python3.6/site-packages', '/home/agibsonccc/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg'
for path in paths:
    sys.path.append(paths)
    
from keras import Sequential
from keras import layers
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import os
from sklearn.model_selection import train_test_split
print('Hello World!')
```

Imports fail and it's hard to tell why. These python paths are just from a simple miniconda install.

Right now, it just fails with:
```
Exception in thread "main" java.lang.RuntimeException: exec failed
	at org.datavec.python.PythonExecutioner.exec(PythonExecutioner.java:250)
	at ai.skymind.Train.main(Train.java:10)

```

I'd like a way of surfacing why it failed. 

@saudet any input here?

**Comment by saudet** [comment]
AFAIU, the functions for embedding Python don't print anything on error. We need to call `PyErr_Print()` to get the usual stack trace. That only prints to stderr though, I don't think there's a way to change that...
