### ISSUE TITLE
DL4J: BarnesHutTsne performance

### ISSUE THREAD

**Issue by alexanderst** [eclipse/deeplearning4j#7554]
org.deeplearning4j.plot.BarnesHutTsne class has performance problems.

Can be verified with test org.deeplearning4j.TsneTest.testSimple().

**Comment by alexanderst** [comment]
Nested loops with ops calls are used in Java code. Possible solution is to implement C++ operations for the following places:

https://github.com/deeplearning4j/deeplearning4j/blob/0c7d15e2cc3d2167672f6ea96dbe45dec92c1f0e/deeplearning4j/deeplearning4j-nearestneighbors-parent/nearestneighbor-core/src/main/java/org/deeplearning4j/clustering/sptree/SpTree.java#L314

https://github.com/deeplearning4j/deeplearning4j/blob/fceb662a76e8f72f2eed7def33c727c4f9a3eb09/deeplearning4j/deeplearning4j-manifold/deeplearning4j-tsne/src/main/java/org/deeplearning4j/plot/BarnesHutTsne.java#L406

https://github.com/deeplearning4j/deeplearning4j/blob/fceb662a76e8f72f2eed7def33c727c4f9a3eb09/deeplearning4j/deeplearning4j-manifold/deeplearning4j-tsne/src/main/java/org/deeplearning4j/plot/BarnesHutTsne.java#L584

**Comment by raver119** [comment]
Fixed quite some time ago
