### ISSUE TITLE
ND4S: Review and fix datatypes

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7599]
We have a few tests failing as per this issue: https://github.com/deeplearning4j/deeplearning4j/issues/7594

However, I think we have bigger problems than just a few failing tests.
My quick reading of the ND4S code suggests that we need to carefully review and fix datytpes whenever we are creating NDArrays, to match behaviour of ND4J
For example:
- Implicits.IntMtrix2INDArray, IntArrayMtrix2INDArray, IntArray2INDArray - creates float datatype NDArrays; ND4J equivalent (Nd4j.createFromArray(int[]) etc) would produce an integer INDArray
- Implicits.Num2Scalar[T] - creates a double scalar regardless of the type? ND4J has overloads for creating scalars of double/float/long/int/boolean etc type

There's probably more examples of this.

Also, I don't see support for String, Long, Boolean, Byte, Half etc type NDArrays that ND4J supports natively now.

**Comment by alexanderst** [comment]
@raver119 Fixed.

**Comment by raver119** [comment]
👍
