### ISSUE TITLE
Add Python install validation to maven for modules using python

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7600]
For modules using Python (datavec-python, pydatavec, pydl4j) we should check the user's python install - both that it's present, is the required version (2 vs. 3) and has any required libraries.
For example, for datavec-python at present on Windows, if python is missing or misconfigured, we get obscure errors like:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
Current thread 0x00006cbc (most recent call first):
```
and
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Users\Alex\Anaconda3\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
```

**Comment by saudet** [comment]
That'll get fixed once I'm done bundling Python itself in the presets.
