### ISSUE TITLE
INDArray.getWhere() does not work on Linux x86_64

### ISSUE THREAD

**Issue by nicoulaj** [eclipse/deeplearning4j#7632]
#### Issue Description
This test:

    @Test
    public void testGetWhere() {
        INDArray input = Nd4j.create(new double[] { 1, -3, 4, 8, -2, 5 });
        INDArray expected = Nd4j.create(new double[] { 4, 8, 5 });
        INDArray actual = input.getWhere(input, Conditions.greaterThan(1));
        assertEquals(actual, expected);
    }

fails with logs:
```
Validation error at /home/jenkins/workspace/deeplearning4j-master-linux-x86_64-centos6-cpu/libnd4j/include/ops/declarable/impl/DeclarableOp.cpp:448 code=4() "this->validateArguments(*block)" 
choose: Number of T arguments should be positive number, but got 0 arguments

java.lang.AssertionError: expected [[    4.0000,    8.0000,    5.0000]] but found [[         0,         0,         0,         0,         0,         0]]
Expected :[    4.0000,    8.0000,    5.0000]
Actual   :[         0,         0,         0,         0,         0,         0]
```

#### Version Information

* Deeplearning4j version: sonatype repo 1.0.0 snapshot: 1.0.0-SNAPSHOT 2019-04-25
* platform information (OS, etc): linux x86_64
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by alexanderst** [comment]
There's validation failure on C++ side - tArgs are validated as required, but it's legal to have them empty nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/custom/Choose.java#L97

Output:
"Validation error at /home/alex/skymindIO/deeplearning4j/libnd4j/include/ops/declarable/impl/DeclarableOp.cpp:447 code=4() "this->validateArguments(*block)" 
choose: Number of T arguments should be positive number, but got 0 arguments"

**Comment by raver119** [comment]
Fixed
