### ISSUE TITLE
GPU memory not released

### ISSUE THREAD

**Issue by madhs53** [eclipse/deeplearning4j#7651]
Training MultiLayerNetworks using 1.0.0-beta3 with CUDA backend (NVidia-P100) we are seeing constant gradual GPU memory growth.

Using heap dumps I've also seen that the number of instances of org.bytedeco.javacpp.Pointer
 continues in increase - it does not decrease once training has finished. When the next model trails, the number increases (along with GPU memory usage).

I've attached 2 VisualVM snapshots, a few minutes apart. Between the first and second snapshot a small model was trained (small dataset) and completed. The number of points has increased. 

Note that auto GC is enabled at 15 second intervals and we are using AsyncDataSetIterator and EarlyStoppingTrainer.

[snapshots.zip](https://github.com/deeplearning4j/deeplearning4j/files/3140466/snapshots.zip)

Not only is this observed between multiple training runs, but also occurs during a single LSTM run. This is causing problems when we train large models, especially LSTM with a large dataset, as we usually reach the GPU memory limit after several hundred epochs.

Any advice is greatly appreciated.

**Comment by AlexDBlack** [comment]
Try again with 1.0.0-beta4 (just released).
There were changes/improvements to memory management as well as fixes that might impact this.

If it is still reproducible on beta4, can you provide the model configuration as well as the code used to start/run early stopping?

**Comment by raver119** [comment]
Variable time series, i suppose?

**Comment by madhs53** [comment]
@AlexDBlack Thanks. I'll try with beta4 and report back.

@raver119 yeah variable time series for LSTM but with padded features.

**Comment by madhs53** [comment]
I'm trying to build 1.0.0-beta4 from source (see [Issue 6805](https://github.com/deeplearning4j/deeplearning4j/issues/6805) for why - we are running on a specific server configuration that had issues where we had to build from source to fix.)

I've encountered this error:

`[ERROR] Failed to execute JavaCPP Builder: Cannot run program "powerpc64le-linux-gnu-g++" (in directory "/rstudio/working/mvn/ws/dl4j/repo_beta4/deeplearning4j/deeplearning4j-release-1.0.0-beta4/nd4j/nd4j-ba                              ckends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/linux-ppc64le"): error=2, No such file or directory
`

This is at step:
[INFO] nd4j-native 1.0.0-SNAPSHOT ......................... FAILURE [ 36.021 s]

Can I skip this step if I'm using CUDA?

**Comment by saudet** [comment]
Try to use the default g++ maybe with 
mvn -Djavacpp.platform.compiler=g++ ...

**Comment by madhs53** [comment]
Thanks. It looks like I'm getting a new error now:

`[ERROR] Failed to execute goal on project nd4j-native: Could not resolve dependencies for project org.nd4j:nd4j-native:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:mkl:jar:linux-ppc64le:2019.3-1.5, org.bytedeco:mkl-dnn:jar:linux-ppc64le:0.18.1-1.5: Could not find artifact org.bytedeco:mkl:jar:linux-ppc64le:2019.3-1.5 in maven-restlet (http://maven.restlet.org) -> [Help 1]
`

**Comment by saudet** [comment]
How are you getting this error? Which version of Maven are you using?
