### ISSUE TITLE
Mono Repo (Multiple Projects) - CI Test Failures

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7657]
**Last updated: 2019/06/03**

### libnd4j

linux-ppc64le-cpu
* AttentionTests.basic_dot_product_attention_bp: `run_tests.sh: line 33:  7481 Segmentation fault      (core dumped)`
* Also `AttentionTests.basic_dot_product_attention_bp_with_mask` and `AttentionTests.multi_head_input_dot_product_attention_bp_with_mask` - same crash.

linux-x86_64-cuda-9.2
* Test build is broken on CI: https://gist.github.com/AlexDBlack/da88c504c1551c1bd011e4a28861dc16

### nd4j-tests

Note: Failures lists here may not be complete. Tests appear to be cut short due to JVM crash, not running later tests.

linux-x86_64-cpu
* `JVM crash on: test[reductions/count_nonzero_all](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`
    - Later run: crash was on `[losses/huber_diff_rank2_axis1_SUM_BY_NONZERO_WEIGHTS](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`

linux-x86_64-cpu-avx2
* `JVM crash on: test[losses/huber_diff_rank3_weights2](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)` (also on avx512)
   - Later run: crash was on `[losses/huber_diff_rank2_axis1_SUM_BY_NONZERO_WEIGHTS](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)` instead
* Failure: `[unsorted_segment/unsorted_segment_sum_rank2](org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff)` - Predictions do not match on unsorted_segment/unsorted_segment_sum_rank2, node UnsortedSegmentSum

linux-x86_64-cpu-avx512
* `[losses/log_loss_rank3_weights1](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`
* Failure: `[unsorted_segment/unsorted_segment_mean_rank2](org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff)`: Predictions do not match on unsorted_segment/unsorted_segment_mean_rank2, node UnsortedSegmentMean/truediv
* JVM crash on `org.nd4j.linalg.serde.LargeSerDeTests` - not seen on other platforms/tests inc. avx2

linux-ppc64le-cpu
* JVM crash: Running org.nd4j.autodiff.samediff.FailingSameDiffTests
    - Not sure if fixed: 2019/05/18 crashes before getting here...
* JVM crash: `TFGraphs.BERTGraphTest`
    - https://gist.github.com/AlexDBlack/f3dd917ff3f5e36369911356d61b987e
* JVM crash: `TFGraphTestZooModels - squeezenet_2018_04_27` - https://gist.github.com/AlexDBlack/ab68b3aab0440d6d3a25586c8ed25457
* JVM crash: `TFGraphTestAllSameDiff - g_11` and `g_02` - https://gist.github.com/AlexDBlack/7c44b3ef165e470348b951da4a00b55f
* Most other tests not run due to previous crash...
* JVM crash on ValidateZooModelPredicitons
* JVM crash: org.nd4j.imports.ExecutionTests - https://gist.github.com/AlexDBlack/f15e90501d7c94a7e59050dadfb92204\
* JVM crash: org.nd4j.evaluation.ROCTest - https://gist.github.com/AlexDBlack/bba4bab8ac59fdce0b47549d4e954b53
**NOTE: After countless JVM crashes, I have disabled TFGraphTestAllSameDiff, TFGraphTestAllLibnd4j, and TFGraphTestZooModels on PPC entirely**

linux-x86_64-cuda-9.2
* JVM Crash: `TFGraphs.BERTGraphTest` - https://gist.github.com/AlexDBlack/fb972a5c1039a1c6adbff685dab8ad56
* org.nd4j.linalg.api.buffer.FloatDataBufferTest.testPointerCreation: NPE only on CUDA
* org.nd4j.serde.base64.Nd4jBase64Test.testBase64Npy: NPE only on CUDA
* org.nd4j.linalg.api.buffer.DoubleDataBufferTest.testPointerCreation: NPE only on CUDA
* ValidationUtilTests.testNpyValidation: NPE only on CUDA
* MixedDataTypesTests.testArrayCreationFromPointer: : NPE only on CUDA
* TestNDArrayCreation.testCreateNpy3: : NPE only on CUDA
* TestNDArrayCreation.testBufferCreation: NPE only on CUDA
* Nd4jTest.testNumpyWrite: NPE only on CUDA
* Nd4jTest.testNumpyConversion: NPE only on CUDA
* Nd4jTest.testNpyByteArray: NPE only on CUDA
* DataBufferTests.testNoArgCreateBufferFromArray() - crashing on CI only? https://gist.github.com/AlexDBlack/28e1cb9c720c1798b4a4b44338449025

Numpy reading NPEs also causing issues for Keras import on CUDA.

macosx-x86_64-cpu
* `JVM crash: test[reductions/count_nonzero_all](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`
* Later run: JVM crash on `[losses/huber_diff_rank2_axis1_SUM_BY_NONZERO_WEIGHTS](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`

macosx-x86_64-cpu-avx2
* JVM crash: `test[losses/mse_rank2_weights_1](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`

windows-x86_64-cuda-9.2
* `testOutputOnly[conv_4](org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff)`: output: 1 values exceed maxRelError=0.001 with minAbsError=1.0E-5; largest observed relError=0.0017903551924973726 expected:<0> but was:<1>
* `testOutputOnly[g_09](org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff)`: Predictions do not match on g_09, node output_1
* `test[conv_4](org.nd4j.imports.TFGraphs.TFGraphTestAllLibnd4j)`: output: 1 values exceed maxRelError=0.001 with minAbsError=1.0E-5; largest observed relError=0.0017903551924973726 expected:<0> but was:<1>
- Plus: most of same issues as linux-x86_64-cuda-9.2
**Plus another 76 failures** - `Cannot allocate...` and `Physical memory usage is too high`
- Yet: a more recent run had no memory issues...

Alex's local Kubuntu/5930k box (native backend):
JVM crash on TFGraphTestAllLibnd4j:
https://gist.github.com/AlexDBlack/5820f6a108603ac39400f5f81023c608
Possibly related to other TFGraphTestAllLibnd4j crashes.
Seems to pass in isolation (run 4 times), fails consistently when run as part of suite (4 runs)

### nd4j-test-tensorflow

linux-x86_64-cuda-9.2: 
* `java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path` - https://gist.github.com/AlexDBlack/53fb188013a02e39897986177914a8b9

### nd4j-cuda
* AllocatorTest - getting stuck on CI

### nd4j-parameter-server-client

linux-x86_64
* ParameterServerClientTest.testServer() - Intermittent failures - 1 failure out of about 8 runs on CI - https://gist.github.com/AlexDBlack/fcad95b87c3a7914b048891e9d511987

### nd4j-parameter-server-node

linux-x86_64-cuda-9.2:
* `NetworkOrganizerTest.testNetTree6` - intermittent issue or flaky test: passes in most runs, failed it at least one: https://gist.github.com/AlexDBlack/31f58a81aa104c6e51bb0e08cec3a82d

linux-x86_64 and -cuda-9.2:
* `ParameterServerClientPartialTest.testServer` - intermittently failing on CPU and CUDA (previous runs - passed) - https://gist.github.com/AlexDBlack/f25e71e12d43300ba0cea56744f933b0

Generall: MestOrganizerTest: Produces a *ton* of log spam

### datavec-python

linux-x86_64-cpu, -cuda-9.2
* CI not set up to use python? https://gist.github.com/AlexDBlack/ccbe696d9d2921460fe848ef232d0f33
    - As of 2019/05/18 - tests are now all timing out (timeouts added to stop tests getting stuck) - https://gist.github.com/AlexDBlack/ad386c5921171b5b3d476ce0c502e10a

### datavec-local

linux-x86_64-cpu, -cuda-9.2
* ExecutionTest.testPythonExecutionNdarray:272 ? Runtime java.lang.RuntimeExcept...

Very likely due to same Python setup issue as before

### datavec-spark_2.10

linux-x86_64-cpu, -cuda-9.2
* ExecutionTest.testPythonExecution:261->Object.wait:502->Object.wait:-2 ? TestTimedOut
* ExecutionTest.testPythonExecutionWithNDArrays:306 ? Spark Job aborted due to s...

Same sort of Spark failures as datavec-python

### deeplearning4j-nn

linux-x86_64-cpu
* IndexedTailTest.testMultiThreaded_1:282 Failed for reader [0] expected:<50005000> but was:<50004815>
    - Looks like: this one not failing on every run, only some
* SmartFancyBlockingQueueTest.testSFBQ_3:184->Object.wait:-2 ? TestTimedOut test...
* SmartFancyBlockingQueueTest.testSFBQ_5:344->Object.wait:-2 ? TestTimedOut test...

Timeouts: Looks like legitimate issue (stays stuck no matter how long)

linux-x86_64-cuda-9.2 (as above, plus - at least sometimes):
* EncodedGradientsAccumulatorTest.testStore1:55 ? OutOfMemory Cannot allocate ne...
* SmartFancyBlockingQueueTest.testSFBQ_1:43 ? OutOfMemory Cannot allocate new Fl...

### deeplearning4j-core

linux-x86_64
* BarnesHutTsneTest.testCorrectness1 - https://gist.github.com/AlexDBlack/a6502b36bd1f172b3dbfb1637ce9e9fc

Also failing locally (Windows native)

### nearestneighbor-core

linux-x86_64-cpu
* ~~RandomProjectionLSHTest.testANNSearchReflexive:202 Expected one search result to be the query~~

### deeplearning4j-ui-model

linux-x86_64-cuda-9.2
* TestStatsStorage.testFileStatsStore:224 ? UnsatisfiedLink org.sqlite.core.Nati...
* TestStatsStorage.testStatsStorage:69 ? UnsatisfiedLink org.sqlite.core.NativeD...

CUDA only issue... fine locally, fine on CPU

### dl4j-spark

linux-x86_64-cpu
* One run only: TestSparkComputationGraph just stuck (never seen this when running locally) - https://gist.github.com/AlexDBlack/8de649e93060352b50e9a33b4862eec3

One run:
* MLLIbUtilTest>BaseSparkTest.before:64 ? OutOfMemory Cannot allocate new IntPoi...
* TestRepartitioning>BaseSparkTest.before:64 ? OutOfMemory Cannot allocate new I...

### deeplearning4j-nlp

linux-x86_64
* BertWordPieceTokenizerTests.testBertWordPieceTokenizer3, 5 - https://gist.github.com/AlexDBlack/1db34db26a14b127f8bdb0c0f5ee93fd
These look like character encoding issues that are already fixed on dev branch.

linux-x86_64-cuda-9.2
* ParagraphVectorsTest.testParagraphVectorsModelling1 (expected/actual difference)

### dl4j-spark-parameterserver

linux-x86_64-cpu, -cuda-9.2
* GradientSharingTrainingTest.differentNetsTrainingTest:273 ? Spark Job aborted ...
* GradientSharingTrainingTest.testEpochUpdating:346 ? Spark Job aborted due to s...
* GradientSharingTrainingTest.trainSanityCheck:169 ? Spark Job aborted due to st...

### dl4j-spark-nlp-java8_2.11

linux-x86_64-cuda-9.2
* SparkWord2VecTest.testStringsTokenization1:86 ? Runtime java.lang.RuntimeExcep...

### deeplearning4j-modelexport-solr

linux-x86_64-cuda-9.2
```
Tests in error: 
org.deeplearning4j.nn.modelexport.solr.handler.ModelTupleStreamIntegrationTest.org.deeplearning4j.nn.modelexport.solr.handler.ModelTupleStreamIntegrationTest
  Run 1: ModelTupleStreamIntegrationTest>SolrTestCaseJ4.assertNonBlockingRandomGeneratorAvailable:2703->Assert.assertFalse:64->Assert.assertTrue:41->Assert.fail:88 SecureRandom algorithm 'NativePRNG' is in use by your JVM, which is a potentially blocking algorithm on some environments. Please report the details of this failure (and your JVM vendor/version) to solr-user@lucene.apache.org. You can try to run your tests with -Djava.security.egd=file:/dev/./urandom or bypass this check using -Dtest.solr.allowed.securerandom=NativePRNG as a JVM option when running tests.
  Run 2: ModelTupleStreamIntegrationTest>SolrTestCaseJ4.teardownTestCases:313 ? NullPointer
```

Unable to reproduce locally (Windows 10 + CUDA 10.1)
Should be fixed: https://github.com/deeplearning4j/deeplearning4j/pull/7768

### deeplearning4j-nearestneighbor-server

linux-x86_64-cpu, -cuda-9.2
* NearestNeighborTest.testNearestNeighbor:63 expected:<2> but was:<1>

### deeplearning4j-cuda-9.2

linux-x86_64-cuda-9.2
* ~~TestConvolution.validateXceptionImport:217 block5_sepconv1_bn expected ...~~
Ignore added here: https://github.com/deeplearning4j/deeplearning4j/pull/7768
Logged issue here: https://github.com/deeplearning4j/deeplearning4j/issues/7766

### deeplearning4j-modelimport (keras import)

linux-x86_64-cuda-9.2 (passes on CPU)
* FullModelComparisons.cnnBatchNormLargerTest, .cnnBatchNormTest, .lstmTest - https://gist.github.com/AlexDBlack/fb8cbc68c7160f95f7d22ddff89d96f2

### deeplearning4j-zoo

linux-x86-64
* TestInstantiation.testInitRandomModelSqueezenet - JVM crash https://gist.github.com/AlexDBlack/47a8e7707077819c1c51a310ecea6d6f
* TestInstantiation.testInitRandomModelUNet - JVM crash https://gist.github.com/AlexDBlack/de710e878531eb5da01eec8a8b6701b7

linux-x86-64_cuda-9.2
* JVM crash - TestInstantiation.testInitPreprtrainedDarknet19 or ...Darknet19S2 - https://gist.github.com/AlexDBlack/321f232c42b25c636f2f779b2e45a66d
* JVM crash - TestInstantiation.testCnnTrainingYOLO2 - https://gist.github.com/AlexDBlack/d159bd9224f8271000726f07e0d353bc
* JVM crash - TestInstantiation.testInitPretrainedXception - https://gist.github.com/AlexDBlack/f3774775a33f5d92a47a84a520359dc7
* Test failure: TestImageNet.testDarknetLabels - only seen in 1 CI (CUDA) run so far - might be intermittent, or might have been hidden by JVM crashes - https://gist.github.com/AlexDBlack/ef7b431b45df52cc33729c5a53b4c02a

**NOTE: Zoo TestInstantiation test completely ignored on CI now due to too many JVM crashes**

All tests are fine locally (Windows, CPU/CUDA) - no crashes/failures seen other than on CI machines.

### dl4j-perf

linux-x86_64
* 3 failures on CI only, probably due to GLibC versions? 
https://gist.github.com/AlexDBlack/d6014801ad033d1f19ed1d25c3cad513
https://github.com/oshi/oshi/issues/338

### nd4s

linux-x86_64-cpu
* Tests: succeeded 41, failed 4, canceled 0, ignored 6, pending 0

**Comment by AlexDBlack** [comment]
This is partly blocked by test resources changes (other than those already logged known issues that will mainly be fixed by others at this point).

I'm seeing persistent issues with certain test resources not being found (when running tests on CI), even though they definitely exist and are correct path etc. I'm about 95% sure this is the 4GB JAR problem we've seen before.

**Comment by agibsonccc** [comment]
Closed out of date
