### ISSUE TITLE
Matrix multiplication with scalar result does not preserve DataType

### ISSUE THREAD

**Issue by DrChainsaw** [eclipse/deeplearning4j#7674]
#### Issue Description

The following testcase fails in beta4 using both CPU and CUDA 10 backend:

    @Test
    public void mmulToScalar() {
        final INDArray arr1 = Nd4j.create(new float[] {1,2,3}).reshape(1,3);
        final INDArray arr2 = arr1.reshape(3,1);
        assertEquals("Incorrect type!", DataType.FLOAT, arr1.mmul(arr2).dataType());
    }

Reason is that this case is handled using Nd4j.getBlasWrapper().dot which returns a double:
``` 
if (result.isScalar())
            return Nd4j.scalar(Nd4j.getBlasWrapper().dot(this, other)).reshape(1, 1);
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* platform information (OS, etc): Windows 10
* CUDA version, if used: 10
* NVIDIA driver version, if in use: CBA to look it up. Shouldn't matter...

#### Contributing

I guess fixing this is trivial.

**Comment by raver119** [comment]
I'm not convinced that's a bug. dot() intentionally returns `double`. Nd4j.scalar() intentionally creates `double` scalar out of `double` primitive.

Want to inherit array datatype? Use Dot op.

**Comment by raver119** [comment]
In general, this issue just raises another question: where we want to draw a line between primitives and INDArray data types.

**Comment by AlexDBlack** [comment]
No, this is definitely a bug. The return type of mmul should always match the arg types regardless of input shapes; it doesn't here because of the java shortcut to use dot (which is an internal detail here).

**Comment by alexanderst** [comment]
Implemented in dev branch.
