### ISSUE TITLE
SameDiff: Check TF import datatypes, add UINT type tests

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7721]
We should be able to import uint types just fine, but I don't see any tests for these...

https://github.com/deeplearning4j/TFOpTests/search?q=uint8&unscoped_q=uint8

We should add some more import tests to ensure we have all supported dtypes in import unit tests.

**Comment by raver119** [comment]
And BFLOAT16

**Comment by AlexDBlack** [comment]
Added a while ago.
