### ISSUE TITLE
NL4J: threads failing to stop

### ISSUE THREAD

**Issue by imod** [eclipse/deeplearning4j#7737]
#### Issue Description

We use NL4J to do predictions based on a pretrained keras model. We do this from within tomcat (via spring boot). This is working fine, but the Tomcat shutdown does take quite a while because of threads failing to stop. The messages we get while tomcat shutsdown are these:

```
May 15, 2019 7:08:07 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8080"]
May 15, 2019 7:08:07 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Tomcat]
May 15, 2019 7:08:07 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [JavaCPP Deallocator] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.bytedeco.javacpp.Pointer$DeallocatorThread.run(Pointer.java:302)
May 15, 2019 7:08:07 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [Workspace deallocator thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.nd4j.linalg.memory.provider.BasicWorkspaceManager$WorkspaceDeallocatorThread.run(BasicWorkspaceManager.java:292)
May 15, 2019 7:08:07 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [NativeRandomDeallocator thread 0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.nd4j.rng.deallocator.NativeRandomDeallocator$DeallocatorThread.run(NativeRandomDeallocator.java:96)
May 15, 2019 7:08:07 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8080"]
May 15, 2019 7:08:07 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8080"]
```

as you can see, there are three different threads causing issues, these are: 
- NL4J: "Workspace deallocator thread"
- NL4J: "NativeRandomDeallocator thread 0"
- JavaCPP: "JavaCPP Deallocator"

I understand this might not be an issue in many cases but **it really hurts while doing local development and does not give a good feeling about resource handling in general**.

If it is not possible to fix this in an easy way, please provide a way to shutdown these threads  programmatically. This would allow to easily solve the issue with the help of some application lifecycle handler by the application itself.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta3
* platform information (OS, etc): mac

#### Contributing

If you have an idea how to tackle this, please let me know - would love to fix it the way you want it.

**Comment by raver119** [comment]
Please update to 1.0.0-beta4. All these issues should'be been resolved there.

**Comment by imod** [comment]
wow @raver119 that was a really fast reply  - many thanks!!!  🥇 👍  🙏 

i just did the update and checked the shutdown again. Indeed, two of the warnings are gone, but one still remains: `JavaCPP Deallocator`

```
WARNING: The web application [ROOT] appears to have started a thread named [JavaCPP Deallocator] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.bytedeco.javacpp.Pointer$DeallocatorThread.run(Pointer.java:303)
```

**Comment by raver119** [comment]
cc @saudet

**Comment by imod** [comment]
I did an other test, but before I come up with the result, I have to explain or "setup"... 
As explained before, we import a trained keras model and use it for prediction, to do so, we do not need a lot of the transitive dependencies which DL4J normally brings.

To reduce the size of our deployed application, we exclude as much as possible (which is quite a pain with DL4J).

With our reduced set of dependencies, I get the last warning above (`JavaCPP Deallocator` which is not shutting down properly).

But now I also did a test where I do no excludes on the dependencies and what I get now is this:

```
May 15, 2019 9:31:08 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8090"]
May 15, 2019 9:31:08 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Tomcat]
May 15, 2019 9:31:08 AM org.apache.catalina.core.ApplicationContext log
INFO: Destroying Spring FrameworkServlet 'dispatcherServlet'
May 15, 2019 9:31:08 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [DeallocatorServiceThread_0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:117)
May 15, 2019 9:31:08 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [DeallocatorServiceThread_1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:117)
May 15, 2019 9:31:08 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8090"]
May 15, 2019 9:31:08 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8090"]
```
So it actually gets worse again. We now have two threads which fail to stop properly. 

Looking at the source at https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/memory/deallocation/DeallocatorService.java#L68 I see this threads do get started, but there is no way to stop the threads. 

Also, there are multiple places where an `InterruptedException` is thrown, but there is no call to `Thread.currentThread().interrupt()` when this happens, e.g. https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/memory/deallocation/DeallocatorService.java#L108

**Comment by raver119** [comment]
Upon interruption thread will exit loop and die gracefully. But yea, tagging won't hurt.

**Comment by saudet** [comment]
Those are deamon threads, they can't prevent the JVM from terminating. What
are your Tomcat processes waiting on exactly?

**Comment by imod** [comment]
no idea, I just start tomcat and don't even do a prediction. but it is reproducible every single time

**Comment by raver119** [comment]
Can you make threads dump with jstack?

**Comment by imod** [comment]
I'm off now for a day, but sure will try on friday

**Comment by saudet** [comment]
Maybe we just need to call `Thread.setContextClassLoader(null)` as suggested on this page:
    https://wiki.apache.org/tomcat/MemoryLeakProtection
@imod Could you give this a try see what happens?

**Comment by imod** [comment]
@saudet sure I can, do you already have a SNAPSHOT build I can use?

**Comment by imod** [comment]
@saudet @raver119 I have tried to build the sources by myself, but unfortunate I was not able to find a figure out a working maven command :( ...I'm running on a mac, maybe you have a command handy which I can use to build it?

**Comment by saudet** [comment]
The usual `mvn clean install` works just fine. Anyway, I've updated JavaCPP accordingly in commit https://github.com/bytedeco/javacpp/commit/655dae21833119a0edd45e1a16dbaa2e585d6455 so give it a try with 1.5.1-SNAPSHOT: http://bytedeco.org/builds/

**Comment by imod** [comment]
sorry, I'm really not a maven newby, but I don't get this to work, not all the SNAPSHOT dependencies seem available...

to simply just test the dependencies (and nothing of my project), I created a new `pom.xml` as follows:

```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" 
    xmlns="http://maven.apache.org/POM/4.0.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>ml</artifactId>
    <groupId>fortysix</groupId>
    <version>0.1-SNAPSHOT</version>
    <name>ml</name>
    <properties>
    </properties>
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-beta4</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-beta4</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-modelimport</artifactId>
            <version>1.0.0-beta4</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.1.0-1.5.1-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>

```

If I run `mvn clean install -DskipTests -U`, then I get this:

```
[ERROR] Failed to execute goal on project ml: Could not resolve dependencies for project fortysix:ml:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:opencv:jar:android-x86_64:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:ios-arm64:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:ios-x86_64:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:linux-x86:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:linux-x86_64:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:linux-armhf:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:macosx-x86_64:4.1.0-1.5.1-SNAPSHOT, org.bytedeco:opencv:jar:windows-x86_64:4.1.0-1.5.1-SNAPSHOT: Could not find artifact org.bytedeco:opencv:jar:android-x86_64:4.1.0-1.5.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
```


ok, so let's follow the advice and only get the stuff I currently need: `mvn clean install -DskipTests -U -Djavacpp.platform=macosx-x86_64`

still, it fails:

```
[ERROR] Failed to execute goal on project ml: Could not resolve dependencies for project fortysix:ml:jar:0.1-SNAPSHOT: Could not find artifact org.bytedeco:opencv:jar:macosx-x86_64:4.1.0-1.5.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
```

I also checked manually and there is no `opencv-4.1.0-1.5.1-SNAPSHOT-macosx-x86_64.jar` at https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/opencv/4.1.0-1.5.1-SNAPSHOT/ 

what am I doing wrong?

**Comment by saudet** [comment]
This has nothing to do with OpenCV. I only modified how the thread is started in JavaCPP, no need to try to import anything else.

**Comment by imod** [comment]
@saudet I think this is not yet the fix we are looking for... Please have a close look at the stacktrace:

```
WARNING: The web application [ROOT] appears to have started a thread named [DeallocatorServiceThread_0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:117)
May 20, 2019 4:30:45 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [DeallocatorServiceThread_1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.2/java.lang.Object.wait(Native Method)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 app//org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:117)
May 20, 2019 4:30:45 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8090"]
```

its not `org.bytedeco.javacpp.Pointer.DeallocatorThread`, but `org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread`

**Comment by saudet** [comment]
Ok, so it works for `Pointer$DeallocatorThread`, so let's do the same for `DeallocatorService$DeallocatorServiceThread` @alexanderst

**Comment by alexanderst** [comment]
DeallocatorServiceThread tagging done. Will be merged soon.

**Comment by alexanderst** [comment]
@raver119 Fix was implemented.
