### ISSUE TITLE
multi-gpu support for Arbiter

### ISSUE THREAD

**Issue by daanvdn** [eclipse/deeplearning4j#7773]
Creating this issue as per @agibsonccc's request
 
Regarding **Arbiter**

To my understanding there is currently no support for using arbiter in a distributed manner with spark: the only implementation of `org.deeplearning4j.arbiter.optimize.runner.IOptimizationRunner` is `org.deeplearning4j.arbiter.optimize.runner.LocalOptimizationRunner`, which is confined to a single machine. It seems however that this implementation is further confined to just 1 gpu/cpu. It would be very useful to have a variant of the `LocalOptimizationRunner` that can leverage **all** the gpus of a single machine, much like the `org.deeplearning4j.parallelism.ParallelWrapper` does. 

dl4j version: 1.0.0-beta3

**Comment by AlexDBlack** [comment]
It supports multiple threads, and hence multiple tasks - via constructor maxConcurrentTasks.
The only concern here - if there is a concern at all - is thread/device affinity.
By default threads get associated with devices on a round-robin basis - which should work fine in most cases.

**Comment by daanvdn** [comment]
@AlexDBlack so if there is no mechanism to do gpu/cpu pinning, does that mean that for instance setting `maxConcurrentTasks` to the number of gpus/cpus (e.g. 4) might cause runtime errors? Or does it simply mean that maximal leverage of all cpus/gpus simply cannot be guaranteed?

**Comment by AlexDBlack** [comment]
Under normal circumstances it should do exactly what you expect.
4 concurrent tasks on 4 GPUs should result in 1 model per thread, and should run perfectly fine, using all devices fully (independently).
I say *should* in that it we're relying on default round-robin thread-device affinity for this, not manually assigning threads to devices. I can't think where the former would go wrong, but the latter should be safer.

**Comment by daanvdn** [comment]
thanks for the explanation @AlexDBlack. I'll run some experiments and report back if I see any errors.
