### ISSUE TITLE
DL4J Keras Import: Merge Vertex InputType issue

### ISSUE THREAD

**Issue by Arpit-Mittal** [eclipse/deeplearning4j#7817]
Steps to reproduce issue

ComputationGraph graph = KerasModelImport.importKerasModelAndWeights(
                "iris_model_json",
                "ml_model_save");
[modelweightsandjson.zip](https://github.com/deeplearning4j/deeplearning4j/files/3242640/modelweightsandjson.zip)

In java, deeplearning4j is not able to load model? Could you tell us solutions to solve this problem? I  got below error:
InvalidInputTypeException: Invalid input: MergeVertex cannot merge activations of different types: first type = RNN, input type 2 = FF

**Comment by Arpit-Mittal** [comment]
Below are steps to reproduce:

ComputationGraph graph = KerasModelImport.importKerasModelAndWeights(
         "/Users/armittal/thai-implementation/thai-romanization/model/thai2rom-v2.hdf5");
      
thai2rom-v2.hdf5 is present in   modelWeights folder.
[modelWeights.zip](https://github.com/deeplearning4j/deeplearning4j/files/3239496/modelWeights.zip)

iris_model_json and ml_model_save are present in modelweightsandjson.

ComputationGraph graph = KerasModelImport.importKerasModelAndWeights(
"/Users/armittal/thai-implementation/thai-romanization/iris_model_json",
"/Users/armittal/thai-implementation/thai-romanization/ml_model_save");
}
[modelweightsandjson.zip](https://github.com/deeplearning4j/deeplearning4j/files/3239505/modelweightsandjson.zip)

**Comment by Arpit-Mittal** [comment]
In loading model through java, it is reporting errors. Please debug it tell me solution? I have attached steps to reproduce scenario. How can I use the keras model in java to do prediction? Are there any examples that you can share to me to solve this problem? 

I have attached python code above which is creating the model. If I load model through python it works ok. But I want to do it in java.

**Comment by Arpit-Mittal** [comment]
Any updates on this?

**Comment by Arpit-Mittal** [comment]
Let me know if you need additional information?

**Comment by Arpit-Mittal** [comment]
Please tell us solutions to solve this problem?

**Comment by Arpit-Mittal** [comment]
Below are the models that were used:

https://github.com/keras-team/keras/tree/master/examples  lstm_seq2seq.py Trains a basic character-level sequence-to-sequence model. lstm_seq2seq_restore.py Restores a character-level sequence to sequence model from disk (saved by lstm_seq2seq.py) and uses it to generate predictions.

**Comment by Arpit-Mittal** [comment]
Please help us how the inference for above models can be done using deepLearning4j? It works in python not in java.

**Comment by raver119** [comment]
No need spamming. As soon as updates available - you'll be notified.

**Comment by agibsonccc** [comment]
Closing, not relevant anymore.
