### ISSUE TITLE
ND4J: Fix/replace uses of Nd4j.sizeOfDataType()

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7826]
Nd4j.sizeOfDataType() is the size of the default datatype. Most places using this that I can see should be getting size from the relevant array datatype instead.

![image](https://user-images.githubusercontent.com/2360237/58743396-be47e900-8473-11e9-9700-d9d0c6a0f32a.png)

**Comment by alexanderst** [comment]
Implemented in dev branch.
