### ISSUE TITLE
one-row or one-column matrix not accepted as matrix

### ISSUE THREAD

**Issue by lpaatero** [eclipse/deeplearning4j#7839]
#### Issue Description

I have NDArray matrix of dimensions n x 100, where n may have values 1...100.

Attempt to call toFloatMatrix() fails with exception 

>       org.nd4j.linalg.exception.ND4JIllegalStateException: Unable to create a 2d array from a non matrix! Shape: FLOAT,[1,100],c

when n=1, but works for all other matrix dimensions.

My expectation is that any of n=1...100 would be acceptable dimension for matrix.

From source it seems that isMatrix has (unexpected) requirement that neither of matrix dimensions must be 1. Still one-row or one-column matrix is common case. 

Note that functions rows() and columns() have special handling, that allows them to get rows or columns of one-row or one-column matrix.

#### Version Information

* current git version.

**Comment by AlexDBlack** [comment]
Thanks for reporting. This is definitely a bug.
