### ISSUE TITLE
DL4J/NLP: Add WordVectors.outOfVocabSupported(), use in CnnSentenceDataSetIterator

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7858]
CnnSentenceDataSetIterator uses WordVectors.hasWord(String) here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/CnnSentenceDataSetIterator.java#L204

But for vector methods like FastText that support out-of-vocabulary vectors, there's no point calling this method.

Instead, let's add `WordVectors.outOfVocabSupported()` method, and change iterator condition to:
`if (!wordVectors.outOfVocabSupported() && !wordVectors.hasWord(token)) {`

**Comment by alexanderst** [comment]
Fixed on branch, will be merged soon.

**Comment by alexanderst** [comment]
FastText has supervised mode, so I assume it doesn't support out of vocabulary. I'm not sure if it's significant, but we defined outOfVocabulary = true for FastText and it might be wrong for this code:

val fastText = FastText.builder().supervised(true).build();
fastText.fit();

**Comment by alexanderst** [comment]
Implemented and merged.

**Comment by alexanderst** [comment]
Yes, CnnSentenceDataIterator.java L204, but looks like the fix is still on dev branch.

**Comment by AlexDBlack** [comment]
https://github.com/eclipse/deeplearning4j/blob/1170827c18005aa9dc7e6f0550964a4e4a6afcf2/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/CnnSentenceDataSetIterator.java#L204
