### ISSUE TITLE
ND4J: Review/fix ByteBuffer methods (Java 9 build, Java 8 exec)

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7888]
Here's something I ran into today (SameDiff UI - LogFileWriter) that might impact things in other places:
`
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer
`
Turns out if you build on Java 9, run on Java 8, and use ByteBuffers you can run into this.

This is apparently a well-known issue:
https://github.com/apache/felix/pull/114
https://www.google.com/search?q=java+9+buffer+NoSuchMethodError

ND4J is the main place that uses ByteBuffers, though we should check other libraries too.

> The solution is to cast ByteBuffer instances to Buffer before calling the method.

(From PR above)

**Comment by saudet** [comment]
There are other similar issues that pop up here and then. The only way to ensure that it will work with JDK 7 is to compile it with JDK 7.
