### ISSUE TITLE
INDArray equals but have different hashcode

### ISSUE THREAD

**Issue by csxiang18** [eclipse/deeplearning4j#7894]
How can I remove duplicate rows for matrix?
When I use hash set to store INDArray rows, I found that it can not remove duplicate rows. As even though two INDArray x.equals(y) is true, they have different hash code.

Can anyone explain why INDArray have this feature?

For example:

    INDArray x = Nd4j.zeros(5);
    INDArray y = Nd4j.zeros(5);
    System.out.println(x.equals(y)); // this return true
    System.out.println(x.hashcode());
    System.out.println(y.hashcode());  // two INDArray have different hash code.

**Comment by raver119** [comment]
We intentionally don't provide hashCode() for INDArray, since it single integer value has very little sense in case of floating point Tensors. 

And equals() isn't actually regular equals(). It's equalsWithEps.

**Comment by raver119** [comment]
I mean: say you have typical 3D array that represents image. 3, 244, 244. That's 178608 values. Do you REALLY want to have single integer value that kind of "represents" it?

**Comment by csxiang18** [comment]
Yeah, but when I need to find duplicate images in my dataset, this could be useful. As what I need is only a hashSet, which can implement my feature easily.

**Comment by saudet** [comment]
@raver119 equals() would now make sense for integer data types, so hashes would now be useful too.

**Comment by AlexDBlack** [comment]
The big problem with hashcodes on NDArray (regardless of datatype) is that NDArrays are mutable. Put a mutable array into a hashset/hashmap and you'll have a bad time if the array is changed in any way...

**Comment by raver119** [comment]
Well, hypothetically we can add parallelized hashCode()-like operation to libnd4j, which would be invoked in INDArray.hashCode(). But as @AlexDBlack already mentioned arrays are mutable...

Maybe we should just add it, and say out VERY loud that we do not recommend doing that ever?

**Comment by AlexDBlack** [comment]
Yeah, I think I'd be OK with that. It'll be useful for some use cases, like lookup tables where INDArray is key.
And people can misuse INDArrays (mutable array in hashmap/hashset etc) even now.

Hash would also be quite nice for some other use cases, like detecting array changes for testing purposes, etc.

**Comment by raver119** [comment]
Implemented, should be ok now. However, collisions should be expected.
