### ISSUE TITLE
libnd4j: Unable to build via maven (mkldnn conv3d signature issues)

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7896]
This started post CUDA branch merge (it was seen on the CUDA branch, but not on master before merging).

Tested on current master, Windows 10. Build using `buildnativeoperations.sh -c cpu -a native` works fine.

https://gist.github.com/AlexDBlack/e56260ae4fbeacb4d4a0f3248700d538

**Comment by raver119** [comment]
Fixed in dev branch, will be merged later
