### ISSUE TITLE
Out of memory in training a model

### ISSUE THREAD

**Issue by montardon** [eclipse/deeplearning4j#7900]
[outOfMemory.txt](https://github.com/deeplearning4j/deeplearning4j/files/3281536/outOfMemory.txt)
#### Issue Description

I import an untrained  Keras model of ResNet20 on Cifar10.
I train my model on 200 epochs.
After about 90 epochs, I get an out of memory error.

#### Version Information

* Deeplearning4j version: 1.0.0-beta4
* platform information (OS, etc): Ubuntu 18.0.2
* CUDA version, if used: CUDA 10.0
* NVIDIA driver version, if in use: 418.67

#### Contributing
Training code
https://gist.github.com/montardon/17b9962718592aa595c891f001a836fe
Model
[model_cifar10_ResNet20v1.zip](https://github.com/deeplearning4j/deeplearning4j/files/3281531/model_cifar10_ResNet20v1.zip)

Give path to model as program argument.

**Comment by montardon** [comment]
I used YourKit Java Profiler while training the model. Heap memory keeps growing.

![Capture d’écran de 2019-06-12 16-45-35](https://user-images.githubusercontent.com/238749/59361957-fc29f480-8d32-11e9-9e0e-abb166457e06.png)
![Capture d’écran de 2019-06-12 16-55-48](https://user-images.githubusercontent.com/238749/59361987-08ae4d00-8d33-11e9-871b-45f8630067cb.png)

**Comment by raver119** [comment]
So, all out of suddent that's not a real leak.
Problem appears only if gc pressure is small enough, and full gc is never performed. In this case thread (and workspace attached to that thread) is never removed by gc, and memory stacks up.

Once gc kicks in - everything is released properly. 
Problem appeared in beta4 due to 2 changes
1) periodic gc calls were disabled by default
2) we've reduced amount of on-heap objects used by nd4j objects. 

Obvious temporary workaround - add System.gc() call within your epoch loop. Or enable periodic gc.

**Comment by raver119** [comment]
Another workaround - wrap your iterator with AsyncShieldDataSetIterator.  But i'd recommend not to, and stick to other two workarounds.

**Comment by saudet** [comment]
It's also possible that the system is having a hard time deallocating native memory for some reason. This typically happens on Windows, but in any case, increasing "org.bytedeco.javacpp.maxretries" to something crazy like 1000 should avoid giving up too fast:
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxRetries

**Comment by montardon** [comment]
I found this dump in IntelliJ project tree. May be it can help you.
[dl4j-memory-crash-dump-1560283133783_1.txt](https://github.com/eclipse/deeplearning4j/files/3320798/dl4j-memory-crash-dump-1560283133783_1.txt)

**Comment by raver119** [comment]
Few comments above i've already explained what's wrong and what are the possible workarounds
