### ISSUE TITLE
JVM Crash on RNN basic test rebuild

### ISSUE THREAD

**Issue by thomas-trendsoft** [eclipse/deeplearning4j#7917]
#### Issue Description
i tried to rebuild a rnn with the BasicRNNExample file and try to use it with word vectors to mark some part of the sentence. the basic source is :
```java
package rnn.app;

import java.io.FileNotFoundException;
import java.util.List;

import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.word2vec.Word2Vec;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration.ListBuilder;
import org.deeplearning4j.nn.conf.layers.LSTM;
import org.deeplearning4j.nn.conf.layers.RnnOutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.INDArrayIndex;
import org.nd4j.linalg.indexing.NDArrayIndex;
import org.nd4j.linalg.learning.config.RmsProp;
import org.nd4j.linalg.lossfunctions.LossFunctions.LossFunction;

public class RNNMainApp {

	// RNN dimensions
	private static final int HIDDEN_LAYER_WIDTH = 20;
	private static final int HIDDEN_LAYER_CONT = 2;
    
    public static void main(String[] args) throws FileNotFoundException {

        Word2Vec               wnet = WordVectorSerializer.loadFullModel("yourmodel");
    	int vsize = wnet.getWordVector(wnet.vocab().wordAtIndex(0)).length;
    	
    	System.out.println(vsize);
    	
		// some common parameters
		NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder();
		builder.seed(123);
		builder.biasInit(0);
		builder.miniBatch(false);
		builder.updater(new RmsProp(0.001));
		builder.weightInit(WeightInit.XAVIER);

		ListBuilder listBuilder = builder.list();

		// first difference, for rnns we need to use LSTM.Builder
		for (int i = 0; i < HIDDEN_LAYER_CONT; i++) {
			LSTM.Builder hiddenLayerBuilder = new LSTM.Builder();
			hiddenLayerBuilder.nIn(i == 0 ? vsize : HIDDEN_LAYER_WIDTH);
			hiddenLayerBuilder.nOut(HIDDEN_LAYER_WIDTH);
			// adopted activation function from LSTMCharModellingExample
			// seems to work well with RNNs
			hiddenLayerBuilder.activation(Activation.TANH);
			listBuilder.layer(i, hiddenLayerBuilder.build());
		}

		// we need to use RnnOutputLayer for our RNN
		RnnOutputLayer.Builder outputLayerBuilder = new RnnOutputLayer.Builder(LossFunction.MCXENT);
		// softmax normalizes the output neurons, the sum of all outputs is 1
		// this is required for our sampleFromDistribution-function
		outputLayerBuilder.activation(Activation.SOFTMAX);
		outputLayerBuilder.nIn(HIDDEN_LAYER_WIDTH);
		outputLayerBuilder.nOut(2);
		listBuilder.layer(HIDDEN_LAYER_CONT, outputLayerBuilder.build());

		// create network
		MultiLayerConfiguration conf = listBuilder.build();
		MultiLayerNetwork net = new MultiLayerNetwork(conf);
		net.init();
		net.setListeners(new ScoreIterationListener(1));

		/*
		 * CREATE OUR TRAINING DATA
		 */
		// create input and output arrays: SAMPLE_INDEX, INPUT_NEURON,
		// SEQUENCE_POSITION
		String                    s = "wer kommt heute noch mit zur stadt hamburg";
		TokenizerFactory         tf = new DefaultTokenizerFactory();
		
		List<String> slist = tf.create(s).getTokens();
		
		INDArray input = Nd4j.zeros(1, vsize, slist.size());
		INDArray labels = Nd4j.zeros(1, 2, slist.size());
		
		// loop through our sample-sentence
		int samplePos = 0;
		for (String p : slist) {
			INDArray v1 = wnet.getWordVectorMatrix(p);
			if (v1 == null) {
				System.out.println("unknown word: '" + p + "'");
    			v1 = wnet.getWordVectorMatrix(wnet.vocab().wordAtIndex(0));				
			}
			
			input.put(
	                new INDArrayIndex[] {
	                    NDArrayIndex.point(1), NDArrayIndex.all(), NDArrayIndex.point(samplePos)
	                },
	                v1);
			
			// output neuron for next-char is 1 at "samplePos"
			if (samplePos != 7) {
				labels.putScalar(new int[] { 0, 0 , samplePos }, 1);				
			} else {				
				labels.putScalar(new int[] { 0, 1 , samplePos }, 1);				
			}
				
			samplePos++;
		}
		
		System.out.println(input.shapeInfoToString());
		
		DataSet trainingData = new DataSet(input, labels);

		INDArray testData = wnet.getWordVectorMatrix(slist.get(0));
		INDArray testInit = Nd4j.zeros(1,vsize, 1);
		testInit.put(
                new INDArrayIndex[] {
                    NDArrayIndex.point(1), NDArrayIndex.all(), NDArrayIndex.point(1)
                },
                testData);
		INDArray output = net.rnnTimeStep(testInit);
		
		// some epochs
		for (int epoch = 0; epoch < 10; epoch++) {

			System.out.println("Epoch " + epoch);

			// train the data
			net.fit(trainingData);

			// clear current stance from the last example
			net.rnnClearPreviousState();

		}    	
    }
}
```
Please describe our issue, along with:
- expected behavior

the training should give me the epochs running (no glue if some good result)

- encountered behavior

jvm continues to crash every start time in a different way:
java(4955,0x7000021a7000) malloc: Incorrect checksum for freed object 0x7ff49f9e8c00: probably modified after being freed.
Corrupt value: 0x3a0d57613dcd2988
java(4955,0x7000021a7000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

sometimes it trains a bit but mostly not to the end.

#### Version Information

i use the 1.0-beta4 version of deeplearning4j and nd4j

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0-b4
* platform information (OS, etc)
MacOSX
* CUDA version, if used
no cuda used cpu only
* NVIDIA driver version, if in use
-

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by thomas-trendsoft** [comment]
missed to say i monitored with top the memory usage and it was about 400 mb. so i thought i is not the other bug with the memory leak.

**Comment by thomas-trendsoft** [comment]
oh sorry my nearly first try for a issue report: my java version is:
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Comment by saudet** [comment]
Do you get the same kind of behavior with the original BasicRNNExample and the original pom.xml?

**Comment by thomas-trendsoft** [comment]
no the example works fine, i tried the jdk 1.8 and 12 and both throw also an error

**Comment by saudet** [comment]
Ok, so maybe it's something in your pom.xml file. Could you show us what it looks like?

**Comment by thomas-trendsoft** [comment]
pom looks like this, the compiler version could be a little old, i can try with a newer one:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>my</groupId>
  <artifactId>RNNApp</artifactId>
  <version>0.1</version>
  
  <dependencies>
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>1.0.0-beta4</version>
  	</dependency>
	<dependency>
	    <groupId>org.deeplearning4j</groupId>
	    <artifactId>deeplearning4j-nlp</artifactId>
	    <version>1.0.0-beta4</version>
	</dependency>
  	<dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>1.0.0-beta4</version>
  	</dependency>
  </dependencies>
  
     <build>
        <plugins>
	      <plugin>
	        <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-dependency-plugin</artifactId>
	        <version>3.1.1</version>
	        <executions>
	          <execution>
	            <id>copy-dependencies</id>
	            <phase>package</phase>
	            <goals>
	              <goal>copy-dependencies</goal>
	            </goals>
	            <configuration>
	              <outputDirectory>libs</outputDirectory>
	              <overWriteReleases>false</overWriteReleases>
	              <overWriteSnapshots>false</overWriteSnapshots>
	              <overWriteIfNewer>true</overWriteIfNewer>
	            </configuration>
	          </execution>
	        </executions>
	      </plugin>
		    <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.1.1</version>
				<configuration>
				  <archive>
				    <manifest>
						<mainClass>rnn.app.RNNMainApp</mainClass>
						<addClasspath>true</addClasspath>
						<classpathPrefix>../libs/</classpathPrefix>
				    </manifest>
				  </archive>
				</configuration>
		    </plugin>
		    <plugin>
		   		<groupId>org.apache.maven.plugins</groupId>
		   		<artifactId>maven-compiler-plugin</artifactId>
		   		<version>2.3.2</version>
		   		<configuration>
		   		    <configuration>
                    	<showWarnings>true</showWarnings>
                	</configuration>
		    		<source>1.8</source>
		    		<target>1.8</target>
		   		</configuration>
		  	</plugin>	
        </plugins>
    </build>
 
</project>

**Comment by thomas-trendsoft** [comment]
same crash with comiler version 3.8.1

**Comment by saudet** [comment]
Does this happen only on Mac? Or does it happen on Linux or Windows as well?

**Comment by thomas-trendsoft** [comment]
we started on two machines the code and both process don't crash but stuck after giving the vector size println. waited about 20 minutes and on....

**Comment by thomas-trendsoft** [comment]
played a little around with the source and if i leave the init step and make the output layer size equals the input layer size then it works

**Comment by saudet** [comment]
Could you try with the snapshots, just to make sure it's not something that's already been fixed?

**Comment by thomas-trendsoft** [comment]
i tried with the snapshot repository and updated snapshot dependencies inside the pom. 
this time i get an exception:

Error: Unable to initialize main class rnn.app.RNNMainApp
Caused by: java.lang.NoClassDefFoundError: org/nd4j/linalg/learning/config/IUpdater

compiles fine but doesn't start

**Comment by saudet** [comment]
That looks like some loading issue, and the cause of this error should show up in the stack trace. Could you post the whole stack trace that you get?

**Comment by thomas-trendsoft** [comment]
were the last day out of office: the complete output is:

Error: Unable to initialize main class rnn.app.RNNMainApp
Caused by: java.lang.NoClassDefFoundError: org/nd4j/linalg/learning/config/IUpdater

no further exception trace is given.

**Comment by AlexDBlack** [comment]
@thomas-trendsoft That's almost always mixed versions (really old ND4J on classpath), a bad build, or sometimes IDE issues (especially Eclipse IDE) - not due to anything in DL4J/ND4J directly.
How exactly are you running this? (via IDE? uber-jar?) IS the pom.xml you posted earlier what you're using?

**Comment by thomas-trendsoft** [comment]
i run the program from console with java -jar target/RNNApp.jar and no other classpath variable set.

the current pom for snapshot build is: 

```<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>my</groupId>
  <artifactId>RNNApp</artifactId>
  <version>0.1</version>
  
  <repositories>
    <repository>
        <id>snapshots-repo</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>daily</updatePolicy>  <!-- Optional, update daily -->
        </snapshots>
    </repository>
</repositories>

  <dependencies>
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>1.0.0-SNAPSHOT</version>
  	</dependency>
	<dependency>
	    <groupId>org.deeplearning4j</groupId>
	    <artifactId>deeplearning4j-nlp</artifactId>
	    <version>1.0.0-SNAPSHOT</version>
	</dependency>
  	<dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>1.0.0-SNAPSHOT</version>
  	</dependency>
	<dependency>
	    <groupId>org.nd4j</groupId>
	    <artifactId>nd4j-api</artifactId>
	    <version>1.0.0-SNAPSHOT</version>
	</dependency>
  	
  </dependencies>
  
     <build>
        <plugins>
	      <plugin>
	        <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-dependency-plugin</artifactId>
	        <version>3.1.1</version>
	        <executions>
	          <execution>
	            <id>copy-dependencies</id>
	            <phase>package</phase>
	            <goals>
	              <goal>copy-dependencies</goal>
	            </goals>
	            <configuration>
	              <outputDirectory>libs</outputDirectory>
	              <overWriteReleases>false</overWriteReleases>
	              <overWriteSnapshots>false</overWriteSnapshots>
	              <overWriteIfNewer>true</overWriteIfNewer>
	            </configuration>
	          </execution>
	        </executions>
	      </plugin>
		    <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.1.1</version>
				<configuration>
				  <archive>
				    <manifest>
						<mainClass>rnn.app.RNNMainApp</mainClass>
						<addClasspath>true</addClasspath>
						<classpathPrefix>../libs/</classpathPrefix>
				    </manifest>
				  </archive>
				</configuration>
		    </plugin>
		    <plugin>
		   		<groupId>org.apache.maven.plugins</groupId>
		   		<artifactId>maven-compiler-plugin</artifactId>
		   		<version>3.8.0</version>
		   		<configuration>
		   		    <configuration>
                    	<showWarnings>true</showWarnings>
                	</configuration>
		    		<source>1.8</source>
		    		<target>1.8</target>
		   		</configuration>
		  	</plugin>	
        </plugins>
    </build>
 
</project>
```

**Comment by thomas-trendsoft** [comment]
i think my model is wrong with the different output vector got already a new model which uses one more layer to reduce the output size to the wanted classification vector size. i think the model should give a good error response on this. in the current state i get a complet jvm crash.

**Comment by thomas-trendsoft** [comment]
if it helps this is the list of the files inside the libs directory:

artoolkitplus-2.3.1-1.5.jar
byteunits-0.9.1.jar
 cloning-1.9.3.jar
 common-image-3.1.1.jar
 common-io-3.1.1.jar
 common-lang-3.1.1.jar
 commons-codec-1.10.jar
 commons-compress-1.16.1.jar
 
commons-io-2.5.jar
 commons-lang-2.6.jar
 commons-lang3-3.6.jar
 commons-math3-3.5.jar
 commons-net-3.1.jar
 datavec-api-1.0.0-SNAPSHOT.jar
 datavec-data-image-1.0.0-SNAPSHOT.jar
 
deeplearning4j-common-1.0.0-SNAPSHOT.jar
 deeplearning4j-core-1.0.0-SNAPSHOT.jar
 deeplearning4j-datasets-1.0.0-SNAPSHOT.jar
 deeplearning4j-datavec-iterators-1.0.0-SNAPSHOT.jar
 
deeplearning4j-modelimport-1.0.0-SNAPSHOT.jar
 deeplearning4j-nlp-1.0.0-SNAPSHOT.jar
 deeplearning4j-nn-1.0.0-SNAPSHOT.jar
 deeplearning4j-tsne-1.0.0-SNAPSHOT.jar
 
deeplearning4j-ui-components-1.0.0-SNAPSHOT.jar
 deeplearning4j-util-1.0.0-SNAPSHOT.jar
 deeplearning4j-utility-iterators-1.0.0-SNAPSHOT.jar
 fastutil-6.5.7.jar
 ffmpeg-4.1.3-1.5.jar
 
flandmark-1.07-1.5.jar
 flatbuffers-java-1.10.0.jar
 flycapture-2.13.3.31-1.5.jar
 freemarker-2.3.23.jar
 gson-2.7.jar
 guava-20.0.jar
 hdf5-1.10.5-1.5-linux-ppc64le.jar
 hdf5-1.10.5-1.5-linux-x86.jar
 
hdf5-1.10.5-1.5-linux-x86_64.jar
 hdf5-1.10.5-1.5-macosx-x86_64.jar
 hdf5-1.10.5-1.5-windows-x86.jar
 hdf5-1.10.5-1.5-windows-x86_64.jar
 hdf5-1.10.5-1.5.jar
 hdf5-platform-1.10.5-1.5.jar
 
imageio-bmp-3.1.1.jar
 imageio-core-3.1.1.jar
 imageio-jpeg-3.1.1.jar
 imageio-metadata-3.1.1.jar
 imageio-psd-3.1.1.jar
 imageio-tiff-3.1.1.jar
 jackson-1.0.0-SNAPSHOT.jar
 jai-imageio-core-1.3.0.jar
 
javacpp-1.5.jar
 javacv-1.5.jar
 jfasttext-0.4.jar
 jna-4.3.0.jar
 jna-platform-4.3.0.jar
 joda-time-2.2.jar
 leptonica-1.78.0-1.5-android-arm.jar
 leptonica-1.78.0-1.5-android-arm64.jar
 
leptonica-1.78.0-1.5-android-x86.jar
 leptonica-1.78.0-1.5-android-x86_64.jar
 leptonica-1.78.0-1.5-linux-armhf.jar
 leptonica-1.78.0-1.5-linux-ppc64le.jar
 leptonica-1.78.0-1.5-linux-x86.jar
leptonica-1.78.0-1.5-linux-x86_64.jar
 leptonica-1.78.0-1.5-macosx-x86_64.jar
 leptonica-1.78.0-1.5-windows-x86.jar
 leptonica-1.78.0-1.5-windows-x86_64.jar
 leptonica-1.78.0-1.5.jar
leptonica-platform-1.78.0-1.5.jar
 libdc1394-2.2.5-1.5.jar
 libfreenect-0.5.7-1.5.jar
 libfreenect2-0.2.0-1.5.jar
 librealsense-1.12.1-1.5.jar
 mkl-2019.3-1.5-linux-x86.jar
mkl-2019.3-1.5-linux-x86_64.jar
 mkl-2019.3-1.5-macosx-x86_64.jar
 mkl-2019.3-1.5-windows-x86.jar
 mkl-2019.3-1.5-windows-x86_64.jar
 mkl-2019.3-1.5.jar
 mkl-dnn-0.18.1-1.5-linux-x86_64.jar
mkl-dnn-0.18.1-1.5-macosx-x86_64.jar
 mkl-dnn-0.18.1-1.5-windows-x86_64.jar
 mkl-dnn-0.18.1-1.5.jar
 mkl-dnn-platform-0.18.1-1.5.jar
 mkl-platform-2019.3-1.5.jar
 nd4j-api-1.0.0-SNAPSHOT.jar
nd4j-buffer-1.0.0-SNAPSHOT.jar
 nd4j-common-1.0.0-SNAPSHOT.jar
 nd4j-context-1.0.0-SNAPSHOT.jar
 nd4j-jackson-1.0.0-SNAPSHOT.jar
 nd4j-native-1.0.0-SNAPSHOT-android-arm.jar
nd4j-native-1.0.0-SNAPSHOT-android-arm64.jar
 nd4j-native-1.0.0-SNAPSHOT-android-x86.jar
 nd4j-native-1.0.0-SNAPSHOT-android-x86_64.jar
 nd4j-native-1.0.0-SNAPSHOT-ios-arm64.jar
nd4j-native-1.0.0-SNAPSHOT-ios-x86_64.jar
 nd4j-native-1.0.0-SNAPSHOT-linux-armhf.jar
 nd4j-native-1.0.0-SNAPSHOT-linux-ppc64le.jar
 nd4j-native-1.0.0-SNAPSHOT-linux-x86_64.jar
nd4j-native-1.0.0-SNAPSHOT-macosx-x86_64.jar
 nd4j-native-1.0.0-SNAPSHOT-windows-x86_64.jar
 nd4j-native-1.0.0-SNAPSHOT.jar
 nd4j-native-api-1.0.0-SNAPSHOT.jar
 nd4j-native-platform-1.0.0-SNAPSHOT.jar
nearestneighbor-core-1.0.0-SNAPSHOT.jar
 neoitertools-1.0.0.jar
 objenesis-2.6.jar
 openblas-0.3.5-1.5-android-arm.jar
 openblas-0.3.5-1.5-android-arm64.jar
 openblas-0.3.5-1.5-android-x86.jar
openblas-0.3.5-1.5-android-x86_64.jar
 openblas-0.3.5-1.5-ios-arm64.jar
 openblas-0.3.5-1.5-ios-x86_64.jar
 openblas-0.3.5-1.5-linux-armhf.jar
 openblas-0.3.5-1.5-linux-ppc64le.jar
openblas-0.3.5-1.5-linux-x86.jar
 openblas-0.3.5-1.5-linux-x86_64.jar
 openblas-0.3.5-1.5-macosx-x86_64.jar
 openblas-0.3.5-1.5-windows-x86.jar
 openblas-0.3.5-1.5-windows-x86_64.jar
openblas-0.3.5-1.5.jar
 openblas-platform-0.3.5-1.5.jar
 opencsv-2.3.jar
 opencv-4.0.1-1.5-android-arm.jar
 opencv-4.0.1-1.5-android-arm64.jar
 opencv-4.0.1-1.5-android-x86.jar
opencv-4.0.1-1.5-android-x86_64.jar
 opencv-4.0.1-1.5-ios-arm64.jar
 opencv-4.0.1-1.5-ios-x86_64.jar
 opencv-4.0.1-1.5-linux-armhf.jar
 opencv-4.0.1-1.5-linux-ppc64le.jar
opencv-4.0.1-1.5-linux-x86.jar
 opencv-4.0.1-1.5-linux-x86_64.jar
 opencv-4.0.1-1.5-macosx-x86_64.jar
 opencv-4.0.1-1.5-windows-x86.jar
 opencv-4.0.1-1.5-windows-x86_64.jar
 opencv-4.0.1-1.5.jar
opencv-platform-4.0.1-1.5.jar
 oshi-core-3.4.2.jar
 oswego-concurrent-1.3.4.jar
 protobuf-java-shaded-351-0.9.jar
 protobuf-java-util-shaded-351-0.9.jar
 slf4j-api-1.7.21.jar
 snakeyaml-1.12.jar
stax2-api-3.1.4.jar
 stream-2.7.0.jar
 t-digest-3.2.jar
 tesseract-4.0.0-1.5.jar
 threadly-4.10.0.jar
 threetenbp-1.3.3.jar
 videoinput-0.200-1.5.jar
