### ISSUE TITLE
Could not read abnormally long HDF5 attribute.

### ISSUE THREAD

**Issue by Vent1narc** [eclipse/deeplearning4j#7919]
When importing a pre-trained Keras model throws the "Could not read abnormally long HDF5 attribute." exception.

Maybe increasing the buffer size in Hdf5Archive will help?

---ERROR LOG ---
https://pastebin.com/mzcXfxPn

**Comment by Vent1narc** [comment]
I am using the latest dl4j build (1.0.0-beta4).
I also saw that you increased buffer limit from 100 to 1000 in #4744 
But I might have an even larger requirement for the buffer size even though my whole model takes less space overall than the person having an issue in #4744

**Comment by AlexDBlack** [comment]
Are you able to share the model for testing?
We can in theory increase the buffer limit, though it's already 2MB for a single attribute IIRC. The JSON configuration for most entire models (not just single attributes within a model) should be in the kB range, so something seems off here...

**Comment by Vent1narc** [comment]
Unfortunately, I can't send you the model because it belongs to my company.
I will try decoding the model file and having a look at what might be wrong.
The model was saved used Keras and Keras loads the model from the file without any issues.

**Comment by AlexDBlack** [comment]
No problem, have a look at the configuration/attribute and let me know.
If there's a legitimate case for really large attributes (that we aren't aware of) the fix is simple, we can just increase the limit. But I'd like to know why it's so big so (a) we can add some tests, and (b) determine a suitable limit.

**Comment by maxpumperla** [comment]
jfyi, the current limit is just what worked in practice. It's perfectly possible that we might have to increase it. Happy to do so when we can determine a better limit.

**Comment by Vent1narc** [comment]
From the debugger view, I could see that it was trying to load the whole file into an array of bytes and then trying to make sense of what it managed to load. If it didn't recognize what it loaded it doubled the limit for the array length. The debugger also showed String s and I could see everything that it was trying to load. First, it loaded the model configuration and then started loading weight data. However, it kept loading more and more weights but the limit of 1024 * 2000 was not enough. My whole file is 35MB long which is more than 1024 * 2000 bytes. Even though the person in #4744 had a larger Keras model than I did it never got to the part of the code where it needed to load the weights because it realized that there is an unsupported layer. I believe that significantly increasing the maximum buffer size limit will fix my issue.

**Comment by Vent1narc** [comment]
From further inspecting the structure of my hdf5 file and some other example ones I found that between json configuration of the model and weights there are some 0 bytes blocks that are not in my file. I believe the way it separates json from weights is by finding that 0 bytes block. I saved my model with Keras and I believe that Keras decided not to put those blocks for some reason. So probably when trying to read json it is also grabbing weights which makes it too much data to put into a buffer.

**Comment by Vent1narc** [comment]
I will try to save my keras model json and weights separately and see if it makes it easier for dl4j to load it that way.

**Comment by Vent1narc** [comment]
After splitting weights and json, my json file was 8MB solely because of 17 lambda layers. 8MB isbigger than the limit of 2MB so that is probably the reason why it couldn't load.

**Comment by AlexDBlack** [comment]
Thanks.
Serializing lambda layers in JSON (presumably as base64 or something) makes sense as a cause for unusually large configurations.
I guess the only thing left here to do is just increase the maximum buffer size and add some unit tests...

**Comment by Vent1narc** [comment]
I was able to start loading the model by splitting the Keras output into json and weights files. However I have some other issues now. Thank You for help.

**Comment by AlexDBlack** [comment]
We'll keep this issue open until we've implemented the increased buffer size, to avoid other issues like this in the future.

**Comment by AlexDBlack** [comment]
Fixed here, will be merged into eclipse/deeplearning4j master soon: https://github.com/SkymindIO/deeplearning4j/pull/28
