### ISSUE TITLE
Performance issue on imported Keras Model

### ISSUE THREAD

**Issue by montardon** [eclipse/deeplearning4j#7920]
#### Issue Description

I am training an imported Keras model in DL4J for 200 epochs.( ResNet20 with Cifar10)
I have batch size of 125, number of iteration is 400.

I'm surprised by performance. The time taken for training is 15800s to compare with 8400s in Keras/Python.

I test on the same computer with a Quadro P1000 4Gb.

cuDNN is used both in DL4J and in Keras/Python

o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [7,0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device Name: [Quadro P1000]; CC: [6.1]; Total/free memory: [4236312576]

https://gist.github.com/montardon/81ef9ea1eab183fd7097d552c57dd6ed
https://gist.github.com/montardon/2cd79a81078522adee944a32c5ade9cb
[model_cifar10_ResNet20v1.zip](https://github.com/eclipse/deeplearning4j/files/3306246/model_cifar10_ResNet20v1.zip)

https://gist.github.com/montardon/e2570bb48bceb6b62c6bbc035c63aa3e
https://gist.github.com/montardon/9184950865e831aa130bf72631a0fe21

I'm using Java
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-beta4
* platform information (OS, etc): Ubuntu 18.04.2
* CUDA version, if used: 10.0
* NVIDIA driver version, if in use: 418.67

#### Contributing

I'd like to help.

**Comment by montardon** [comment]
Using perf tool, (coming along with linux-tools-common and linux-tools-generic packages) I generated these 2 flamegraphs.

It looks like we have a similar structure. Sampling used with perf is -F 99.
![java perf](https://user-images.githubusercontent.com/238749/60101026-43fd4280-975b-11e9-9a44-65bd33cc1b2b.png)
![python perf](https://user-images.githubusercontent.com/238749/60101032-465f9c80-975b-11e9-8a85-d28ae6ab60a9.png)

**Comment by montardon** [comment]
Seems to be the same ratio on Windows 10 with CUDA 10.1 with GeForce RTX 1080.
117s for 5 epochs with Keras/Python
280s for 5 epochs with DL4J/Java

I read the guide for benchmarking and I know that 5 epochs might not be enough.

**Comment by AlexDBlack** [comment]
Thanks for the extra info. We still haven't found the time to look at this yet, but we will.
Unfortunately those flame graphs don't help us isolate the cause... we'll need to look at this in a profiler I think.
