### ISSUE TITLE
ND4J: FlatBuffers serialization issue for String arrays

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7927]
Looks like there's some issue with serializing String arrays to/from FlatBuffers.

```
    @Test
    public void testStringSameDiffSerialization() throws Exception {

        File f = new File(testDir.newFolder(), "test.bin");

        SameDiff sd = SameDiff.create();
        INDArray arr = Nd4j.scalar("My test string here!");
        sd.constant("s", arr);
        sd.save(f, false);

        SameDiff sd2 = SameDiff.load(f, false);
        INDArray deArr = sd2.getVariable("s").getArr();
        assertEquals(arr, deArr);
    }
```

```
java.lang.AssertionError: 
Expected :"My test string here!"
Actual   :"       My test stri"
```

Looks like the problem is this Nd4j.create(Buffer, shape) call. The String array header is not being  handled correctly, based on that result, not sure that should be fixed...
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L6568

**Comment by saudet** [comment]
Maybe FlayBuffers doesn't use UTF-8 by default?

**Comment by AlexDBlack** [comment]
No, this isn't a FlatBuffers issue per-se. IIRC from looking at this, dump the INDArray buffer directly into flatbuffers as bytes, then pull it out again into a buffer to recreate the INDArray. So we're not encoding it as a String, we're encoding it as bytes.

**Comment by raver119** [comment]
Strange. We have test for it. https://github.com/SkymindIO/deeplearning4j/blob/b5f0ec072f3fd0da566e32f82c0e43ca36553f39/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/mixed/StringArrayTests.java#L88-L104

**Comment by AlexDBlack** [comment]
Might be scalar specific...
```
    @Test
    public void testBasicStrings_4a() {
        val arrayX = Nd4j.scalar("alpha");

        val fb = new FlatBufferBuilder();
        val i = arrayX.toFlatArray(fb);
        fb.finish(i);
        val db = fb.dataBuffer();

        val flat = FlatArray.getRootAsFlatArray(db);
        val restored = Nd4j.createFromFlatArray(flat);

        assertEquals(arrayX, restored);
        assertEquals("alpha", restored.getString(0));
    }
```

```
java.lang.AssertionError: 
Expected :"alpha"
Actual   :"    "
```

**Comment by raver119** [comment]
quite possible...

**Comment by raver119** [comment]
Fixed in my branch.
