### ISSUE TITLE
ElementWise error when importing keras model

### ISSUE THREAD

**Issue by PS1TD** [eclipse/deeplearning4j#7932]
I am trying to import a Keras model that was trained in PyTorch and then later converted to Keras. The model works fine in Keras.
When importing on of the layers I get an error

ElementWise vertex cannot process CNN activations of different sizes:first [channels,width,height] = [128,58,3], input 1 = [128,56,1]

I believe it has to do with the shape of tensors.
Unfortunately, I can't send my weights file.
Thank You for help.

**Comment by agibsonccc** [comment]
This is likely fixed. For anyone finding this in the future, please open a new issue with more information than this if you hope for us to reproduce it.
