### ISSUE TITLE
Unable to use UIServer

### ISSUE THREAD

**Issue by awaymeet** [eclipse/deeplearning4j#7940]
#### Issue Description

What I want to express is that UIServer cannot be use because its package name for deeplearning4j-play_2.11 is the same as that for deeplearning4j-ui-components. By default, it refers to deeplearning4j-ui-components. So we can't use org.deeplearning4j.ui.api.UIServe.

#### Version Information

1.0.0-beta4
win7 64
idea and eclipse
apache-maven-3.3.9

#### Additional Information
demo  https://github.com/awaymeet/lottery

I don't think it's a maven problem between idea and eclipse. I rely on the packages you publish to the maven repository. But you see
“org.deeplearning4j.ui.api.Component c = null;” can be used
“org.deeplearning4j.ui.api.UIServer server=null;” cannot be used

**Comment by awaymeet** [comment]
https://files.gitter.im/deeplearning4j/deeplearning4j/2W1g/3.jpg
https://files.gitter.im/deeplearning4j/deeplearning4j/eNLI/1.jpg
https://files.gitter.im/deeplearning4j/deeplearning4j/8xdp/2.jpg

**Comment by AlexDBlack** [comment]
Builds and runs fine for me in IntelliJ 2019.1 (Windows):
![image](https://user-images.githubusercontent.com/2360237/60016934-ed482800-96ca-11e9-8632-f018f7e4d299.png)


Also builds fine for me directly in Maven (3.3.9):
https://gist.github.com/AlexDBlack/a6821a83ee78898afd19fed00e3586a8

**Comment by AlexDBlack** [comment]
Only other idea I have is maybe Java version - what are you running?
Beyond that - maybe try deleting deeplearning4j-play_2.11 in your maven repository to force a re-download (perhaps it was corrupted).
That's in `C:\Users\<your_user_name>\.m2\repository\org\deeplearning4j` on windows.

**Comment by awaymeet** [comment]
The reason was found out because the dependencies in the company's internal repository had been updated. Personal computers rely on corporate internal mirroring.
When we delete it and update it, that's all.
Thank you. Thank you very much. The problem haunted us for two and a half days.

**Comment by AlexDBlack** [comment]
OK, great. I'll close this as resolved then.
