### ISSUE TITLE
Nd4j dot product behaves differently from Numpy.

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#7947]
In Numpy the dot product's behaviour is documented here:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

For 2D arrays:

a = np.arange(12).reshape(3,4)
b  = np.arange(12).reshape(4,3)
a.dot(b)

gives the matrix product as documented:
array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

	   
In Nd4J we have no javadocs for dot. But we get quite a different result for 2D Arrays:

int[] shape = {3, 4};
INDArray x = Nd4j.arange(12).reshape(shape);
int[] shape2 = {4, 3};
INDArray y = Nd4j.arange(12).reshape(shape2);

System.out.println(x);
System.out.println(y);

[[         0,    1.0000,    2.0000,    3.0000], 
 [    4.0000,    5.0000,    6.0000,    7.0000], 
 [    8.0000,    9.0000,   10.0000,   11.0000]]
[[         0,    1.0000,    2.0000], 
 [    3.0000,    4.0000,    5.0000], 
 [    6.0000,    7.0000,    8.0000], 
 [    9.0000,   10.0000,   11.0000]]

System.out.println(dot(x, y));

506.0000

For 1D arrays Numpy and Dl4J give the same result:
a = np.arange(12)
b  = np.arange(12)
a.dot(b)

506

INDArray x = Nd4j.arange(12);
INDArray y = Nd4j.arange(12);
System.out.println(dot(x, y));
506.0000

**Comment by AlexDBlack** [comment]
Numpy dot on 2d arrays is matrix multiplication:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

We follow the (much more sane IMO) design of just having 'dot' be the full array dot product reduction:
https://en.wikipedia.org/wiki/Dot_product

Obviously that should be documented in the javadoc.
Consistency with numpy is good, but IMO this isn't a good design there and I'm worried we'll break user code relying on the old behaviour too if we change it now... open to considering it further though.

**Comment by RobAltena** [comment]
That looks good. Can please you assign me and stick a 'documentation' label on this issue?

**Comment by AlexDBlack** [comment]
Done
