### ISSUE TITLE
Nd4j createFromNpyFile loads incorrect value for scalar

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#7957]
```java
@Test
public void testFromNumpy() {

    INDArray out = Nd4j.createFromNpyFile(new File("./test.npy"));
    System.out.println(out);
}
```

Loads an empty array, should load `array(1)`.

[Numpy file](https://drive.google.com/file/d/1aI9ggm4OkvSEOElS9zo3ZQaxH_bynBzK/view?usp=sharing)

This is reproducible with any numpy scalar array export (`np.save("test.npy", np.array(1))`), its not specific to this file.

**Comment by raver119** [comment]
Fixed in my branch, will be merged later.
