### ISSUE TITLE
Nd4J: isView() returns false for views.

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#7959]
#### Issue Description

The following code gives false for all 3 calls to `isView()`. Changing the data impacts all 3 arrays. Expecting to see 2 `isView()` calls return true:

        INDArray x = Nd4j.rand(3,4);
        INDArray  x2 = x.ravel();
        INDArray  x3 = x.reshape(6,2);

        x2.putScalar(5, -1.0);  //Changes array and its views.
        System.out.println( x);
        System.out.println( x2);
        System.out.println( x3);

        System.out.println( x.isView());
        System.out.println( x2.isView());
        System.out.println( x3.isView());

output:

        [[    0.8546,    0.1509,    0.0331,    0.1308], 
         [    0.1753,   -1.0000,    0.2277,    0.1998], 
         [    0.2741,    0.8257,    0.6946,    0.6851]]
         [    0.8546,    0.1509,    0.0331,    0.1308,    0.1753,   -1.0000,    0.2277,    0.1998,    0.2741,    
         0.8257,    0.6946,    0.6851]
        [[     0.8546,    0.1509], 
         [    0.0331,    0.1308], 
         [    0.1753,   -1.0000], 
          [    0.2277,    0.1998], 
         [    0.2741,    0.8257], 
         [    0.6946,    0.6851]]
        false
        false
        false

#### Version Information
1.0.0-beta4
Win 10

**Comment by raver119** [comment]
Good catch. Fixed in my branch, will be merged soon.
