### ISSUE TITLE
GetWhere is not working

### ISSUE THREAD

**Issue by fsiegfried** [eclipse/deeplearning4j#7960]
Nd4j GetWhere (nd4j version 1.0.0-beta4) seems not to work correctly on windows. (similar like on Linux, see Bug 7632)
Simple example goes like this:
INDArray a = Nd4j.ones(height,width); 
INDArray b = Nd4j.rand(height, width, 12345).muli(2).subi(1);
INDArray nSBarrier = b.getWhere(a, Conditions.equals(1.0));

Error:
choose: Number of T arguments should be positive number, but got 0 arguments
Validation error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta4-windows-x86_64-cpu/libnd4j/include/ops/declarable/impl/DeclarableOp.cpp:448 code=4() "this->validateArguments(*block)"

**Comment by raver119** [comment]
Known issue, fix is WIP. There's also another ticket open for this problem
