### ISSUE TITLE
GPU memory leak exception in 1.0.0-beta4

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#7962]
#### Issue Description

I trains LSTM net with GA. The nets were new and free frequently. Using beta4, after many generations of evolution, an exception will be thrown or a fatal error will be encountered. The operational evolutionary generation count is related to the batch size. The exceptions thrown are not necessarily the same, but they are all related to GPU memory. I added 
```
Nd4j.getMemoryManager().togglePeriodicGc(true);
Nd4j.getMemoryManager().setAutoGcWindow(500);  //used params: 5000,2000
```
but it still doesn't work.  
I guess the workspace was not completely released when the network was released.
Attachments are related exceptions and logs
[hs_err_pid1821.log](https://github.com/eclipse/deeplearning4j/files/3347756/hs_err_pid1821.log)
[hs_err_pid1897.log](https://github.com/eclipse/deeplearning4j/files/3347757/hs_err_pid1897.log)
[gup exceptions.txt](https://github.com/eclipse/deeplearning4j/files/3347758/gup.exceptions.txt)

#### Version Information

* Deeplearning4j 1.0.0-beta4
* Platform information (OS, etc): ubuntu18.04
* CUDA version, 10.0
* cudnn: 7.3

**Comment by cqiaoYc** [comment]
ND4j operations were used:
1. Nd4j.getExecutioner().exec(new BernoulliDistribution(Nd4j.createUninitialized(shape), prob), random).castTo(DataType.UBYTE);
2. INDArray.muli(),.subi(),.castTo(DataType.HALF)
3. Nd4j.vstack()
4. Nd4j.randn()
5. Nd4j.getExecutioner().execAndReturn(new HammingDistance(x, y)).getFinalResult().doubleValue();

**Comment by cqiaoYc** [comment]
I resued the RNN net as:
```
if(network==null){
            network = new MultiLayerNetwork(netConfig);
            network.init(netParams, false);
        }else{
            network.clear();
            network.clearLayersStates();
            network.rnnClearPreviousState();
            network.setParams(netParams);
        }
```
Now, there are 2 instances of net, but after 180 generations, an execption was thrown.
```
Exception in thread "pool-1-thread-2" java.lang.RuntimeException: std::bad_alloc
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.concat(Native Method)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:520)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5495)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:979)
	at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:5245)
	at com.cq.deepGa4j.entity.AbstractIndividual.computeNetParams(AbstractIndividual.java:182)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:54)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:352)
	at com.cq.deepGa4j.Population.evolute(Population.java:256)
	at com.cq.deepGa4j.Population.evolute(Population.java:210)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by raver119** [comment]
show your source code as gist please. Ops you've posted above can't leak - that's legacy operations, and they have no internal allocations.

**Comment by cqiaoYc** [comment]
my source code is too long. I listed all possible GPU-related operations：
···
1. Nd4j.getExecutioner().exec(new BernoulliDistribution(Nd4j.createUninitialized(shape), prob), random).castTo(DataType.UBYTE);
2. Nd4j.getExecutioner().execAndReturn(new HammingDistance(x, y)).getFinalResult().doubleValue();
3. 
        allNetParamParts = Nd4j.vstack(netParamParts).castTo(DataType.INT);
        INDArray netParamArray = allNetParamParts.muli(partWeightsWithoutSignal);
        allNetParamParts = allNetParamParts.castTo(DataType.UBYTE);
      netParams = netParams.castTo(DataType.FLOAT);
        netParams.muli(paramsScaleFactor).subi(maxWeight);
        netParams = netParams.castTo(DataType.HALF);
4. INDArray.dup()
5. Nd4j.ones(DataType.UBYTE,1, netParamsCount).subi(sonMaskA);
6. matherNetParamParts[i].mul(sonMaskA).addi(fatherNetParamParts[i].mul(sonMaskB));
7.    if(network==null){
            network = new MultiLayerNetwork(netConfig);
            network.init(netParams, false);
        }else{
            network.clear();
            network.rnnClearPreviousState();
            network.setParams(netParams);
        }
       INDArray output = network.rnnTimeStep(dataSet.getFeatures3D());
       INDArray predicts = output.argMax(1);
···

**Comment by raver119** [comment]
I'm asking for source code because i there are no known leaks, and the first suspect is actual hidden references to INDArrays somewhere within your code.

As i've told before - operations you've listed above have no own memory management.

**Comment by cqiaoYc** [comment]
Thank you! Let me check the references to INDArrays.

**Comment by raver119** [comment]
Keep us posted please.

**Comment by cqiaoYc** [comment]
I set :
```
Nd4j.getMemoryManager().setAutoGcWindow(50);
```
It’s a lot slower when it’s evolved to 300 generations. 
-----------------------------
I simplified the code and removed some of the long-lived INDArray, andNd4j.vstack(). 
Set Nd4j.getMemoryManager().setAutoGcWindow(500);
now the program is running fairly stable and has not thrown an exception.

**Comment by raver119** [comment]
> Nd4j.getMemoryManager().setAutoGcWindow(50);

That's way too often. You can disable it, and just put System.gc() at the end of your epoch somewhere. 

> It’s a lot slower when it’s evolved to 300 generations.
That means you've got lots of java objects, so gc round takes a lot of time. Do what I've said above.

 > removed some of the long-lived INDArray
Right. I'm 99.99% sure that's what caused troubles. References.
