### ISSUE TITLE
Keras model import problem on BLSTM model

### ISSUE THREAD

**Issue by gzhu06** [eclipse/deeplearning4j#7967]
#### Issue Description

I trained a 4 layer BLSTM model in Keras and tried to import this model using: 

ComputationGraph net = KerasModelImport.importKerasModelAndWeights

but when I tried to forward this model on one file, I got an indarray output like this:

[[[         �,         �,         �  ...         �         �,         �], 
  [         �,         �,         �  ...         �         �,         �], 
  [         �,         �,         �  ...         �         �,         �], 
   ..., 
  [         �,         �,         �  ...         �         �,         �], 
  [         �,         �,         �  ...         �         �,         �], 
  [         �,         �,         �  ...         �         �,         �]]]

when I tried to forward this model to other file, it works normally. It looks like sometimes BLSTM model works sometimes it doesn't. 

There is nothing wrong with the files and also when I run the model in Python on the same files, there is no problem. 

#### Version Information

* dl4j and nd4j: 1.0.0-beta4

**Comment by AlexDBlack** [comment]
We're going to need a *lot* more information than this, there's not enough information to even begin to debug this.
For example, can you provide the model file? And provide code for how you are producing the inputs?
Also what backend (CPU/GPU) are you using?

**Comment by gzhu06** [comment]
> We're going to need a _lot_ more information than this, there's not enough information to even begin to debug this.
> For example, can you provide the model file? And provide code for how you are producing the inputs?
> Also what backend (CPU/GPU) are you using?

1)the model file is very huge;
2)the inputs is a spectrogram of an audio file;
3)I'm using CPU.

I'm curious how can the output of my model be some nonsense symbols sometimes.

**Comment by AlexDBlack** [comment]
Those symbols are NaNs.
That can happen in a few ways:
* NaN on infinite on input
* Numerical underflow/overflow (numbers get too small/large)
* 0s or negatives into some ops - like log
* Bugs

Unfortunately without any way to reproduce this issue, we can't do anything to help here, or fix any issues if present.
We would be happy to look into it further once we are able to. Can you at least provide some code to produce an equivalent model and dummy input that reproduces the problem?

**Comment by gzhu06** [comment]
> Those symbols are NaNs.
> That can happen in a few ways:
> 
> * NaN on infinite on input
> * Numerical underflow/overflow (numbers get too small/large)
> * 0s or negatives into some ops - like log
> * Bugs
> 
> Unfortunately without any way to reproduce this issue, we can't do anything to help here, or fix any issues if present.
> We would be happy to look into it further once we are able to. Can you at least provide some code to produce an equivalent model and dummy input that reproduces the problem?

Ok, problem solved, knowing that those symbols are NaNs is very helpful.

Thank you!
