### ISSUE TITLE
Libnd4j batch_to_space validation failure for 1d CNN

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#7969]
Might be related to #6312 and #6447.

Inputs:

1. Input, Shape `[4, 4, 3]`
2. Blocks, Shape `[2]`, values `[1, 2]`
3. Cropping, Shape `[2, 2]`, values `[[0, 0], [0, 1]]`

From the [tensorflow docs](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-to-space-n-d):

reshaped (shape) = `[1, 2, 2, 4, 3]`
permuted (shape)  = `[2, 4, 1, 3, 2]`
reshaped_permuted/output (shape)   = `[2, 4, 5]`

Error:
```java
Op [batch_to_space] execution failed
java.lang.RuntimeException: Op [batch_to_space] execution failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1669)
	at Tests.testSTB(Tests.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at ...
org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1661)
	... 48 more

Error at [D:/jenkins/ws/dl4j-master-windows-x86_64-cpu/libnd4j/include/ops/declarable/generic/parity_ops/batch_to_space.cpp:74:0]:
BatchToSpace: blocks length + 2 should match input rank at least
```

To reproduce:
```java
@Test
public void testBtS(){

    INDArray out = Nd4j.create(DataType.FLOAT, 2, 4, 5);
    DynamicCustomOp c = new BatchToSpace();

    c.addInputArgument(
            Nd4j.rand(DataType.FLOAT, new int[]{4, 4, 3}),
            Nd4j.createFromArray(1, 2),
            Nd4j.createFromArray(new int[][]{ new int[]{0, 0}, new int[]{0, 1} })
    );
    c.addOutputArgument(out);
    Nd4j.getExecutioner().exec(c);

    assertEquals(Nd4j.createFromArray(1f, 3f, 4f), out);
}
```

**Comment by rnett** [comment]
This also fails for 2d CNN input:

1. Input, Shape `[2, 3, 5, 3]`
2. Blocks, Shape `[3]`, values `[1, 1, 2]`
3. Cropping, Shape `[3, 2]`, values `[[0, 0], [0, 0], [0, 1]]`

**Comment by rnett** [comment]
`space_to_batch` may have the same issues, haven't tested (as this breaks first).

**Comment by rnett** [comment]
[tensorflow example](https://colab.research.google.com/drive/1u9CeLGhwbpay-IcZnRKgZTYAymgLMAX8)

Only works with tensorflow 2 (the api changed).

**Comment by raver119** [comment]
right, just a validation bug.

**Comment by raver119** [comment]
Should be fixed now, please confirm/decline

**Comment by rnett** [comment]
Yeah, its fixed.

**Comment by AlexDBlack** [comment]
Closing as resolved.
@rnett  Though let's add the test case from the issue as a ND4J test to prevent regressions (if you haven't already).

**Comment by rnett** [comment]
Added in `org.nd4j.linalg.Nd4jTestsC` in SkymindIO/deeplearning4j#37
