### ISSUE TITLE
ND4J API - INDArray/SDVariable: adding transforms

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#7970]
There are a few methods with a single array input that imo, should go in INDArray/SDVariable, but could go in Nd4j/SameDiff (and sometimes are already there):
 * abs
 * exp, log
 * square, sqrt (maybe)
 * and, or, xor (maybe)
 * tile (if this is the same as repeat its already in INDArray)

My rationale is that they are used enough that its easier (and makes more sense) to access them via `x.pow(2)` rather than `sameDiff.pow(x, 2)`.

Thoughts, additions, removals?

**Comment by AlexDBlack** [comment]
The way I am thinking about this is more API simplification (though it does impact #7971 too).
Currently users need no know ND4J, INDArray, and Transforms classes.
Users can't not use the first two, but Transforms has always been a separate thing, and new users can not realize it exists and that there's a whole lot of methods there.

So the design question is basically this: What methods should be moved from the Transforms class, and to where? (INDArray or ND4J)

Some options here:
1. Go "numpy" style: `numpy.log` and `numpy.exp` etc
2. Add INDArray.exp, expi, etc
3. SameDiff/TF style: `Nd4j.math().log(...)`

cc @raver119 @treo

**Comment by rnett** [comment]
Tbh, I didn't realize Transforms existed until now, although I never really needed it either (cause SameDiff).

**Comment by raver119** [comment]
I think any option is cool, as long as it's unified across the code base. So since for SameDiff we're going via "namespace" way, maybe we should do the same with Nd4j as well?

**Comment by raver119** [comment]
p.s. in c++ APIs we'll be going with "namespace" way as well.

**Comment by AlexDBlack** [comment]
Yeah, I'd be fine with that namespace (SameDiff/TF) style, let's go with that :+1:
I do like how `SameDiff.math()`/`SameDiff.math` and `SameDiff.loss()`/`SameDiff.loss`, etc looks/works in practice.
And as you say, that makes it consistent with the other 2 APIs (SameDiff/c++)...
