### ISSUE TITLE
ND4j getWhere tests should fail

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#7973]
#### Issue Description
[This test](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L7654-L7661) passes:

    @Test
    public void testGetWhereNumber() {
        INDArray input = Nd4j.create(new double[] { 1, -3, 4, 8, -2, 5 });
        INDArray expected = Nd4j.create(new double[] { 8, 5 });
        INDArray actual = input.getWhere(4, Conditions.greaterThan(6));

        assertEquals(expected, actual);
    }

It should fail since 5 < 6. 
The "4" seems to be a bit of a magic number. Changing it makes the test fail harder;

    @Test
    public void testGetWhereNumber() {
        INDArray input = Nd4j.create(new double[] { 1, -3, 4, 8, -2, 5 });
        INDArray expected = Nd4j.create(new double[] { 8, 5 });
        INDArray actual = input.getWhere(0, Conditions.greaterThan(6));

        assertEquals(expected, actual);
    }

actual  = [    1.0000,    4.0000,    8.0000,    5.0000], way off.

#### Version Information
1.0.0-beta4

There is already a ticket open for the issue with Nd4J getWhere. 
Lets make this issue about the getWhere unit tests.

**Comment by raver119** [comment]
It should not. Author of this op/method doesn't use comparator argument at all. Only condition itself. And comparators are 4/0 respectively.
