### ISSUE TITLE
ND4S Build issue

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7978]
Technically this only impacts the Skymind fork AFAIK (not yet merged here), but I'll log it here anyway...
After recent UX improvements to ND4J, ND4S is having trouble resolving some methods
In think there are 2 problems:
1. Additional toString overloads
2. Scala having trouble with java primitive varargs methods (seems like it can't find or use them??)

Full compilation errors below. My scala knowledge isn't sufficient to fix this, and googling the varargs issue didn't result in a solution...

https://gist.github.com/AlexDBlack/f54deeebc14f4713198ad5b4fbfe3f3a

**Comment by alexanderst** [comment]
@raver119  Fixed, please merge and close.
