### ISSUE TITLE
SameDiff: Name scope duplicated in output variable names

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#7981]
For example, if you have a op named `sum` in scope `whileTest`, the true name of sum's output variable will be `whileTest/whileTest/sum:0`.  This is because a `nameScope` is added in `var` (so that it cal be called), but is also added to the op's `ownName`.

Imo the easiest fix is to add a private overload of var with a `useNameScope` flag and call it with false, but I wanted to check before implementing it.

**Comment by rnett** [comment]
Its also done in the `SDVariable` constructor, I don't think that one needs to be there.

**Comment by rnett** [comment]
To reproduce:
```java
@Test
public void testNames(){
    SameDiff SD = SameDiff.create();

    SDVariable a = SD.constant(4);
    SDVariable b = SD.constant(5).lt(4);

    NameScope scope = SD.withNameScope("test");

    SDVariable out = SD.f().switchOp(a, b)[0];

    out.add(45);

    scope.close();

    System.out.println(SD.variableMap());
}
```

**Comment by rnett** [comment]
Well, it seems like it may have something to do with using `switch` and using it through `f()`.
```java
@Test
public void testNames2(){
    SameDiff SD = SameDiff.create();

    SDVariable a = SD.constant(4);
    SDVariable b = SD.constant(5);

    NameScope scope = SD.withNameScope("test");

    SDVariable out = a.mul(b);

    out.add(45);

    scope.close();

    System.out.println(SD.variableMap());
}
```

This does not produce the same issue.

**Comment by rnett** [comment]
Although, this one does:
```java
@Test
public void testNames3(){
    SameDiff SD = SameDiff.create();

    SDVariable a = SD.constant(4);
    SDVariable b = SD.constant(5);

    NameScope scope = SD.withNameScope("test");

    SDVariable out = SD.argmax(a);

    out.add(45);

    scope.close();

    System.out.println(SD.variableMap());
}
```

And its not using `f()`.

**Comment by AlexDBlack** [comment]
I think a simpler solution in SDVariable is:
```
        if(nameScope != null && !varName.startsWith(nameScope)){
            varName = nameScope + "/" + varName;
        }
```

If we simply remove it from the SDVariable constructor, the existing tests below fail.

Let's add some more tests (adapted from the above) here: https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/NameScopeTests.java
