### ISSUE TITLE
ND4j: Building from source updates .java files

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#7986]
#### Issue Description
After building Nd4J with:

    mvn install -DskipTests

git status indicates more files have been updated than were edited:

    git status
    On branch ra_nd4j_append
    Changes not staged for commit:
        (use "git add <file>..." to update what will be committed)
        (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/evaluation/classification/Evaluation.java
        modified:   nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/recurrent/config/SRUCellConfiguration.java
        modified:   nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/recurrent/config/SRUConfiguration.java
        modified:   nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java
        modified:   nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/learning/AdaDeltaUpdater.java
        modified:   nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java

    no changes added to commit (use "git add" and/or "git commit -a")

The expected behavior is to see only the file changed that has been editied. `Nd4j.java`

#### Version Information
Win10 command line.

**Comment by AlexDBlack** [comment]
Nd4jCpu.java is expected
The others are not (and I don't see those when building on windows).
At a guess, it's probably character encoding issues.

Post the `git diff` in a gist and I'll take a look...

**Comment by raver119** [comment]
Only Nd4jCpu and Nd4jCuda are uodated. Others can't be updated unless you have some formatting plugin activated in the background.

**Comment by RobAltena** [comment]
[Here ](https://gist.github.com/RobAltena/1a9312394d1e38b9c7849bd61198221a) is a gist with commands, maven log and git diff.

**Comment by raver119** [comment]
So that's literally encoding issue...

**Comment by raver119** [comment]
```
-       *    2: row of biases with twice length [1 × 4K]
+       *    2: row of biases with twice length [1 �? 4K]
```

**Comment by AlexDBlack** [comment]
Yep, just character encoding, easy to fix. I've got a branch open ATM about to merge, I'll take care of it now (will be on skymind fork until merged back to master)

**Comment by AlexDBlack** [comment]
Fix merged to SkymindIO/deeplearning4j master - https://github.com/SkymindIO/deeplearning4j/pull/49
