### ISSUE TITLE
ND4J Tests - NPE under Java 12 (Guava reflection can't find/list classes)

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7988]
Exact same problem as this, but in tests: https://github.com/eclipse/deeplearning4j/issues/7572

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/validation/OpValidation.java#L528

Using system classloader instead doesn't help. Getting all classes using `.getAllClasses()` instead doesn't help. In all cases, an empty set is returned.

**Comment by rnett** [comment]
This also causes OpValidation to give 0s for stats when ran with Java >8, like:
```
o.n.a.v.OpValidation - Op Validation:                        0 of 0 classes with adequate tests (NaN% coverage)
o.n.a.v.OpValidation - Forward pass tests:                   0 of 0 classes (NaN% coverage)
o.n.a.v.OpValidation - Gradient check tests:                 0 of 0 classes (NaN% coverage)
```

From https://github.com/google/guava/issues/2152#issuecomment-373385731, it looks like all that is needed is a guava update.
