### ISSUE TITLE
ND4J: Exception - Expected vs provided shape mismatch

### ISSUE THREAD

**Issue by aboulang2002** [eclipse/deeplearning4j#7993]
This issue is maybe a duplicate of several issues I see open for calculateOutputShape.

This test:

    @Test
    public void test_DynamicCustomOp() {
        int numChannels = 3;
        int height = 100;
        int width = 100;

        int newHeight = 10;
        int newWidth = 10;

        INDArray boxes = Nd4j.create(new float[] { 0.0f, 0.0f, 1.0f, 1.0f }, new long[] { 1, 4 }, DataType.FLOAT);
        INDArray indices = Nd4j.create(new int[] { 0 }, new long[] { 1, 1 }, DataType.INT);
        INDArray resize = Nd4j.create(new int[] { newHeight, newWidth }, new long[] { 1, 2 }, DataType.INT);

        INDArray input = Nd4j.rand(new long[] { 1, height, width, numChannels });

        // Expected shape: [ 1, 10, 10, 3 ]
        long[] resizedShape = new long[] { 1, newHeight, newWidth, numChannels };
        LongShapeDescriptor outputShape = LongShapeDescriptor.fromShape(resizedShape, input.dataType());
        INDArray output = Nd4j.create(outputShape, false);

        CustomOp op = DynamicCustomOp.builder("crop_and_resize")
                .addInputs(input, boxes, indices, resize)
                .addIntegerArguments(1) // NearestNeighbor
                .addOutputs(output)
                .addOutputShape(outputShape)
                .build();
        Nd4j.getExecutioner().exec(op);
    }

This runs fine with ND4J 1.0.0.0-beta4 but fails with 1.0.0.0-SNAPSHOT with this error:
`Expected vs provided shape mismatch [1, 10, 10, 1] vs [1, 10, 10, 3] at index 0`
Which is incorrect. I do expect [ 1, 10, 10, 3].

**Comment by raver119** [comment]
cc @shugeo

**Comment by shugeo** [comment]
Indeed, this is a bug, it was already fixed. In a week should be merged.
