### ISSUE TITLE
Libnd4j assign error for XLNet

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8002]
When running XLNet import test, I get:
```
Can't assign new value to the array: this shape [1024]; other shape: [-32000, 1024]
terminate called after throwing an instance of 'std::runtime_error'
  what():  NDArray::assign: lengths of arrays are mismatched
```

To reproduce, run `org.nd4j.imports.TFGraphs.TFGraphTestZooModels` and comment out `"xlnet_cased_L-24_H-1024_A-16"` from the ignores.

Make sure you have the latest version of the test resources.

**Comment by AlexDBlack** [comment]
Could we isolate this a bit more?
Ideally to the op + the inputs. A standalone test case (using DynamicCustomOp) would be even better, as that can be translated in to a c++ test for easier/faster debugging and to prevent future regressions.

**Comment by rnett** [comment]
Will do.  Errors like this don't produce a stack trace, it would be good to add that at some point.

**Comment by AlexDBlack** [comment]
Some errors like this will produce a good stack trace - it really depends on the op type (custom ops are good, legacy ops not so much). Standardizing this would be great too...
https://github.com/eclipse/deeplearning4j/blob/1170827c18005aa9dc7e6f0550964a4e4a6afcf2/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/ops/NativeOpExecutioner.java#L2079-L2135

**Comment by rnett** [comment]
To reproduce:
```java
@Test
public void testGather(){

    INDArray out = Nd4j.create(DataType.FLOAT, 128, 8, 1024);
    DynamicCustomOp op = new Gather();

    INDArray a = Nd4j.rand(DataType.FLOAT, 32000, 1024);//.sub(0.5).mul(2);

    INDArray b = Nd4j.rand(DataType.FLOAT, 128, 8).sub(0.5).mul(20).castTo(DataType.INT);

    op.addInputArgument(
            a,
            b,
            Nd4j.scalar(0f)
    );
    op.addIArgument(0);
    op.addOutputArgument(out);

    Nd4j.getExecutioner().exec(op);
}
```

Note that the `.sub(0.5).mul(20).castTo(DataType.INT)` on b is necessary, it works otherwise (although all indexes are 0).

**Comment by rnett** [comment]
Indexes are negative here, as they are in the graph, and it is possible that that is what is causing the error.

**Comment by AlexDBlack** [comment]
> Indexes are negative here, as they are in the graph

Yeah, my guess is that the real problem is earlier in the graph. Gather doesn't support negative indices:
> Index tensor. Must be in range [0, params.shape[axis]).

https://www.tensorflow.org/api_docs/python/tf/gather

Our gather works the same way.

**Comment by rnett** [comment]
So it looks like it was due to having random inputs to XLNet instead of the index/mask setup you're supposed to use.  This has been fixed in test-resources and I now get OOM, so this looks to be fixed.

It would be nice to have some kind of assertion on the Libnd4j side that the indecies are positive, rather than erroring on an assign.

**Comment by rnett** [comment]
I think the reason no stack trace was provided is because c++ `terminate` was called, nothing was ever passed back up to Java.  Gather is a CustomOp, so it should have produced a stack trace w/ the code you linked earlier.  Seems like it needs some parameter validation.

**Comment by AlexDBlack** [comment]
> It would be nice to have some kind of assertion on the Libnd4j side that the indecies are positive, rather than erroring on an assign.

Agreed.

https://github.com/eclipse/deeplearning4j/issues/8007
