### ISSUE TITLE
Nd4j.createBufferDetached defaults to Float

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8003]
Just want to make sure this is expected behavior end not an issue. 

    @Test
    public void testDummy() {

        int[] shape = new int [] {10};

        for(DataType dt : DataType.values()){

            try {
                DataBuffer dataBuffer = Nd4j.createBufferDetached(shape, dt);
                System.out.println(dt.toString() + " - " + dataBuffer.dataType().toString());
            } catch (UnsupportedOperationException e){
                System.out.println(e.getMessage());
            }
        }
        }

outputs:

    DOUBLE - DOUBLE
    FLOAT - FLOAT
    FP16 isn't supported for CPU yet
    LONG - LONG
    INT - INT
    SHORT - FLOAT
    UBYTE - FLOAT
    BYTE - FLOAT
    BOOL - FLOAT
    UTF8 - FLOAT
    COMPRESSED - FLOAT
    BFLOAT16 - FLOAT
    UINT16 - FLOAT
    UINT32 - FLOAT
    UINT64 - FLOAT
    UNKNOWN - FLOAT

`createBufferDetached`  has no tests at the moment.

edit:  `createBuffer(int[] shape, DataType type)` has the same problem. (Managed to slip pass me by having a bit of javadoc.)

**Comment by AlexDBlack** [comment]
Good catch. Definitely a bug.

**Comment by raver119** [comment]
I've fixed this, however this set of methods isn't used anywhere anymore, and should be removed probably...
