### ISSUE TITLE
Nd4j rand methods give zeros for BFLOAT16

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8010]
The following test returns zeros arrays, not random ones:

    
    @Test
    void testRndBloat16() {
        INDArray x  = Nd4j.rand(DataType.BFLOAT16 , 'c', new int[]{5});
        System.out.println(x);

        x = Nd4j.randn(DataType.BFLOAT16 , 10);
        System.out.println(x);
    }

output:

    [         0,         0,         0,         0,         0]
    [         0,         0,         0,         0,         0,         0,         0,         0,         0,         0]

Behavior for other datatypes is as expected: An exception for non floating point datatypes or a random array.

**Comment by raver119** [comment]
Fixed
