### ISSUE TITLE
Nd4j.create checks data sizes inconsistent.

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8013]
The create methods work most of the time when too much data is provided. But some methods have an extra  check sprinkled in (and copied/pasta-ed around) for the 1d case. For example:

    @Test
    void testCreateSizeChecks() {
        INDArray x;
        double [] data = new double[]{1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13, 14, 15, 16};

        // This is accepted:
        x = Nd4j.create(data , new int[]{3, 2, 2});
        x = Nd4j.create(data , new int[]{6, 2});

        // This is not.
        // linalg.exception.ND4JIllegalStateException: Shape of the new array [9] doesn't match data length: 12
        x = Nd4j.create(data , new int[]{12});
    }

#### Contributing
With all the checking done in `Nd4j.java` I can help out on this one. We just need to decide on the checking strictnes and on which `create` methods to keep/discard/deprecate,

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/SkymindIO/deeplearning4j/pull/87
