### ISSUE TITLE
concurrent exception in dl4j ui

### ISSUE THREAD

**Issue by musicaudience** [eclipse/deeplearning4j#8017]
#### Issue Description

Please describe our issue, along with:
- there should no concurrent modification exception met in the ui project.
- occasionally, the  concurrent modification exception will be thrown from the dl4j ui.

#### Version Information
deeplearning4j-play_2.11-1.0.0-beta4.jar

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-beta4
* Platform information (OS, etc)
Mac OS X

* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

class name: org.deeplearning4j.ui.module.train.TrainModule
![image](https://user-images.githubusercontent.com/35216951/61357160-5f66f380-a8aa-11e9-87e2-065391d616ad.png)

![image](https://user-images.githubusercontent.com/35216951/61357388-bd93d680-a8aa-11e9-9370-86b6000177e8.png)

field "knownSessionIDs"'s iterator is not synchronized
![image](https://user-images.githubusercontent.com/35216951/61357285-845b6680-a8aa-11e9-93d5-8c7afee4cf0c.png)

which will leads concurrent modification exception:
![image](https://user-images.githubusercontent.com/35216951/61357714-5fb3be80-a8ab-11e9-8161-b3d23b778a43.png)

**Comment by AlexDBlack** [comment]
Thanks for reporting. This was due to a non-synchronized method sessionInfoForSession.
The map should have been synchronized at the method level.
