### ISSUE TITLE
Nd4j.createFromNpy causes SIGSEGV when file does not exist

### ISSUE THREAD

**Issue by Belval** [eclipse/deeplearning4j#8020]
#### Issue Description

Please describe our issue, along with:

Expected behavior: An exception should be thrown indicating that the path is invalid
Encountered behavior: Application fails with SIGSEGV, causing core dump.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): Ubuntu 18.04
* CUDA version, if used: 10.1
* NVIDIA driver version, if in use: 418.56

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)

Error message: https://gist.github.com/Belval/b4e3b59682c1b30e9f7d789d6739a92a
Core dump: https://gist.github.com/Belval/ea196bbadb7fe6e212bf31eac0f64b4a

* pom.xml file or similar (also in a Gist)

https://gist.github.com/Belval/1858e7f7e31ec6b3eafe696e3b9de1ee

#### How to reproduce

Run this: `INDArray inputs = Nd4j.createFromNpyFile(new File("/home/belval/blah.npy"));`

**Comment by Belval** [comment]
Don't waste time on this, the path was wrong. Maybe a check should be added but it's not a real bug.

**Comment by raver119** [comment]
Path validation should be added then. No way absent file should cause segfault. Don't close this one please.

**Comment by Belval** [comment]
Updated the title to better describe the issue.

**Comment by raver119** [comment]
Fixed, thanks for highlighting this issue
