### ISSUE TITLE
beta4 dependent on Java 9 jars

### ISSUE THREAD

**Issue by daw3rd** [eclipse/deeplearning4j#8022]
#### beta 4 adds new dependencies on jars that are compiled with Java 9 and so may not run on Java 8.

I would like to run DL4J beta4 in a web app on tomcat 8 with Java 1.8, but am getting many of these types of errors in the tomcat log

```
SEVERE: Unable to process Jar entry [META-INF/versions/9/module-info.class] from Jar [file:/root/sound.V2/apache-tomcat-8.0.39/webapps/IoT-SoundServer/WEB-INF/lib/mkl-2019.3-1.5-macosx-x86_64.jar] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
```

beta4 seems to have changed dependencies as I did not get this with beta2.  I have not yet seen this running DL4J in a standalone java app.  I believe Tomcat is being aggressive and trying to validate all jars on the classpath even though they may not be loaded.  I suppose this is good in that it may be pointing out a problem?

#### Version Information

* deeplearning4j-nn 1.0.0-beta4
* nd4j-native-platform 1.0.0-beta4
* Ubuntu 14, Tomcat 8.0.39, IBM Java 1.8
* Not using GPU

**Comment by saudet** [comment]
That seems to be a bug in Tomcat, not Java 8. If you can't update the version of Tomcat, you can remove those module-info.class files, that's fine.

**Comment by daw3rd** [comment]
I don't think this a bug in tomcat.  I think tomcat is trying to validate .class or jar files and it can't when the .class/jar files are Java 9 and tomcat is running with Java 8.  It is simply identifying the jars that are not Java 8, which may mean that DL4J can't run in Java 8 under some circumstances (besides tomcat).

**Comment by AlexDBlack** [comment]
I agree with @saudet here. This looks like a tomcat bug.
This post explains it in some detail:
https://github.com/classgraph/classgraph/issues/291#issuecomment-446493724

**Comment by daw3rd** [comment]
Ok, I'm convinced this is a tomcat bug.  However, doesn't this still indicate that dl4j beta4 has dependencies on Java 9-compiled code?  Is that expected/desired?

**Comment by saudet** [comment]
The file is in a directory named `META-INF`, which is not a valid package name, and therefore cannot contain class files. This is a bug in Tomcat.
