### ISSUE TITLE
Hope ND4J can support bit operations on integers.

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#8024]
The bit operations on integers like and, or, xor, move, etc, are too important for general purpose computing applications. It would be great if ND4j supported these operations.

**Comment by raver119** [comment]
And/Or/Xor are already available at cpp level.

**Comment by raver119** [comment]
What else you'd like to have?

**Comment by cqiaoYc** [comment]
bit move operation.

**Comment by raver119** [comment]
You mean bit shift?

**Comment by cqiaoYc** [comment]
such as:  i>>2

**Comment by raver119** [comment]
Yes, that's bit shift. Okay, we'll add those too.

**Comment by AlexDBlack** [comment]
> And/Or/Xor are already available at cpp level.

Not Java level yet though as far as I can see... easy to add though

> Yes, that's bit shift. Okay, we'll add those too.

For import, we need and/or/xor/not, left/right shift...
https://www.tensorflow.org/api_docs/python/tf/bitwise

Plus one more while we're at it:
https://www.tensorflow.org/api_docs/python/tf/bitcast

**Comment by cqiaoYc** [comment]
Great! and when can I use them? 
1. A special requirement is cyclic shift. such as: b0b1b2b3b4b5>>2, the result is b4b5b0b1b2b3; and b4b5b0b1b2b3<<2 is b0b1b2b3b4b5.
ndarrayX>>ndarrayY, cyclic shift ndarrayX[i]>>ndarrayY[i].
2. another requirement is ndarray map, such as ndarrayX.map(Map<Integer,Integer> ndaMap), the result is ndarrayY[i]=ndaMap.get(ndarrayX[i])

**Comment by cqiaoYc** [comment]
the cyclic shift operation  is very important for me.

**Comment by cqiaoYc** [comment]
Bit shift operations are related to sign. Does ND4J plan to support unsigned integers and unsigned short integer types?

**Comment by AlexDBlack** [comment]
Unsigned types were added soon after beta4 was released. They are fully supported on current master/snapshots.
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/DataType.java#L32-L34

**Comment by cqiaoYc** [comment]
Look-up table method is a very common calculation method, so it is suggested that ND4J provide a method:
INDArray INDArray.map(Map<Integer,Integer> map);
INDArray resultArray=vector.map(mm);  
```
for (int i;i<vector.shape()[0];++i){
    resultArray.putScalar(i, map.get(vector.getInt(i)));
}
```

**Comment by AlexDBlack** [comment]
@cqiaoYc That's just gather operation on 1d array, which we already have.

SameDiff implementation:
https://github.com/eclipse/deeplearning4j/blob/57efc2bf956af1140c00675aca7c8bd8a67f29bf/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDBaseOps.java#L579-L614

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Gather.java

Works identically to TF gather:
https://www.tensorflow.org/api_docs/python/tf/gather?hl=en

**Comment by cqiaoYc** [comment]
@AlexDBlack Thank you! I I'm not familiar with sameDiff, I'll learn it.

**Comment by AlexDBlack** [comment]
@cqiaoYc You can use the operation normally for ND4J too, not just in SameDiff
(Though now that I look at it, there's no INDArray constructor for that op)

You can do something like:

```
INDArray inputVector = ...
INDArray indicesVector = ...
INDArray out = ...
Nd4j.exec(DynamicCustomOp.builder("gather")
    .addInputs(inputVector, indicesVector)
    .addOutputs(out)
    .addIntegerArguments(0)   //Axis - along dimension 0
.build());
```

**Comment by cqiaoYc** [comment]
@AlexDBlack Thank you!

**Comment by cqiaoYc** [comment]
Another requirement is to compute bit-based Hamming distances, that is, to compute how many bits of the corresponding integers in two ndarrays are different. This can be calculated by XOR, mapping and summation, so it is not very urgent.

**Comment by raver119** [comment]
shift_bits & cyclic_shift_bits implemented.
