### ISSUE TITLE
checkShapeValues has different implementation for long[] and int[]

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8028]
#### Issue Description
[one checks for <0, the other for <1](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L4701-L4723)

Some code to show the inconsistent consequences:

        int [] intShape = new int[] {2,0};
        long [] longShape = new long[] {2,0};

        // This is an ND4JIllegalStateException
        Nd4j.checkShapeValues(intShape);
        //This is ok:
        Nd4j.checkShapeValues(longShape);

        // This is ok
        INDArray x = Nd4j.zeros(intShape);
        // This is an ND4JIllegalStateException
        x = Nd4j.zeros(intShape, 'f');

The fix in nd4j.java is trivial, but we really should have a more serious look at the tests around these. Hence this issue.

**Comment by AlexDBlack** [comment]
Good catch. The long[] methods are all well tested.
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/shape/EmptyTests.java#L247-L284

We should probably just do int[] to long[] conversion and have only the one implementation/check.
