### ISSUE TITLE
ND4J: Nd4j and INDArray API cleanup

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8032]
This PR identified a number of methods that are unused and/or untested...
https://github.com/eclipse/deeplearning4j/pull/7997

Some of them (setParams method for example) should probably simply be removed, to clean up the API. If we decide to keep them, they should be tested.

INDArray should probably be reviewed for this also.

**Comment by rnett** [comment]
We have talked about moving to namespace style APIs as well for Nd4j (#7970).  It might be worth setting up a pass to go over all of the Nd4j api stuff and set up reflection tests (like SkymindIO/deeplearning4j#42), all at once.

**Comment by AlexDBlack** [comment]
@rnett sounds good to me, a thorough pass to clean this up all at once would be a good idea.

**Comment by AlexDBlack** [comment]
Both were recently cleaned up by @RobAltena
