### ISSUE TITLE
Unable to reproduce  unit tests in stand alone project.

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8037]
#### Issue Description
I am setting up a small test project to quickly reproduce Nd4J tests while tackling some of the code issues in `nd4j.java`.  The duplicate code for `CreaeDetached` is an easy fix.  However the tests [testCreateDetached_1](https://github.com/SkymindIO/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L3307) and [testCreateDetached_2](https://github.com/SkymindIO/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L3318) fail in a standalone project. (Before any fixing). 

Gist with details: 
https://gist.github.com/RobAltena/d44b77204b68347b6771824f8c0237c8

Edit: Within Dl4J  both `CreaeDetached` methods are only used from these tests. Maybe they should be removed?

Based on this test:

     @Test
    void testEnum() {
        long[] shape = new long[]{10};
        for(DataType dt : DataType.values()){
            try {
                DataBuffer dataBuffer = Nd4j.createBufferDetached(shape, dt);
                System.out.println(dt + " : " + dataBuffer.dataType());
            } catch (Exception e){
                System.out.println(dt + " : " + e.getMessage());
            }
        }
    }

With this result:

    DOUBLE : FP16 isn't supported for CPU yet
    FLOAT : FP16 isn't supported for CPU yet
    HALF : FP16 isn't supported for CPU yet
    LONG : LONG
    INT : INT
    SHORT : Cannot create type: SHORT
    UBYTE : Cannot create type: UBYTE
    BYTE : Cannot create type: BYTE
    BOOL : Cannot create type: BOOL
    UTF8 : Cannot create type: UTF8
    COMPRESSED : Cannot create type: COMPRESSED
    BFLOAT16 : Cannot create type: BFLOAT16
    UINT16 : Cannot create type: UINT16
    UINT32 : Cannot create type: UINT32
    UINT64 : Cannot create type: UINT64
    UNKNOWN : Cannot create type: UNKNOWN

Removal seems in order.

**Comment by AlexDBlack** [comment]
cc @raver119 
createBufferDetached seems like something we might need... though were the Nd4j.createBuffer methods going away longer term anyway?
If so, then maybe this could go away sooner rather than later...

**Comment by RobAltena** [comment]
Few thoughts from my side: We should and are providing an easy to use suite of factory methods for ndarrays. For buffers and detached buffers we could consider them a more advanced concept where the user should know what they are doing. A method like [numpy.newbuffer](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.newbuffer.html) could be all that we need.

**Comment by raver119** [comment]
Users typically never touch these methods, only we do, for out-of-workspace allocations. There methods were used for shapeInfoBuffers. Now shape info buffers are created in cpp. So on one hand we can remove those, but on other hand i'd keep those for a while, we might use those for upcoming SameDiff executioner changes. Hasn't decided yet.

**Comment by RobAltena** [comment]
I rebuild SkyMindIO/Deeplearning4j  libn4j and nd4j locally this morning.

All the tests pass and the output of testEnum looks a lot better:

    DOUBLE : DOUBLE
    FLOAT : FLOAT
    HALF : HALF
    LONG : LONG
    INT : INT
    SHORT : SHORT
    UBYTE : UBYTE
    BYTE : BYTE
    BOOL : BOOL
    UTF8 : Cannot create type: UTF8
    COMPRESSED : Cannot create type: COMPRESSED
    BFLOAT16 : BFLOAT16
    UINT16 : UINT16
    UINT32 : UINT32
    UINT64 : UINT64
    UNKNOWN : Cannot create type: UNKNOWN

Source builds, test pass --> Issue closed.
