### ISSUE TITLE
SameDiff: Output return types are a pain to work with

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8044]
Currently, we have 3 output methods, which return either `Map<String, INDArray>` (with a `DataSet` as input) or `List<Map<String, INDArray>>`.  `List<Map<String, INDArray>>` is a pain to use if you are trying to get all the outputs for some variables, and it doesn't match the keras predict methods.

In addition, single output prediction (which will be what is used most of the time) is an extra step over multi output prediction (which is rarer).

I'd make two changes:
1. All (multi)output methods return `Map<String, INDArray>`, when batches are passed in they are concatenated together for each variable (`[{a: [1, 2], b: [6, 5]}, {a: [3, 4], b: [4, 3]}] --> {a: [1, 2, 3, 4], b: [6, 5, 4, 3]}`).
2. Add `outputSingle` methods that output values for a single variable (returning `INDArray`, using concatenation like above for multi-batch).

This makes the most common use case of multi-batch prediction on a single output go from:
Before:
```java
List<Map<String, INDArray>> out = SD.output(...);
List<INDArray> batches = new ArrayList<>();

for(Map<String, INDArray> batch : out)
    batches.add(batch.get(...));

INDArray result = Nd4j.concat(0, batches.toArray(new INDArray[0]));
```
After:
```java
INDArray result = SD.outputSingle(...);
```

**Comment by AlexDBlack** [comment]
https://github.com/SkymindIO/deeplearning4j/pull/82
