### ISSUE TITLE
libnd4j: add mergemax_bp op

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8053]
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/transforms/merge_max.cpp

mergeavg, mergeadd aren't really needed (straightforward to do in java for example) but we could add those too...

Main reason is performance: this is ugly and slow (compared to a proper implementation)
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/MergeMax.java#L86-L89

**Comment by raver119** [comment]
Implemented. Now we need java wrappers for these operations + adopt them within doDiff methods of corresponding ops.

cc @alexanderst
