### ISSUE TITLE
Failed importing Keras LSTM model

### ISSUE THREAD

**Issue by ilya-shim** [eclipse/deeplearning4j#8055]
Hi, I think my case is similar to #4556 but I didn't understand how can I fix my python/java code.

I'm training the following model in Keras on Google Colab:

```
from keras.models import Sequential
from keras.layers import Bidirectional, LSTM, Dense

model = Sequential()
model.add(Bidirectional(LSTM(units=24), input_shape=(30,300)))
model.add(Dense(24,activation="softmax"))
model.summary()
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['acc'])
```

I have a separate preprocessing service that returns (30, 300) shaped array.
Therefore, in Keras I reshape it to **(1, 30, 300)** and prediction works.

The Java MultiLayerNetwork expects **(1, 300, 30)** shaped vector, and I don't know how to provide it. 
Tried several different approaches, and they all failed (i.e. I'm not getting correct predictions).

My pom dependencies:
```
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-beta4</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-beta4</version>
        </dependency>
```

This issue also occurs when I deployed my model to Skil.
This was my post request from Postman:

`{
	"id":"12345",
	"needsPreProcessing":false,
	"prediction":
	{
		"shape":[1,300,30],
		"ordering":"c",
		"dataType":"FLOAT16",
		"data":<FLAT ARRAY OF 9000 FLOATS>
	}
}`

Thanks,
Ilya.

**Comment by AlexDBlack** [comment]
for DL4J, you need data in the format [numExamples, inputSize, sequenceLength]

> The Java MultiLayerNetwork expects (1, 300, 30) shaped vector, and I don't know how to provide it.

There's a few different approaches. For testing, you can save to a .npy file and load using Nd4j.createFromNpyFile.

Alternatively you can create a a double[][][] and use Nd4j.createFromArray


> Tried several different approaches, and they all failed (i.e. I'm not getting correct predictions).

LSTMs (including bidirectional) are well tested, we haven't had any reports of other issues there. So my first guess would be an issue with data loading.

How different are the results? Completely different, or just like 2nd/3rd decimal place?

If you're confident data loading is correct, then we'll need to look into this further to debug it.

**Comment by ilya-shim** [comment]
When loading the input .npy file that I pass to the predict_proba method in my Keras code, the following Java code worked for me:

```
public void test() throws UnsupportedKerasConfigurationException, IOException, InvalidKerasConfigurationException {

        MultiLayerNetwork network = KerasModelImport.importKerasSequentialModelAndWeights(H5_PATH);

        INDArray inputRaw= Nd4j.createFromNpyFile(new File(INPUT_NPY_PATH)); // shape (1,30,300)
        INDArray input0 = inputRaw.reshape(30,300); // shape (30,300)
        INDArray inputT = input0.transpose(); // shape (300,30)
        INDArray inputFinal = inputT.reshape(1,300,30); // shape (1,300,30)
        INDArray predictions = network.output(inputFinal);

}
```
Thanks!
