### ISSUE TITLE
Gyrfalcon AI Accelarators support ?

### ISSUE THREAD

**Issue by eix128** [eclipse/deeplearning4j#8056]
Hi , in these days AI Accelerators is spreading much.
I have seen some example:
https://www.cnx-software.com/2019/06/04/solidrun-i-mx-8m-mini-som-includes-gyrfalcon-lightspeeur-2803s-ai-accelerator/

Gyrfalcon AI accelerator 

Any plans to support  AI accelerators  and NPU (Neural Processing Unit)  in future?

This is a must for DL4J for future use.
Also OpenCL support...

**Comment by AlexDBlack** [comment]
We do have plans on our internal roadmap for increasing hardware support, beyond just CPU (x86, ARM, PPC) and GPU (CUDA). OpenCL is something we are considering but nothing has been committed to or announced at this time.

Accelerators like Gyrfalcon are not on our roadmap at present.

Are you involved in the development of such devices? Or are you a user (or potential future user) considering deployments on such devices?

**Comment by eix128** [comment]
I work on OpenCL currently.
How can we implement OpenCL or NPUs ? Any interface or abstract implementation we can make for DL4J ?

**Comment by raver119** [comment]
There would be bunch of classes to implement, like DataBuffer.h, NativeOpExecutioner.h (like it's done in `libnd4j/blas/cuda`). That would be first steps.

**Comment by raver119** [comment]
If you're interested in implementing it - drop me a line - raver119@skymind.io, and i'll be glad to guide you through framework structure.
