### ISSUE TITLE
libnd4j: mergemax input shape validation not working

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8058]
```
    @Test
    public void testInputValidationMergeMax(){
        INDArray[] inputs = new INDArray[]{
                Nd4j.createFromArray(0.0f, 1.0f, 2.0f).reshape('c', 1, 3),
                Nd4j.createFromArray(1.0f).reshape('c', 1, 1)};

        INDArray out = Nd4j.create(DataType.FLOAT, 1, 3).assign(Double.NaN);
        CustomOp op = DynamicCustomOp.builder("mergemax")
                .addInputs(inputs)
                .addOutputs(out)
                .callInplace(false)
                .build();

        Nd4j.exec(op);
        System.out.println(out);
    }
```

Result: no exception, and no outputs written/modified (all NaNs as set before exec).

This should fail validation here:
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/transforms/merge_max.cpp#L32

Also likely impacts the other merge* ops.

I'm assuming we're following TF conventions (i.e., no broadcast support) for these merge ops...
https://www.tensorflow.org/api_docs/python/tf/math/add_n

Alternatively, if we do want to support broadcasting (would be nice) then this is a bug int applying broadcasting for this op.

**Comment by raver119** [comment]
Fixed
