### ISSUE TITLE
Databuffer AllocationMode has only one not deprecated value

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8076]
#### Issue Description
This enum is used in 42 places in production and in 27 tests. 

     enum AllocationMode {

        @Deprecated
        DIRECT,
        @Deprecated
        HEAP,
        @Deprecated
        JAVACPP,
        @Deprecated
        LONG_SHAPE, // long shapes will be used instead of int

        MIXED_DATA_TYPES, // latest generation of INDArrays support multiple data types, with information stored within shapeInfo "offset" field.
    }

We have a chance to get rid of this enum and all the code around it before the 1.0 release.

**Comment by raver119** [comment]
No way. It's used as generation for shape information. So used in backwards compatibility.
