### ISSUE TITLE
libnd4j: *pooling2d_bp ops can't handle different stride inputs

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8077]
See the following test cases. It's failing on the last assertEquals

https://gist.github.com/AlexDBlack/f075d26ed51c74270eee8f5472bbf29a

Why?
If input and output (i.e., input to pool2d and gradient at pooling op input - input and gradI args) have different strides, the offsets won't be correct and hence output will be wrong.
i.e., we're only taking into account 2 of the 3 necessary strides here.

https://github.com/eclipse/deeplearning4j/blob/923ab155837bdbd70973db5fc70362b4cbae3e60/libnd4j/include/ops/declarable/helpers/cpu/convolutions.cpp#L1866-L1873

Specifically, I think changes need to occur here:
* iStep2 and iStep3 should be based on input stride - not gradI strides
* the index calculation for gI (line 1925) needs to be based on gradI strides, not input strides (as it would be once iStep2/3 are updated)

For optimization, it might make sense to detect when input/gradI strides are the same and do what we currently do, and if not, do extra calculation.

I tried fixing it, couldn't get it to pass.

**Comment by raver119** [comment]
cc @shyrma

**Comment by AlexDBlack** [comment]
OK, so I'm still seeing this after @shyrma's changes... looked into it for quite a while and I have no idea why it's not passing:/

What I've checked (and everything looks fine)
* The C++ implementation for both average and max pooling (multiple times, thoroughly)
* My test cases (original ones posted above had an error in kernel size, but now corrected)
* Multi-threading (OMP_NUM_THREADS=1 still fails - and it's consistent)
* avgpool2d_bp op
* Java side (op context, etc)

I've also checked on 2 different computers, same result on both...

The other weird thing is that average pooling fails with permuted input array... which isn't even used for the average pool backprop op. The strides there should make zero difference, yet somehow they leak in and change the result...

**Comment by AlexDBlack** [comment]
Updated test cases:
https://gist.github.com/AlexDBlack/a803cb42a225f3d7fa352b5b0a03f1ff
https://gist.github.com/AlexDBlack/f76c9bf602de5f3ec19f30a88d967a9f

Note image in the second gist... bottom row of expected is bottom right of actual 3x3 blocks... right values, wrong location.

**Comment by raver119** [comment]
Fixed quite a while ago.
