### ISSUE TITLE
Pure Java nd4j with 0.4?

### ISSUE THREAD

**Issue by michaelmalak** [eclipse/deeplearning4j#8078]
I understand from https://github.com/deeplearning4j/nd4j/issues/835 and from other places that a pure Java nd4j for JVM-only environments is not presently available nor on the roadmap.

However, my question is whether it is possible to use dl4j/nd4j 0.4-rc3.6 to realize a pure Java solution? This appears to be the last version of the "nd4j-java" artifact on https://mvnrepository.com/artifact/org.nd4j/nd4j-java

My sbt file:

libraryDependencies ++= Seq(
  "org.deeplearning4j" % "deeplearning4j-nlp" % "0.4.0",
  "org.nd4j" % "nd4j-java" % "0.4-rc3.6"
)

But at runtime I get:

[error] java.lang.AbstractMethodError: org.nd4j.linalg.factory.Nd4jBackend.getConfigurationResource()Lorg/nd4j/linalg/io/Resource;
[error] 	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:128)

#### Version Information

* Deeplearning4j 0.4.0
* CentOS 7
* CUDA version: N/A
* NVIDIA driver version: N/A

**Comment by AlexDBlack** [comment]
Sorry, we aren't supporting a nearly 4 year old build of DL4J/ND4J. You're totally on your own if you want to try/use it.

I wouldn't recommend trying it or using it however, you'd be missing literally thousands of new features, bug fixes, and optimizations.
At one point yes, we did have pure java execution for operations, but I don't remember which version.
