### ISSUE TITLE
ND4J: Remove Nd4j.trueScalar/trueVector

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8087]
These methods were deprecated in beta4 (if not earlier).
I think we should be OK removing them for beta5.
For tests / existing uses:
trueScalar -> scalar
trueVector -> createFromArray

Also clean up these methods (note they are missing datatypes - the BaseNDArrayFactory.trueScalar method looks like what we need...)
https://github.com/eclipse/deeplearning4j/blob/68ea5f3688be9045cac3c06b1828b21262b22903/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseNDArrayFactory.java#L1382-L1427

**Comment by RobAltena** [comment]
Could not find a straightforward mapping, will have a closer look.

**Comment by RobAltena** [comment]
Almost done, just a few more dangling trueVectors to remove.
