### ISSUE TITLE
Can't create UNet with input height = 1

### ISSUE THREAD

**Issue by localmaxima** [eclipse/deeplearning4j#8089]
I am trying to create a Unet computation graph to train a model. Each record is WxHxD where W=367, H = 1, D=141. I copied my Unet graph from the Unet graph that comes with the zoo models but I changed it to use custom dimensions. 

If I use bigger values like 512x512x3, it works fine. I think the issue is with the H = 1.

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): spark cluster on ubuntu

Provided is a screenshot of the error message. 

![error](https://user-images.githubusercontent.com/7837524/63021334-a68fd680-bea0-11e9-9240-3efb81e602de.png)

I created a docker image to reproduce the error. All you have to do is clone this repo, checkout branch "1.0.0-beta4-unet-dim" and from the main folder run "docker-compose up"

https://github.com/localmaxima/dl4j-azure-minimal-example.git

**Comment by aelkayesh** [comment]
Given the amount of time spent to create such a ticket with all required tools setup(Docker/Spark...etc),  and given that it's been six months without even a comment or any reaction on my ticket, I will just close it and thank you guys for your past efforts.

**Comment by saudet** [comment]
That's probably been fixed in 1.0.0-beta6. If you find that the same issue still happens with more recent versions though, we will be pleased to take a look at it.

/cc @eraly @treo
