### ISSUE TITLE
Can't create computation graph that train on datasets on Azure storage

### ISSUE THREAD

**Issue by localmaxima** [eclipse/deeplearning4j#8090]
I am trying to create a Unet computation graph that should train on datasets stored on Azure but it fails with NullPointerException.

Please check attached screeshot:

![error](https://user-images.githubusercontent.com/7837524/63021835-c247ac80-bea1-11e9-9a62-6700c8ae837c.png)

* Deeplearning4j version:1.0.0-beta4
* Platform information (OS, etc): ubuntu

I created a docker image to reproduce the error. All you have to do is clone this repo, checkout branch "1.0.0-beta4-unet-comp_graph-azure" and from the main folder run "docker-compose up"

https://github.com/localmaxima/dl4j-azure-minimal-example.git

**Comment by aelkayesh** [comment]
Given the amount of time spent to create such a ticket with all required tools setup(Docker/Spark...etc),  and given that it's been six months without even a comment or any reaction on my ticket, I will just close it and thank you guys for your past efforts.

**Comment by sshepel** [comment]
@localmaxima have you tried the latest release of dl4j?
