### ISSUE TITLE
Nd4j: remove Nd4j.setNumThreads()/numThreads()

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8102]
These look unused, remnants of old java execution?
https://github.com/eclipse/deeplearning4j/blob/c29c011d1a74f9c0c6f67759a991b5734eb08790/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L6188-L6207

**Comment by raver119** [comment]
Yep, not used anymore.

**Comment by AlexDBlack** [comment]
https://github.com/SkymindIO/deeplearning4j/pull/110
