### ISSUE TITLE
Bibtex for citing deeplearning4j?

### ISSUE THREAD

**Issue by breandan** [eclipse/deeplearning4j#8111]
What is the appropriate way to cite DL4J/ND4J in an academic publication? Does this work?

```
@article{team2016nd4j,
    title={{ND4J: Fast, Scientific and Numerical Computing for the JVM}},
    author={Eclipse Deeplearning4j Development Team},
    year={2016},
    url = {https://github.com/eclipse/deeplearning4j},
}

@article{team2016dl4j,
    title={{DL4J: Deep Learning for Java}},
    author={Eclipse Deeplearning4j Development Team},
    year={2016},
    url = {https://github.com/eclipse/deeplearning4j},
}
```

**Comment by raver119** [comment]
cc @chrisvnicholson ^^^

**Comment by andreped** [comment]
This page states how to cite DL4J:
https://jrmerwin.github.io/deeplearning4j-docs/about

From this it states:

> Cite Eclipse Deeplearning4j
> If you plan to publish an academic paper and wish to cite Deeplearning4j, please use this format:
> Eclipse Deeplearning4j Development Team. Deeplearning4j: Open-source distributed deep learning for the JVM, Apache Software Foundation License 2.0. http://deeplearning4j.org
