### ISSUE TITLE
libnd4j: Implement updaters as C++ operations

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8114]
The math is all defined here: https://github.com/eclipse/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/learning

Implemented efficiently in c++ (i.e., with only one - or only few - memory passes) this should be an easy win for performance in both DL4J and SameDiff, and should be faster than the current Java implementations.

**Comment by raver119** [comment]
Implemented and merged
