### ISSUE TITLE
the need for NDArray bits operations 

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#8119]
Now there are CyclicRShiftBits, RShiftBits, etc. ops, it is fine. But they params are a ndarray and a scalar, the two ndarrays input params version are more useful, such as :
```
public CyclicRShiftBits(INDArray input, INDArray shift, INDArray output);
public RShiftBits(INDArray input, INDArray shift, INDArray output) ；//shift and input are same shape.
public BitsAnd(INDArray input1, INDArray  input2, INDArray output);
public BitsOr(INDArray input1, INDArray  input2, INDArray output);
public BitsXor(INDArray input1, INDArray  input2, INDArray output); //inputs are same shape.
public BitsNot(INDArray input, INDArray output);
```
These methods are more powerful because ndarray can implement scalar version functions.
#### Version Information

nd4j: 1.0.0-beta4

**Comment by raver119** [comment]
So, basically you want them to be broadcastable. Ok, sounds legit.

**Comment by cqiaoYc** [comment]
Yes, these ops are very useful. Another bit op:
the result is the different bit count (or rate) between input1 and input2. 
```
public double BitsHammingDistance(INDArray input1, INDArray  input2);
```
GCC has __builtin_popcount(), and CUDA has popcount intrinsics for 32-bit and 64-bit types: __popc() and __popcll(). These ops can count set bits.

**Comment by cqiaoYc** [comment]
@raver119 Can these ops be coming with beta5?

**Comment by raver119** [comment]
I've added bits_hamming_distance op impl yesterday.

**Comment by cqiaoYc** [comment]
> I've added bits_hamming_distance op impl yesterday.

@raver119 nice! thank you for your work! For me, other operations are also necessary.

**Comment by raver119** [comment]
Implemented
