### ISSUE TITLE
AggregatingSentenceIterator.addSentencePreProcessor() doesn't actually add

### ISSUE THREAD

**Issue by cowwoc** [eclipse/deeplearning4j#8122]
#### Issue Description

Please describe our issue, along with:
- expected behavior: Invoking `AggregatingSentenceIterator.addSentencePreProcessor()` should add multiple pre-processors.
- encountered behavior: The last pre-processor overwrites the previous values.

This is counter-intuitive given the method name. Either rename the method or support multiple pre-processors.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): N/A
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by AlexDBlack** [comment]
Thanks for reporting - fixed here (deprecated method + added better named method), will be merged to eclipse/deeplearning4j master soon.
https://github.com/SkymindIO/deeplearning4j/pull/141
