### ISSUE TITLE
SameDiff/Libnd4j: TensorMMul issues

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8128]
[`TensorMMul`](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/reduce/TensorMmul.java) needs a look, from https://github.com/eclipse/deeplearning4j/issues/7901#issuecomment-523406758.

>  TF import name is wrong - should be "MatMul" which already maps to Mmul op

> C++ shape function doesn't appear to use the transpose argument, Java shape function does.

**Comment by shyrma** [comment]
Hi rnett

c++ tensormmul operation doesn't use transpose arguments.
This operation corresponds to tf.tensordot which is also without transpose arguments.

**Comment by raver119** [comment]
Yep. File a separate issue for backprop please. As for other things - totally agree.
Also, can you please add graph import test for new mapped name once you have it please? Just to make sure we're on the same page with TF here.

**Comment by rnett** [comment]
@raver119 via https://github.com/SkymindIO/deeplearning4j/pull/193#discussion_r318870186, it looks like there is no TF import.
