### ISSUE TITLE
Libnd4j: Eye shape function ignored dtype

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8129]
Currently, the java-side `calculateOutputShape` calls the C++ function and then sets the dtype of the first returned shape.  This should be done on the C++ side.

See: https://github.com/SkymindIO/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/transforms/eye.cpp#L47-L49

See https://github.com/eclipse/deeplearning4j/issues/7901#issuecomment-523406758.

**Comment by shyrma** [comment]
Hi rnett

c++ tensormmul operation doesn't use transpose arguments.
This operation corresponds to tf.tensordot which is also without transpose arguments.

**Comment by shyrma** [comment]
Hi rnett

issue has been fixed. User should pass dtype parameter as float argument.
Use following enum/numbers for data types

**Comment by raver119** [comment]
https://github.com/SkymindIO/deeplearning4j/blob/ef8cb55b7b2db7c2e5ec2c4c37cc622e7838fe40/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/DataType.java#L57

**Comment by raver119** [comment]
Added.
