### ISSUE TITLE
DL4J: SpaceToBatch layer incorrect gradients

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8133]
When blocks are > [1,1] the gradient is off by a factor of prod(blocks)
This seems to be due to the fact that SpaceToBatch changes the minibatch size for subsequent layers, including the output layer.
This may just be a problem with the gradient check util, however.

This doesn't look to be a new issue, just our previous tests weren't thorough enough to catch it.

**Comment by raver119** [comment]
cc @shyrma

**Comment by AlexDBlack** [comment]
I'm about 80% sure the op is fine, it's likely just a quirk of DL4J score vs. gradient calculation with non-constant minibatch size
