### ISSUE TITLE
DL4J: Improve WordVectorSerializer usability

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8137]
There's a number of usability-related improvements we need here

- No JavaDoc on a lot of methods
- We should pull methods like readFloat, getFloat, readString etc out into a separate utility method to avoid cluttering the API
- We need to clearly specify somewhere (class javadoc?) the different formats and methods, and what users should use for different purposes (so they don't need to read through all of the different method javadocs to find what they need)

**Comment by alexanderst** [comment]
Fixed and merged.
