### ISSUE TITLE
JVM crash with CUDA error: NativeOps.cu:1903 code=700(<unknown>) "dZ" 

### ISSUE THREAD

**Issue by wiku** [eclipse/deeplearning4j#8142]
#### Issue Description
Hi,

I'm optimizing hyperparameters of a computation graph and training multiple networks one after another. Every 10-20 trainings I'm getting a JVM crash with below error:
```
2019-08-23 22:51:06 [AMDSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 4
CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.1/libnd4j/blas/cuda/NativeOps.cu:1903 code=700(<unknown>) "dZ" 
*** Error in `/usr/lib/jvm/java-8-openjdk-amd64/bin/java': free(): invalid next size (fast): 0x00007fe89b050f00 ***
```

#### Version Information

* Deeplearning4j version: 
1.0.0-beta4

* Platform information (OS, etc)
Ubuntu 16.04, GeForce RTX 2070

CUDA version: 
10.1

NVIDIA driver version: 
418.67

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
https://gist.github.com/wiku/9feb738b33d916338439b56301ab57cb 

Note: I am using a custom DataSetIterator, creating INDArrays on the fly by calling Nd4j.create(float[], int[]) 

I'd be extremely grateful if you could give me any hints what could be wrong. Could it be a hardware issue?

**Comment by amcelroy** [comment]
+1, I'm seeing this also on a 2 GPU setup, though I'm only running a single GPU using CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(false) to try and track it down.

**Comment by raver119** [comment]
Please try latest snapshot.

**Comment by raver119** [comment]
Also, if you’re on cuda 10.1 and using snapshots - please make sure you’re using latest cuda 10.1 update 2

**Comment by wiku** [comment]
Big thanks for your support! I've reinstalled my drivers and upgraded Cuda to update 2 and after that this particular issue doesn't occur any more (well, the jvm still sporadically crashes, but now in a different way - maybe I'll open another issue for that, but for now its no longer that urgent).
