### ISSUE TITLE
Problem when using CUDA

### ISSUE THREAD

**Issue by iluvmf** [eclipse/deeplearning4j#8146]
#### Issue Description

I was training my neural network with cpu before but it was quite slow so I decided to go with gpu.  I installed cuda toolkit and restarted my pc but still get an exception.  Before installing cuda toolkit, I was not getting as far I I get now, it is now showing "Loaded [JCublasBackend] backend" and also "Number of threads used for NativeOps: 32", but after that I get the exception.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version is: 1.0.0-beta4

* Windows 10

* CUDA version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

* NVIDIA driver version is: 25.21.14.2600

#### Additional Information

* Full log or exception stack trace:
https://gist.github.com/iluvmf/8f9f9b1a4f61c3a8ed26947e746605da
* pom.xml file:
https://gist.github.com/iluvmf/8f9f9b1a4f61c3a8ed26947e746605da
#### Contributing

Not entirely sure why I get this error after installing cuda toolkit and restarting my pc.  If you guys have any idea, let me know! 

Thank you and have a good day!

**Comment by iluvmf** [comment]
Just found a fix by adding this to my pom file:

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>windows-x86_64-redist</classifier>
        </dependency>

**Comment by raver119** [comment]
Both links you've posted are the same. Please show exception :)

**Comment by iluvmf** [comment]
https://gist.github.com/iluvmf/f72f0115e81a45f924dea23304ed7e14
My mistake, wrong copy paste.
