### ISSUE TITLE
ND4J Tests - TF import tests initialization is slow, and slower on CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8148]
TFGraphTestAllSameDiff relies on classpath scanning to discover test cases.
This scanning takes some time.
One odd thing that I have noticed is that the scanning/initialization takes considerably longer on the CUDA backend. This only makes sense if the arrays were actually being loaded at this point or something (instead of only when the test runs), which should not be happening.

**Comment by AlexDBlack** [comment]
Improved somewhat with this: https://github.com/SkymindIO/deeplearning4j/pull/183

Still nearly 2 minutes to initialize the parameterized test cases for CUDA testing.

I also noticed that we're loading all of the array into memory at once for these tests. This isn't a problem yet (the tests are small), but it's not ideal from a memory point of view.
Loading the arrays lazily during the test would be a better idea, though it probably won't make any difference to the overall runtime of the tests (same arrays need to be loaded either way...)

**Comment by raver119** [comment]
Ideally long-term solution would be test framework that runs directly from Python. 
In this way we could solve multiple problems at once:
1) tests that use huge arrays/graphs might be generated on the fly, rather than stored somewhere
2) there will be nothing to initialize :)
