### ISSUE TITLE
Deconvolution2D with ConvolutionMode.Same output is 0

### ISSUE THREAD

**Issue by iltie165** [eclipse/deeplearning4j#8149]
When I build a simple model with Deconvolution2D layer and set ConvolutionMode = 'Same', 
the model output is always zero regardless of input.
Here is my model config:
```
ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
                .seed(123)
                .weightInit(new NormalDistribution(0, 0.02))
                .updater(new Adam(0.0002, 0.5, Adam.DEFAULT_ADAM_BETA2_VAR_DECAY, Adam.DEFAULT_ADAM_EPSILON))
                .graphBuilder()
                .addInputs("ramdon-z")
                .appendLayer("pj-layer", new DenseLayer.Builder()
                        .nIn(this.inputDim)
                        .nOut(4 * 4 * 512)
                        .activation(Activation.IDENTITY)
                        .build())
                .appendLayer("decv512-layer", new Deconvolution2D.Builder()
                        .kernelSize(5, 5)
                        .stride(2, 2)
                        .convolutionMode(ConvolutionMode.Same)
                        .nIn(512)
                        .nOut(256)
                        .activation(Activation.IDENTITY)
                        .build(), new FeedForwardToCnnPreProcessor(4, 4, 512))
                .appendLayer("img-output-layer", new Deconvolution2D.Builder()
                        .kernelSize(5, 5)
                        .stride(2, 2)
                        .convolutionMode(ConvolutionMode.Same)
                        .nIn(256)
                        .nOut(128)
                        .activation(Activation.IDENTITY)
                        .build())
                .setOutputs("img-output-layer")
                .build();
```
and my input is a random Array:
```
INDArray randomZ = Nd4j.rand(new long[]{16, 100}, new 
          org.nd4j.linalg.api.rng.distribution.impl.NormalDistribution(0, Math.exp(-1 / Math.PI)));
       
Map<String, INDArray> res = generator.model.feedForward(randomZ, true);

```
The output of "img-output-layer" is always zero.
os: mac osx
dl4j version: 1.0.0-beta4

**Comment by iltie165** [comment]
> I don't think this is a bug. You're starting with a small number (your random) then multiplying by three other small numbers (initialized weights).
> 
> If you try using just one deconv layer, you get a nonzero output (although quite small, with a large number of zeros).
> 
> ```java
> ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
>         .seed(123)
>         .weightInit(new NormalDistribution(0, 0.02))
>         .updater(new Adam(0.0002, 0.5, Adam.DEFAULT_ADAM_BETA2_VAR_DECAY, Adam.DEFAULT_ADAM_EPSILON))
>         .graphBuilder()
>         .addInputs("ramdon-z")
>         .appendLayer("pj-layer", new DenseLayer.Builder()
>                 .nIn(100)
>                 .nOut(4 * 4 * 512)
>                 .activation(Activation.IDENTITY)
>                 .build())
>         .appendLayer("img-output-layer", new Deconvolution2D.Builder()
>                 .kernelSize(5, 5)
>                 .stride(2, 2)
>                 .convolutionMode(ConvolutionMode.Same)
>                 .nIn(512)
>                 .nOut(128)
>                 .activation(Activation.IDENTITY)
>                 .build(), new FeedForwardToCnnPreProcessor(4, 4, 512))
>         .setOutputs("img-output-layer")
>         .build();
> ```
> 
> Now if this happens after training, it is definitely a bug.

Thank for you reply.
Indeed one layer can output nonzero value, and there is large zero values. But the output is very strange, according to 'deconv' algorithm. 
If not set ConvolutionMode = Same, you can find the layer output can be pretty good.

At last, I have tried the same network with 'tensorflow'.  Output is nonzero.

**Comment by AlexDBlack** [comment]
This is an odd choice of configuration, dense before deconv.
Not sure yet if there is a legitimate issue here or not, but 98304 of 131072 output values are zero, and that's not just numerical underflow (still happens with larger input + larger weight init). That seems suspicious, given the way deconv works.

https://gist.github.com/AlexDBlack/3d0238d4444e437ea3c263376f9df561

**Comment by iltie165** [comment]
> This is an odd choice of configuration, dense before deconv.
> Not sure yet if there is a legitimate issue here or not, but 98304 of 131072 output values are zero, and that's not just numerical underflow (still happens with larger input + larger weight init). That seems suspicious, given the way deconv works.
> 
> https://gist.github.com/AlexDBlack/3d0238d4444e437ea3c263376f9df561

At the beginning this issue appeared when I build a DCGAN. I find no matter how training the generator, it always output zero. 
With debugging the code, I find when set 'ConvolutionMode = Same' 'deconv' output become strange. But I am not familiar with C++, so I may not be able to solve the problem.  Sorry.

**Comment by iltie165** [comment]
> ```java
>         SameDiff sd = SameDiff.create();
>         SDVariable input = sd.constant(Nd4j.linspace(0, 256, 256).reshape(1, 4, 8, 8));
>         SDVariable weight = sd.var("W", new UniformInitScheme('c', 256), DataType.FLOAT,
>                 5, 5, 2, 4);
>         SDVariable out = sd.cnn.deconv2d(input, weight, DeConv2DConfig.builder().kH(5).kW(5).sH(2).sW(2).isSameMode(true).build());
> 
>         INDArray outArr = out.eval();
> 
>         System.out.println(outArr);
>         System.out.println(Arrays.toString(outArr.shape()));
> ```

So, it may be the reason which more than one 'deconv' ops with padding output always zeros. 
```
    @Test
    public void testDeconv2d(){
        SameDiff sd = SameDiff.create();
        SDVariable input = sd.constant(Nd4j.linspace(0, 256, 256).reshape(1, 4, 8, 8));
        SDVariable weight = sd.var("W", new UniformInitScheme('c', 256), DataType.FLOAT,
                5, 5, 2, 4);
        SDVariable out = sd.cnn.deconv2d(input, weight, DeConv2DConfig.builder().kH(5).kW(5).sH(2).sW(2).isSameMode(true).build());

        SDVariable weightAfterDeconvWithPadding = sd.var("W2", new UniformInitScheme('c', 256), DataType.FLOAT,
                5, 5, 1, 2);
        SDVariable outAfterDeconvWithPadding = sd.cnn.deconv2d(out, weightAfterDeconvWithPadding,
                DeConv2DConfig.builder().kH(5).kW(5).sH(2).sW(2).isSameMode(true).build());

        INDArray outArr = out.eval();

        INDArray outArrAfterDeconv = outAfterDeconvWithPadding.eval();

        System.out.println(outArr);
        System.out.println(Arrays.toString(outArr.shape()));

        System.out.println(String.format("double deconv output max: %f, min: %f, std: %f",
                outArrAfterDeconv.maxNumber().floatValue(),
                outArrAfterDeconv.aminNumber().floatValue(),
                outArrAfterDeconv.stdNumber().floatValue()));
    }
```
Gives:
```
double deconv output max: 0.000000, min: 0.000000, std: 0.000000
```

**Comment by AlexDBlack** [comment]
Recently fixed here: https://github.com/KonduitAI/deeplearning4j/pull/12
Same issue as: https://github.com/eclipse/deeplearning4j/issues/8298
