### ISSUE TITLE
ND4J: INDArray interface - deprecated method cleanup

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8150]
INDArray:
- javaTensorAlongDimension (replace uses with tensorAlongDimension)
- get(List<List<Integer>>) (only one ignored test using this)
- setStride, setShape (delete, only use in 1 unused method, NDArrayIndex.updateForNewAxis - delete that also)
- lengthLong() (replace with length())

cc @RobAltena 

Edit: I already checked beta4, they were deprecated there, if not an earlier release.

**Comment by RobAltena** [comment]
Let me list other candidates for deletion here. We will take them out at an appropriate time.
double getDoubleUnsafe(long offset);

**Comment by AlexDBlack** [comment]
Done - thanks @RobAltena
