### ISSUE TITLE
Build error: ld undefined reference to GOMP

### ISSUE THREAD

**Issue by michaelmalak** [eclipse/deeplearning4j#8158]
Trying to build for the first time. Fedora 30, fresh install/VM:

> sudo yum install maven make cmake g++

> [ 98%] Building CXX object tests_cpu/layers_tests/CMakeFiles/runtests.dir/VariableSpaceTests.cpp.o
> [ 98%] Building CXX object tests_cpu/layers_tests/CMakeFiles/runtests.dir/VariableTests.cpp.o
> [ 98%] Building CXX object tests_cpu/layers_tests/CMakeFiles/runtests.dir/WorkspaceTests.cpp.o
> [100%] Linking CXX executable runtests
> /usr/bin/ld: CMakeFiles/runtests.dir/PlaygroundTests.cpp.o: in function `PlaygroundTests_loopThroughArrs_test1_Test::TestBody() [clone ._omp_fn.1]':
> PlaygroundTests.cpp:(.text+0x13cb): undefined reference to `GOMP_loop_nonmonotonic_guided_start'
> /usr/bin/ld: PlaygroundTests.cpp:(.text+0x1496): undefined reference to `GOMP_loop_nonmonotonic_guided_next'
> /usr/bin/ld: CMakeFiles/runtests.dir/PlaygroundTests.cpp.o: in function `PlaygroundTests_loopThroughArrs_test1_Test::TestBody() [clone ._omp_fn.0]':
> 
> ...
> 
> collect2: error: ld returned 1 exit status
> make[2]: *** [tests_cpu/layers_tests/CMakeFiles/runtests.dir/build.make:1378: tests_cpu/layers_tests/runtests] Error 1
> make[1]: *** [CMakeFiles/Makefile2:687: tests_cpu/layers_tests/CMakeFiles/runtests.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] deeplearning4j 1.0.0-SNAPSHOT ...................... SUCCESS [  4.426 s]
> [INFO] libnd4j ............................................ FAILURE [  01:39 h]
> [INFO] nd4j ............................................... SKIPPED
>

**Comment by saudet** [comment]
You'll to build all dependencies with GCC 9.x as well for this to work.
