### ISSUE TITLE
UnsupportedKerasConfigurationException

### ISSUE THREAD

**Issue by dyoann** [eclipse/deeplearning4j#8162]
Hello,

I've build a model with keras (python) using this kind of model :

```
base_model = tf.keras.applications.MobileNetV2(input_shape=(224,224),  include_top=False,weights='imagenet')
base_model.trainable = False

model = tf.keras.Sequential([
  base_model,
  keras.layers.GlobalAveragePooling2D(),
  keras.layers.Dense(4, name='out_dense'),
  keras.layers.Activation('sigmoid', name='out_activation')
])
model.compile(optimizer=keras.optimizers.RMSprop(lr=0.0001), 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
```

However, when I load the model in Java with the code :
```
String modelPath = new ClassPathResource("./end_model.h5").getFile().getPath();
MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(modelPath);
```

I get the error : org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Model. Please fill an issue at ...

Do you have any idea what is wrong in my model ?
Maybe it's MobileNetV2 layer that is not supported ? According to the documentation GlobalAveragePooling2D, Dense and Activation should be supported

Thanks !

**Comment by chambersliu** [comment]
@dyoann I came across the same issue with u, have u solved the issue?

**Comment by dyoann** [comment]
Sorry I didn't :/ ...
I end up grabing the model result directly from a python server (using REST)

**Comment by chambersliu** [comment]
@dyoann I found that Unsupported keras layer type: **Model**  means fixed layer structures, but not a single layer,  for example, mobilenet-v2, which seems not supported by keras java api, you can find supported layers in class:org.deeplearning4j.nn.modelimport.keras.config.KerasLayerConfiguration

**Comment by agibsonccc** [comment]
Found the above script wasn't valid:
```
import tensorflow as tf
import keras
base_model = tf.keras.applications.MobileNetV2(input_shape=(224,224,3),  include_top=False,weights='imagenet')
base_model.trainable = False

model = tf.keras.Sequential([
  base_model,
  tf.keras.layers.GlobalAveragePooling2D(),
  tf.keras.layers.Dense(4, name='out_dense'),
  tf.keras.layers.Activation('sigmoid', name='out_activation')
])
model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.save('end.h5',save_format='h5')
```

We need to add "Model" support to our import in order for this to work. Nested models need to be unrolled. 

Closing this in favor of: https://github.com/eclipse/deeplearning4j/issues/9108
