### ISSUE TITLE
A Probable Memory Leakage Problem

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#8165]
#### Issue Description

When my application (GA + LSTM) started, it took 2.5 minutes per 10 generations, but after 1800, it took 8 minutes. No improvement, when I removed the set up:
```
Nd4j.getMemoryManager().togglePeriodicGc(true);
Nd4j.getMemoryManager().setAutoGcWindow(500);
```
the result of jmap:
![内存占用图](https://user-images.githubusercontent.com/29296200/63902940-4e2f0c00-ca3e-11e9-914e-0b3405af68c9.JPG)

ConcurrentHashMap is not used in my app.

#### Version Information

* Deeplearning4j version : 1.0.0-beta4
* Platform information (OS, etc) : centos 7.6
* CUDA version, 10.0

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Given that number of objects, it's probably garbage collection overhead.
Is there anything special about your app, in terms of multi-threading, storing a bunch of different networks/arrays in memory, or anything like that?

**Comment by cqiaoYc** [comment]
Yes, there are 6 gpus with 6-threads in my app, storing about 2000 network params, and other arrays, but one network per a thread. 
about snapshots, there is not cuda- linux-x86_64.jar, so can not be used. 
I am currently using ubyte type ndarray with the shape of [16, netParams] to simulate bit operations of uint16 ndarray with the shape of [1, netParams] . If there are broadcasting bit operations, the performance of my app can be greatly improved. I desperately need them. I hope they are in beta 5. 
the bit ops as :https://github.com/eclipse/deeplearning4j/issues/8119

**Comment by cqiaoYc** [comment]
Without the setup:
```
Nd4j.getMemoryManager().togglePeriodicGc(true);
Nd4j.getMemoryManager().setAutoGcWindow(500);
```
Processes may be killed ,and no other prompts.

**Comment by raver119** [comment]
I highly doubt there's a leak. Show your source code please.

**Comment by cqiaoYc** [comment]
My source is too long. From the result of  jmap op, the classes that occupy a lot of memory are not written by me, and  the container class with large memory usage is not directly used by me. Leakages are most likely caused by improper use of container classes.

**Comment by raver119** [comment]
Huh... That doesn't help. You're seeing symptom here, and making assumptions based on class names. That's not how it works. Leaks in java are only possible when you keep references to objects, preventing GC from collecting garbage.

**Comment by AlexDBlack** [comment]
I will add that another way to debug this sort of leak is to use memory dump in tools such as yourkit java profiler. That should show you the classes that are holding the references to all of those objects.
If we had a screenshot of that, it would help us isolate this.

**Comment by raver119** [comment]
yourkit dump would work, yea

**Comment by cqiaoYc** [comment]
yourkit screenshot:
![内存分析1](https://user-images.githubusercontent.com/29296200/63988086-31153e80-cb0d-11e9-831c-c51bbbbcf2e1.JPG)

AbstractIndividual objections are stored in object pools (one pool per thread). They have big ndarrays (shape=[16,netParams]).
the code to type converting:
```
    INDArray netParamArray = allNetParamParts.castTo(DataType.INT).mul(getPartWeights(getGpuId()));
        netParams = netParamArray.sum(0);  //convert [16,netParams] ubyte values to [1,netParams] uint16
        
        netParams = netParams.castTo(DataType.FLOAT);        
        netParams.muli(paramsScaleFactor).subi(maxWeight);
        netParams = netParams.castTo(DataType.HALF);
```
If using bit ops, the first two lines of code can be optimized. the after code map int type values to HALF values.

**Comment by AlexDBlack** [comment]
Can you provide the actual dump file?
That screenshot you've provided only shows a small fraction of what we need here...

**Comment by cqiaoYc** [comment]
the size of  .snapshot file is 5.7G. How to send it to you?

**Comment by AlexDBlack** [comment]
Hm... in that case, maybe provide screenshots (of the paths) like you did earlier, for the following object types:
* ConcurrentHashMap$Node
* AllocationPoint
* CudaPointer
* CudaFloatDataBuffer
* FloatPointer
* String

**Comment by cqiaoYc** [comment]
screenshots:
![内存分析2](https://user-images.githubusercontent.com/29296200/63990266-fc59b500-cb15-11e9-9054-5ed2fb6680b8.JPG)
![内存分析3](https://user-images.githubusercontent.com/29296200/63990273-01b6ff80-cb16-11e9-814a-2e08d7c3f2fe.JPG)
![内存分析4](https://user-images.githubusercontent.com/29296200/63990283-07144a00-cb16-11e9-98ef-053aecb73e35.JPG)
![内存分析5](https://user-images.githubusercontent.com/29296200/63990295-0c719480-cb16-11e9-976c-c7d3c55b33df.JPG)
![内存分析6](https://user-images.githubusercontent.com/29296200/63990300-109db200-cb16-11e9-84f7-80f65c3c2036.JPG)
![内存分析7](https://user-images.githubusercontent.com/29296200/63990307-14313900-cb16-11e9-877d-9472941373f1.JPG)

**Comment by raver119** [comment]
So, to be clear:

With periodicGc enabled - application doesn't go oom, just slows down.
Without periodicGc enabled - you see this in heap. 

Am i getting this properly?

**Comment by cqiaoYc** [comment]
No, this is with periodicGc enabled. Without periodicGc enabled, app may be killed soon after starting.

**Comment by raver119** [comment]
> With periodicGc enabled - application doesn't go oom
?

**Comment by cqiaoYc** [comment]
Yes, the setup:
Nd4j.getMemoryManager().togglePeriodicGc(true);
Nd4j.getMemoryManager().setAutoGcWindow(600);
app can run more 2days, just slows down.

**Comment by AlexDBlack** [comment]
Looking at these screenshots and going by your description, we're about 95% sure that this is leaked references in your code.
i.e., you have some map, list, array, etc that's storing a bunch of INDArrays, that can't be garbage collected.
That's the only possible explanation here.

We can't say much beyond that without seeing actual code or having some way to run/reproduce this.

**Comment by cqiaoYc** [comment]
a bunch of INDArrays are stored in object pool (ConcurrentLinkedQueue), as:
![内存分析8](https://user-images.githubusercontent.com/29296200/63996777-2f5c7280-cb2f-11e9-9751-1c4d36cf4a9d.png)

**Comment by cqiaoYc** [comment]
Previous single GPU versions had no such problems. There are two suspicious methods.
One is copy ndarray from other thread:
```
 public INDArray copyNetParamPartsFromOtherGPU() {
         return Nd4j.createFromArray(allNetParamParts.data().asInt()).castTo(DataType.UBYTE);
}
```
Must change allNetParamParts.data().asInt() to allNetParamParts.data().dup().asInt()? or Arrays.copyOf(allNetParamParts.data().asInt(), netParamsCount)? 
There is a little problem: DataBuffer.array() return the backing array, and not the buffer itself. **Suggestions for providing a method: DataBuffer.array(DataType dataType).**

Another is sharing data among GPUs:
```
private Map<Integer, INDArray> features3D = new HashMap<>();
public INDArray getFeatures3D(int GpuId) {
        INDArray features3DArray = features3D.get(GpuId);
        if (features3DArray == null) {
            synchronized (features3D) {
                features3DArray = features3D.get(GpuId);
                if (features3DArray == null) {
                    build(GpuId, dataSets);
                    features3DArray = features3D.get(GpuId);
                }
            }
        }
        return features3DArray;
    }
```
Here GpuId is same as threadId. this object is used as a static object.
