### ISSUE TITLE
Libnd4j/Nd4j: ELU doesn't support alpha

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8179]
The DL4J `ActivationELU` supports an alpha parameter, while the C++ and Java ops don't.  Ideally the op would support this and we wouldn't have to do the extra `mul` and `replaceWhere` ops.

https://github.com/SkymindIO/deeplearning4j/blob/00fd50cee21636113f5a4b5c56fbb39762185bb2/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/activations/impl/ActivationELU.java#L56-L92

**Comment by AlexDBlack** [comment]
Added recently
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/activations/elu.cpp
