### ISSUE TITLE
INDArray Defulat Precision is Float16，How to to Float32

### ISSUE THREAD

**Issue by blackhu** [eclipse/deeplearning4j#8190]
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
INDArray default precision is Float32.  You're probably just looking into INDArray.toString() output, which is formatted with limited precision. Data itself is fine.

**Comment by blackhu** [comment]
> INDArray default precision is Float32. You're probably just looking into INDArray.toString() output, which is formatted with limited precision. Data itself is fine.

But I used 
```
        NativeImageLoader loader = new NativeImageLoader(224, 224, 3,new ColorConversionTransform(COLOR_BGR2RGB));
```
Output is:
```
[[[[    0.7451,    0.7451,    0.7569  ...    0.7529    0.7686,    0.7647], 
   [    0.7529,    0.7569,    0.7608  ...    0.7608    0.7608,    0.7647], 
   [    0.7412,    0.7647,    0.7569  ...    0.7608    0.7529,    0.7529], 
    ..., 
```
My python used "img_to_array" output is:
```
[[[[0.74509805 0.74509805 0.75686276 ... 0.7529412  0.76862746
    0.7647059 ]
   [0.7529412  0.7607843  0.7607843  ... 0.7607843  0.7607843
    0.7647059 ]
   [0.7411765  0.7607843  0.75686276 ... 0.7647059  0.7529412
    0.7607843 ]
   ...
```

**Comment by raver119** [comment]
Right, that's truncation during printout. It's built into INDArray.toString(). That doesn't reflect anything real related to the data.

If you want - get data from your INDArray as floats, and you'll see it's the same as you expect. 

You can also check INDArray.dataType(), it'll show real data type of your INDArray.

**Comment by blackhu** [comment]
Think you very much. I got it.
