### ISSUE TITLE
Nd4j/Libnd4j: Eventually support passing gate activation functions to RNNs

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8197]
For parity with [DL4J](https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/AbstractLSTM.java#L100-L109) and [Tensorflow](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTMCell), we need to support passing activation functions to the RNN cells and layers.

**Comment by rnett** [comment]
If I'm reading the issues about making a new lstm op for MKL-DNN and CUDA, neither support custom activations, so this may be irreverent.  It would be nice to have some support for this (and for tensorflow import), but isn't a priority.

**Comment by AlexDBlack** [comment]
We don't need this for TF import as far as I can tell, the TF RNN layers that support this are implemented manually in python, not as optimized fused ops: https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py

We *do* need it for ONNX import, however: https://github.com/eclipse/deeplearning4j/issues/8070
But I'll close this, issues for GRU etc import for ONNX will be opened later (like the aforementioned issue, this will require careful analysis before making any changes or implementing any new ops).
