### ISSUE TITLE
Libnd4j: support for optional LSTM weights

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8198]
For `lstmCell`, `Wc` and `Wp` aren't used unless the peephole or projection options are set, respectively.  We should support not passing them (either on the current lstm ops, or the new one mentioned in other issues).

`lstmBlock` and `lstmBlockCell` have a similar issue with peephole weights.

**Comment by AlexDBlack** [comment]
We can't modify lstmBlockCell as it's used for TF import. Here's an example with use_peephole==false, but arrays are still created. Not a good design choice IMO.

https://gist.github.com/AlexDBlack/7f2d1a1588f9a0642bf9a9f945a1c6a5

lstmCell we *can* modify but it's low priority.

The main LSTM implementation we'll use in the future is this one: https://github.com/eclipse/deeplearning4j/issues/8070

**Comment by AlexDBlack** [comment]
New LSTM op supports optional weights.
https://github.com/eclipse/deeplearning4j/issues/8070
