### ISSUE TITLE
Libnd4j: gru layer/time loop op

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8199]
The `gru` layer/time loop op exists, but the important parts are commented out.

https://github.com/SkymindIO/deeplearning4j/blob/master/libnd4j/include/ops/declarable/helpers/cpu/gru.cpp#L151-L152

Additionally, the `gru` ops takes its bias differently than `gruCell` (one `[3*numUnits]` array vs a `[2*numUnits]` array and a `[numUnits]` array), these should match (it makes things easier Java-side).

**Comment by raver119** [comment]
Implemented, will be merged later today.
