### ISSUE TITLE
doc2vec implementation

### ISSUE THREAD

**Issue by ErikTromp** [eclipse/deeplearning4j#82]
More of a wish of mine (who supports?) is to have an implementation of the doc2vec (Paragraph vector) algorithm, which extends word2vec to create a fixed-length vector of a document of variable length. Note that the Python library gensim already has this implemented https://github.com/ccri/gensim/blob/develop/gensim/models/doc2vec.py) but it would be nice to have it as native Java in DL4J too.

**Comment by pommedeterresautee** [comment]
For what it means, they are adding inference for new documents in doc2vec Gensim implementation. They discuss about it their:
https://groups.google.com/forum/#!topic/gensim/EFy1f0QwkKI

Link to the commit:
https://github.com/gojomo/gensim/commit/ea93e666083221db30adeea97ed0d7af7187b715

Seems interesting (but not yet tested the fork).

**Comment by agibsonccc** [comment]
Please feel free to open up an issue for a feature request.

**Comment by pommedeterresautee** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/263
