### ISSUE TITLE
Libnd4j: RNN backprop ops for gru (and maybe lstm)

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8200]
Not urgent, but we're going to want them eventually.

Current missing backprop ops:
`gru` (time series, cell has one).  See #8199.
`lstmBlock`, `lstmBlockCell`.  May want to wait until the new lstm op.

Is #5504 still relevant (has the gru cell bp been tested)?

**Comment by raver119** [comment]
Implemented, will be merged later today.
