### ISSUE TITLE
DataVec: Add NHWC support for ImageRecordReader / NativeImageLoader

### ISSUE THREAD

**Issue by blackhu** [eclipse/deeplearning4j#8201]

**Comment by saudet** [comment]
At the moment, this is hard coded, but we can use NDArray.reshape() on the arrays returned by NativeImageLoader as a post-processing step.

**Comment by blackhu** [comment]
> At the moment, this is hard coded, but we can use NDArray.reshape() on the arrays returned by NativeImageLoader as a post-processing step.

But reshape cannot reshape result is (height,weight,channel)

**Comment by AlexDBlack** [comment]
You want permute, not reshape.

```
INDArray nhwc = imgNchw.permute(0,2,3,1);
```

**Comment by blackhu** [comment]
> ```
> INDArray nhwc = imgNchw.permute(0,2,3,1);
> ```

That's ok. Thank you very much
