### ISSUE TITLE
Remote UI example exception

### ISSUE THREAD

**Issue by eraly** [eclipse/deeplearning4j#8203]
Current master in SkymindIO branch crashes the remote UI example in dl4j-examples

https://gist.github.com/eraly/ea2176926db93214f61fa42ef543f57a

**Comment by AlexDBlack** [comment]
I'm not able to reproduce this (branch: ab_beta5)
But I did pick up and fix a separate issue with this example: https://github.com/SkymindIO/deeplearning4j/pull/242
