### ISSUE TITLE
 the bits_hamming_distance method can cause JAVA VM to crash.

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#8207]
```
INDArray x = Nd4j.createFromArray(new int[][]{{0b01011000, 0b01011111, 0b01111110}}).castTo(DataType.UINT16);
INDArray y = Nd4j.createFromArray(new int[][]{{0b00010110, 0b01011000, 0b01011000}}).castTo(DataType.UINT16);
INDArray out = Nd4j.create(DataType.UINT64);
Nd4j.exec(DynamicCustomOp.builder("bits_hamming_distance")
                .addInputs(x, y)
                .addOutputs(out)                
                .build());
```
ND4J CUDA build version: 10.0.130
CUDA device 0: [GeForce 920M]; cc: [3.5]; Total memory: [2147483648];

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffeb778a839, pid=17576, tid=0x0000000000000810

 JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [KERNELBASE.dll+0x3a839]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
[hs_err_pid17576.log](https://github.com/eclipse/deeplearning4j/files/3581857/hs_err_pid17576.log)

#### Version Information
Deeplearning4j 1.0.0-SNAPSHOT
Platform information : win10
CUDA version,10.0

**Comment by raver119** [comment]
Good catch. thank you. It's fixed now.

But, once release hits: please use either int or long output data type for this op.
