### ISSUE TITLE
Nd4j example crash (hstack)

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8218]
#### Issue Description
    @Test
    void testSampleCrash() {
        INDArray rowVector1 = Nd4j.create(new double[]{1,2,3});
        INDArray rowVector2 = Nd4j.create(new double[]{4,5,6});

        INDArray vStack = Nd4j.vstack(rowVector1, rowVector2);      //Vertical stack:   [1,3]+[1,3] to [2,3]
        INDArray hStack = Nd4j.hstack(rowVector1, rowVector2);      //Horizontal stack: [1,3]+[1,3] to [1,6]
        System.out.println("\n\n\nCreating INDArrays from other INDArrays, using hstack and vstack:");
        System.out.println("vStack:\n" + vStack);
        System.out.println("hStack:\n" + hStack);
    }

crashes with:

    Error at [D:/jenkins/ws/dl4j-master-windows-x86_64-cpu/libnd4j/include/ops/declarable/generic/transforms/concat.cpp:147:0]:
    CONCAT op: input axis must be in range [0, 0], but got 1 instead!

    org.nd4j.linalg.exception.ND4JIllegalStateException: Op name concat failed to execute. You can't execute non-inplace CustomOp without outputs being specified

	at 
    org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1679)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6606)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.concat(CpuNDArrayFactory.java:557)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:4917)

    Process finished with exit code -1

#### Version Information
Beta5 examples ab_beta5  branch.
same result on SkymindIO sunday build. of nd4j.

* Platform information (OS, etc) 
Win10.

**Comment by AlexDBlack** [comment]
Good catch, this is a validation issue, for invalid input
`Nd4j.create(new double[]{1,2,3})` that's a [3] array, not a [1,3] as it used to be in earlier versions of ND4J.
