### ISSUE TITLE
class not found: org.nd4j.tools.PropertyParser

### ISSUE THREAD

**Issue by ssy248** [eclipse/deeplearning4j#8222]
When I run the code:

 MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
				.seed(12345)
				.l2(0.0001)
	            .weightInit(WeightInit.XAVIER)
	            .updater(new Adam(0.005))
				.list()
				.layer(new LSTM.Builder().nIn(iter.inputColumns()).nOut(lstmLayerSize)
						.activation(Activation.TANH).build())
				.layer(new LSTM.Builder().nIn(lstmLayerSize).nOut(lstmLayerSize)
						.activation(Activation.TANH).build())
				//.layer(new RnnOutputLayer.Builder(LossFunctions.MCXENT).activation(Activation.SOFTMAX)        //MCXENT + softmax for classification
				//.nIn(lstmLayerSize).nOut(nOut).build())
	            .backpropType(BackpropType.TruncatedBPTT).tBPTTForwardLength(tbpttLength).tBPTTBackwardLength(tbpttLength)
				.build();

Then I have the error 

Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/tools/PropertyParser
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5793)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5766)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:671)
	at javaspark.deeplearning2.main(deeplearning2.java:83)
Caused by: java.lang.ClassNotFoundException: org.nd4j.tools.PropertyParser
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

**Comment by AlexDBlack** [comment]
What version of DL4J/ND4J?
Can you provide your pom.xml (or equivalent)?

**Comment by ssy248** [comment]
> What version of DL4J/ND4J?
> Can you provide your pom.xml (or equivalent)?

Thanks for your help.

The dl4j version is 1.0.0-beta4

Sure, my pom file is given by: 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>javaspark</groupId>
  <artifactId>javaspark</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
   <dependency>
<groupId>org.apache.spark</groupId>
<artifactId>spark-core_2.11</artifactId>
<version>2.0.2</version>
</dependency>
<dependency>
          <groupId>org.apache.spark</groupId>
          <artifactId>spark-sql_2.11</artifactId>
          <version>2.0.2</version>
          <scope>compile</scope>
      </dependency>
      <dependency>
          <groupId>org.apache.spark</groupId>
          <artifactId>spark-mllib_2.11</artifactId>
          <version>2.0.2</version>
      </dependency>
      <dependency>
  <groupId>com.github.fommil.netlib</groupId>
  <artifactId>all</artifactId>
  <version>1.1.2</version>
  <type>pom</type>
</dependency>
<dependency>
    <groupId>net.sourceforge.f2j</groupId>
    <artifactId>arpack_combined_all</artifactId>
    <version>0.1</version>
</dependency>

<dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>1.0.0-beta4</version>
  </dependency>
  <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native</artifactId>
                <version>1.0.0-beta4</version>
            </dependency>
  <dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-api</artifactId>
    <version>0.4-rc3.3</version>
</dependency>
  <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>1.0.0-beta4</version>
  </dependency>
  <dependency><groupId>org.nd4j</groupId><artifactId>nd4j-api</artifactId><version>1.0.0-beta4</version></dependency>
  
<dependency>
    <groupId>org.datavec</groupId>
    <artifactId>datavec-api</artifactId>
    <version>0.9.1</version>
</dependency>
  
<dependency>
    <groupId>log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>1.2.17</version>
</dependency>
  
  </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by ssy248** [comment]
Sorry, let me put a link to the pom file: https://github.com/ssy248/deeplearningjava/blob/master/pom.xml

**Comment by AlexDBlack** [comment]
The problem here: You're mixing in a very old version of nd4j-api, 0.4-rc3.3, which is 4 years old. So of course you'll have issues with that.

Switch all of your DL4J/ND4J dependencies to the one version (1.0.0-beta5 is recommended) and try again.
