### ISSUE TITLE
SameDiff: Crash on SameDiffTrainingExample

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8235]
https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/samediff/training/SameDiffTrainingExample.java
on 1.0.0-beta5, CPU backend.

Based on stack trace - probably a serialization issue (crashing in SameDiff.asFlatBuffers)
Output and crash log:
https://gist.github.com/AlexDBlack/8ed13c370bafe793e9b5f304accbc744

**Comment by RobAltena** [comment]
I just reproduced this on Win10. Crashes on [this line](https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/samediff/training/SameDiffTrainingExample.java#L103):

**Comment by AlexDBlack** [comment]
Tested on current master, no issues in 10 runs. Probably fixed as part of the recent execution/memory management overhaul.
