### ISSUE TITLE
Prepping DL4j for Standalone Dist

### ISSUE THREAD

**Issue by ago109** [eclipse/deeplearning4j#89]
Hello there,

This is a port from my question on the Deeplearning4j Google Groups question regarding using DL4J and ND4J as standalone libraries to be called from an existing code-base/research library. The source post can be found at:
https://groups.google.com/forum/#!topic/deeplearning4j/6KslRm_8mzM

The complementary ND4J GitHub issue can be found at:
https://github.com/SkymindIO/nd4j/issues/6

The error I'm particularly worried about as reproduced/can be found in that post comes from my attempts to either importing into an Eclipse project the resulting JAR files created from running the Maven build command (and reaching a successful conclusion to the build), particularly when I import the following external jars and run a simple program as the vignette I attached to the soure GoogleGroups post.  While that vignette pertained to ND4J, I fear the same issue would come with trying to use DL4J in the same way.

Prepped distributions for each back-end combination would work as a good fix, I think. A simple use-case I would like to try is to use the pre-built Convolve operator in my own research library, much like one uses it in Python code when leveraging Numpy. This is part of my movement to upgrade my code from JBLAS to ND4J, which would also give me hooks to use for GPU computation in the future.  Another case would be make use of DL4J models by calling from the code base and respecting their API calls (but allow for flexibility in writing Java code independent of the way DL4J was configured but still make use of its internal functionality).

Thank you,
Alex Ororbia
Intelligent Systems & Applied Cognitive Science Laboratories
Pennsylvania State University

**Comment by danielhers** [comment]
@agibsonccc this link is dead.
