### ISSUE TITLE
Unable to load a google binary with Word2VecLoader

### ISSUE THREAD

**Issue by jaxonshi** [eclipse/deeplearning4j#90]
Trying to load a binary [word2vec](https://groups.google.com/d/msg/deeplearning4j/L_y-_hOs-bU/I-gVLRnZQ6kJ) model, I noticed `Word2VecLoader#loadGoogleBinary` doesn't instantiate `syn0`,`syn1` before calling:

``` java
cache.putVector(word, row);
```

I added:

``` java
cache.setSyn0(Nd4j.rand(new int[]{words+1, size}, cache.getRng()).subi(0.5).divi(size));
cache.putVector(Word2Vec.UNK,Nd4j.rand(1, size).subi(0.5).divi(size));
cache.setSyn1(Nd4j.create(cache.getSyn0().shape()));
cache.initNegative();
```

after:

``` java
cache = new InMemoryLookupCache.Builder().vectorLength(size).build();
```

I also set the token index before adding it to the `InMemoryLookupCache`. The model finishes loading with these changes, but the resulting vectors are not correct (in the sense that they don't match the original data, and cosine similarities between the vectors are nonsensical.)

I originally posted [here](https://groups.google.com/d/msg/deeplearning4j/L_y-_hOs-bU/I-gVLRnZQ6kJ). Adam replied that google has recently updated their binary format and dl4j's word vectors need to be updated accordingly.

**Comment by anupamme** [comment]
I am not able to find the method I need to call in order to load an existing binary model. Is loadGoogleBinary supposed to do that? Is this method not available in latest code (I am not able to find it)? If it is deprecated, what is the alternative?
