### ISSUE TITLE
Error in Word2VecLoad.loadGoogleBinary

### ISSUE THREAD

**Issue by aritasimoes** [eclipse/deeplearning4j#94]
In version 0.0.3.2.7, when loading (after unzipping) the Google pre-trained vectors <a href="https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing">GoogleNews-vectors-negative300.bin.gz</a> using Word2VecLoad.loadGoogleBinary, an exception occurs:

```
CompilerException java.lang.IllegalArgumentException: Word must not be null or empty
```

Alex Zivkovic has already looked into this and apparently some words are empty in the model. He proposed replacing line 72 of Word2VecLoader.java with:

```
            if (word!=null && !word.equals("")) {

                cache.putVocabWord(word, new VocabWord(1, word));

            }
```

**Comment by nrv** [comment]
It seems the bug is still there in 0.6.0 on some models (generated with gensim for exemple). It is now in WordVectorSerializer.readBinaryModel()
