### ISSUE TITLE
Glove on spark with ClassCastException

### ISSUE THREAD

**Issue by huangjiakun1991** [eclipse/deeplearning4j#948]
Hi, i'm testing the glove model on spark. My code is just from 
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/test/java/org/deeplearning4j/spark/models/embeddings/glove/GloveTest.java

However, I got ClassCastException on Spark:

15/12/10 11:18:19,045 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
    at org.deeplearning4j.spark.models.embeddings.word2vec.Word2VecVariables.assignVar(Word2VecVariables.java:59)
    at org.deeplearning4j.spark.models.embeddings.glove.Glove.train(Glove.java:124)
    at com.sohu.adrd.targering.wordvector.SparkTest.main(SparkTest.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:483)

Is there a bug or am I doing someting wrong?

**Comment by agibsonccc** [comment]
No - this is a bug. Thanks for reporting it.

**Comment by huangjiakun1991** [comment]
I notice that the problem is a method of class Word2VecVariables:

 @SuppressWarnings("unchecked")
    public static <T> T getDefault(String variableName) {
        return (T) defaultVals.get(variableName);
    }
...
ret = conf.getDouble(variableName, (Double) getDefault(variableName));
...

So what should I do to fix it temporally?

**Comment by fcesco** [comment]
I have the same issue. The problem as suggested by huangjiakun1991 is due to the default value of "negative" which is an integer.

**Comment by gerdhub** [comment]
A temporary workaround for this bug could be setting

`Word2VecVariables.defaultVals.put(NEGATIVE, 5.0);`

**Comment by raver119** [comment]
Our glove implementation is pending overhaul right now, as soon we
introduce general availability of parameter server, we will also introduce
w2v/paravec/glove implementations using it.

30 окт. 2016 г. 16:09 пользователь "Gerd Hübscher" <notifications@github.com>
написал:

**Comment by agibsonccc** [comment]
@raver119 will we be able to close this after the sequence vectors stuff is finished?

**Comment by raver119** [comment]
GloVe wasn't covered by spark overhaul yet (i had to switch to other task), but yep once i get time i'd like to provide GloVe for spark as well

**Comment by agibsonccc** [comment]
This is likely out of date by now?

**Comment by raver119** [comment]
Nope, sorry. 2nd pass still pending for new j8 spark w2v stuff, it'll be done together with new nlp pipeline.

**Comment by treo** [comment]
Closing due to GloVe feature removal. See https://github.com/eclipse/deeplearning4j/issues/7855#issuecomment-624616313
