### ISSUE TITLE
DeepWalk: problem with huffman tree if graph contains nodes with degree == 0

### ISSUE THREAD

**Issue by LukasMasuch** [eclipse/deeplearning4j#961]
Applying DeepWalk on a graph (1.7m nodes) containing some nodes with degree == 0 will result in this exception:
`java.lang.RuntimeException: Cannot generate code: code length exceeds 64 bits`

I assume, the problem is that the huffman tree will get quite unbalanced and deep because adding together two zero-degree nodes will result in zero. Thereby, the code length will be longer than 64bit.

``` Java
 public void buildTree(int[] vertexDegree) {
        PriorityQueue<Node> pq = new PriorityQueue<>();
        for (int i = 0; i < vertexDegree.length; i++) pq.add(new Node(i, vertexDegree[i], null, null));

        while (pq.size() > 1) {
            Node left = pq.remove();
            Node right = pq.remove();
            Node newNode = new Node(-1, left.count + right.count, left, right);
            pq.add(newNode);
        }
```

**Comment by AlexDBlack** [comment]
TODO: Add checking and handling of zero-degree vertices in graph, both for tree construction and for random walks / learning.

**Comment by agibsonccc** [comment]
Was this done yet?

**Comment by fgiasson** [comment]
@agibsonccc apparently not, I just experienced this issue.

**Comment by agibsonccc** [comment]
@raver119 how relevant is this for your rewrite?

**Comment by raver119** [comment]
Still relevant, DeepWalk is still bending transfer to SeqVec native code, plus Josh asked for nod2vec recently, which, basically, is the same DeepWalk with different walks generator.

**Comment by fgiasson** [comment]
@raver119 yes, there are many different algos that uses the same principles but with different walking strategies. However to my experience (with the older DeepWalk code, not the SeqVec transfer you are working on) it is quite easy to just extends DL4J to implement new walk algorithms.

Are Josh or you working on a new lists os walks? If so, is there a list of the ones that will get implemented?

**Comment by raver119** [comment]
it will be the same. the only difference for end-user: DeepWalk will be native, so significantly faster. You can have it right now via SeqVec,  i just need to make DeepWalk an actual wrapper for it. 

As for walks: i'm thinking about BFS/DFS.

**Comment by fgiasson** [comment]
@raver119 good.

About BFS/DFS they are good. I encountered DFS in at least one DeepWalk paper, but experiencing with differents makes sense for different projects. At that point, the walking method becomes yet another hyperparameter to test and setup.

**Comment by agibsonccc** [comment]
Closing stale issue: cleanup.
